/**
 * @file VisualScriptCompiler.cpp
 * @brief Implementation of visual script graph → AngelScript compiler
 */

#include "VisualScriptCompiler.h"

#include "VisualScriptEmitter.h"

#include "../../Utils/LogMacros.h"

#include <algorithm>
#include <sstream>
#include <utility>

namespace Spark::Scripting
{
    namespace
    {
        using namespace Detail;

        /// Method name and parameter list generated for a built-in event node.
        std::pair<std::string, std::string> EventSignature(ScriptNodeType type)
        {
            switch (type)
            {
            case ScriptNodeType::OnStart:
                return {"Start", ""};
            case ScriptNodeType::OnUpdate:
            case ScriptNodeType::OnKeyPress: // key checks live in Update, wrapped in getKeyDown()
                return {"Update", "float dt"};
            case ScriptNodeType::OnCollision:
                return {"OnCollision", "uint other"};
            case ScriptNodeType::OnTriggerEnter:
                return {"OnTriggerEnter", "uint triggerId"};
            case ScriptNodeType::OnTriggerExit:
                return {"OnTriggerExit", "uint triggerId"};
            case ScriptNodeType::OnDamaged:
                return {"OnDamaged", "float amount"};
            default:
                return {};
            }
        }

        bool IsCustomEventNode(ScriptNodeType type)
        {
            return type == ScriptNodeType::OnCustomEvent || type == ScriptNodeType::DefineCustomEvent;
        }

        std::string CustomEventMethodName(const CustomEventDef& evt)
        {
            return "On" + SanitizeIdentifier(evt.name, "CustomEvent");
        }

        std::string ParameterList(const std::vector<VariableDecl>& parameters)
        {
            std::string list;
            for (size_t i = 0; i < parameters.size(); ++i)
            {
                if (i > 0)
                    list += ", ";
                list += PinTypeString(parameters[i].type) + " " +
                        SanitizeIdentifier(parameters[i].name, ("p" + std::to_string(i)).c_str());
            }
            return list;
        }
    } // namespace

    // ========================================================================
    // Main Compile Entry Point
    // ========================================================================

    ScriptCompileResult VisualScriptCompiler::Compile(const VisualScriptGraph& graph, bool debugMode)
    {
        SPARK_LOG_INFO(Spark::LogCategory::Scripting, "VisualScriptCompiler::Compile — class='%s', nodes=%zu, debug=%s",
                       graph.className.c_str(), graph.nodes.size(), debugMode ? "true" : "false");
        ScriptCompileResult result;

        if (graph.nodes.empty())
        {
            SPARK_LOG_WARN(Spark::LogCategory::Scripting, "Compile failed: empty graph for class '%s'",
                           graph.className.c_str());
            result.errors.push_back("Empty graph — no nodes to compile");
            return result;
        }

        std::vector<const ScriptNode*> eventNodes;
        for (const auto& node : graph.nodes)
        {
            if (IsEventNode(node.type))
                eventNodes.push_back(&node);
        }
        if (eventNodes.empty())
        {
            SPARK_LOG_WARN(Spark::LogCategory::Scripting, "Compile failed: no event nodes in graph '%s'",
                           graph.className.c_str());
            result.errors.push_back("No event nodes found — add OnStart, OnUpdate, or another event node");
            return result;
        }

        for (const auto& var : graph.variables)
        {
            if (!IsVariableDefaultLiteral(var.type, var.defaultValue))
            {
                result.errors.push_back("Variable '" + var.name + "' default is not a " + PinTypeString(var.type) +
                                        " literal: " + EscapeAngelScriptString(var.defaultValue));
            }
        }

        const std::string className = SanitizeIdentifier(graph.className, "MyScript");
        std::ostringstream source;
        source << "// Auto-generated by SparkEngine Visual Script Compiler\n";
        source << "// Class: " << className << "\n";
        if (!graph.description.empty())
        {
            source << "//\n";
            std::istringstream description(graph.description);
            std::string line;
            while (std::getline(description, line))
            {
                std::erase_if(line, [](unsigned char c) { return c < 0x20 || c == 0x7F; });
                source << "//" << (line.empty() ? "" : " ") << line << "\n";
            }
        }
        source << "\nclass " << className << "\n{\n";
        source << "    uint selfEntity = 0; // Entity this script is attached to\n";

        for (const auto& var : graph.variables)
        {
            source << "    " << PinTypeString(var.type) << " " << SanitizeIdentifier(var.name, "var");
            if (!var.defaultValue.empty())
                source << " = " << var.defaultValue;
            source << ";\n";
        }

        // Group event nodes by generated method signature — OnKeyPress compiles into
        // Update(float dt), so OnUpdate plus OnKeyPress (or several OnKeyPress nodes)
        // share one method instead of producing duplicate definitions. A custom event
        // node's "event" property names a declared custom event, and its chain runs in
        // that event's On<Name>(parameters) method (raised in-graph with CallFunction).
        struct EventMethod
        {
            std::string name;
            std::string params;
            std::vector<const ScriptNode*> events;
        };
        std::vector<EventMethod> eventMethods;
        const auto methodFor = [&](std::string name, std::string params) -> EventMethod&
        {
            auto existing = std::find_if(eventMethods.begin(), eventMethods.end(),
                                         [&](const EventMethod& m) { return m.name == name && m.params == params; });
            if (existing != eventMethods.end())
                return *existing;
            return eventMethods.emplace_back(EventMethod{std::move(name), std::move(params), {}});
        };
        for (auto evt = graph.customEvents.begin(); evt != graph.customEvents.end(); ++evt)
        {
            const std::string name = CustomEventMethodName(*evt);
            if (std::any_of(graph.customEvents.begin(), evt,
                            [&](const CustomEventDef& earlier) { return CustomEventMethodName(earlier) == name; }))
                result.errors.push_back("Custom event '" + evt->name + "' generates method " + name + " twice");
        }
        for (const auto* eventNode : eventNodes)
        {
            if (!IsCustomEventNode(eventNode->type))
            {
                auto [name, params] = EventSignature(eventNode->type);
                methodFor(std::move(name), std::move(params)).events.push_back(eventNode);
                continue;
            }
            const std::string eventName = PropertyOr(*eventNode, "event", "");
            const auto declared = std::find_if(graph.customEvents.begin(), graph.customEvents.end(),
                                               [&](const CustomEventDef& evt) { return evt.name == eventName; });
            if (declared == graph.customEvents.end())
            {
                result.errors.push_back("Custom event node " + std::to_string(eventNode->id) +
                                        " names no declared custom event (event '" + eventName + "')");
                continue;
            }
            methodFor(CustomEventMethodName(*declared), ParameterList(declared->parameters))
                .events.push_back(eventNode);
        }
        // A declared event without a handler node still gets its empty method, so raising it compiles.
        for (const auto& evt : graph.customEvents)
            methodFor(CustomEventMethodName(evt), ParameterList(evt.parameters));

        VisualScriptEmitter emitter(graph, debugMode, result.errors);
        for (const auto& method : eventMethods)
        {
            source << "\n    void " << method.name << "(" << method.params << ")\n    {\n";
            for (const ScriptNode* eventNode : method.events)
            {
                std::string indent = "        ";
                std::string body;
                if (eventNode->type == ScriptNodeType::OnKeyPress)
                {
                    const std::string key = PropertyOr(*eventNode, "key", "Space");
                    body += indent + "if (getKeyDown(\"" + EscapeAngelScriptString(key) + "\"))\n" + indent + "{\n";
                    indent += kIndent;
                }
                for (uint32_t pin : emitter.ExecOutputPins(*eventNode))
                    emitter.EmitPinChains(*eventNode, pin, indent, body);
                if (eventNode->type == ScriptNodeType::OnKeyPress)
                    body += "        }\n";
                source << body;
            }
            source << "    }\n";
        }

        // Reusable function sub-graphs: each entry statement's execution chain in listed
        // order (control flow nests like in event methods), pure nodes at their point of use.
        for (const auto& func : graph.functions)
        {
            const std::string returnType =
                func.returnType == PinKind::Execution ? "void" : PinTypeString(func.returnType);
            source << "\n    " << returnType << " " << SanitizeIdentifier(func.name, "MyFunction") << "("
                   << ParameterList(func.parameters) << ")\n    {\n";

            VisualScriptGraph funcGraph;
            funcGraph.nodes = func.nodes;
            funcGraph.connections = func.connections;
            VisualScriptEmitter funcEmitter(funcGraph, debugMode, result.errors);
            std::string body;
            funcEmitter.EmitEntryChains(funcGraph.nodes, "        ", body);
            source << body << "    }\n";
        }

        source << "}\n";

        if (!result.errors.empty())
        {
            SPARK_LOG_WARN(Spark::LogCategory::Scripting, "Compile failed for '%s': %s", graph.className.c_str(),
                           result.errors.front().c_str());
            return result;
        }

        result.angelScriptSource = source.str();
        result.success = true;
        SPARK_LOG_INFO(Spark::LogCategory::Scripting, "Compile succeeded for '%s' — %zu bytes of AngelScript generated",
                       graph.className.c_str(), result.angelScriptSource.size());
        return result;
    }

} // namespace Spark::Scripting
