# Generates SparkServerBuildIdentity.h, the source identity SparkServer reports
# in its operator health snapshot. Runs in script mode (cmake -P) on every
# build, so the stamped commit is the checkout that was compiled, not the one
# that was last configured. The header is rewritten only when its content
# changes, so an unchanged tree does not recompile anything.
#
# Inputs (-D):
#   SPARK_SOURCE_DIR       repository root to query
#   SPARK_OUTPUT           header path to write
#   SPARK_VERSION          SPARK_ENGINE_VERSION (MAJOR.MINOR.PATCH)
#   SPARK_COMMIT_OVERRIDE  optional full commit hash, used only when git cannot report HEAD
#   SPARK_GIT_EXECUTABLE   optional git executable

foreach(_required IN ITEMS SPARK_SOURCE_DIR SPARK_OUTPUT SPARK_VERSION)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "SparkServerBuildIdentity.cmake requires -D${_required}=...")
    endif()
endforeach()
if(NOT SPARK_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "SPARK_ENGINE_VERSION must be MAJOR.MINOR.PATCH; got '${SPARK_VERSION}'")
endif()

set(_commit "unknown")
set(_tree_state "unknown")

# CMake regular expressions have no bounded repetition, so check the length
# separately: SHA-1 object names are 40 hex digits, SHA-256 ones 64.
function(_spark_is_full_commit_hash value result)
    string(LENGTH "${value}" _length)
    if(value MATCHES "^[0-9a-f]+$" AND (_length EQUAL 40 OR _length EQUAL 64))
        set(${result} TRUE PARENT_SCOPE)
    else()
        set(${result} FALSE PARENT_SCOPE)
    endif()
endfunction()

set(_override "")
if(NOT "${SPARK_COMMIT_OVERRIDE}" STREQUAL "")
    string(TOLOWER "${SPARK_COMMIT_OVERRIDE}" _override)
    _spark_is_full_commit_hash("${_override}" _override_valid)
    if(NOT _override_valid)
        message(FATAL_ERROR
            "SPARK_BUILD_COMMIT must be a full 40- or 64-hex commit hash; got '${SPARK_COMMIT_OVERRIDE}'")
    endif()
endif()

# Live git metadata always wins: SPARK_BUILD_COMMIT is a sticky cache
# variable, so letting it take precedence would keep stamping a stale commit
# into every later build of a real checkout.
set(_git_commit "")
if(NOT "${SPARK_GIT_EXECUTABLE}" STREQUAL "")
    execute_process(
        COMMAND "${SPARK_GIT_EXECUTABLE}" -C "${SPARK_SOURCE_DIR}" rev-parse --verify HEAD
        RESULT_VARIABLE _rev_result
        OUTPUT_VARIABLE _rev_output
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    _spark_is_full_commit_hash("${_rev_output}" _rev_valid)
    if(_rev_result EQUAL 0 AND _rev_valid)
        set(_git_commit "${_rev_output}")
    endif()
endif()

if(NOT _git_commit STREQUAL "")
    set(_commit "${_git_commit}")
    if(NOT _override STREQUAL "" AND NOT _override STREQUAL _git_commit)
        message(WARNING
            "SPARK_BUILD_COMMIT (${_override}) is ignored because git reports HEAD ${_git_commit}; "
            "clear the cache variable to silence this warning")
    endif()
    # --no-optional-locks keeps this query read-only: a plain status may
    # refresh and rewrite the index, which a build must never do.
    execute_process(
        COMMAND "${SPARK_GIT_EXECUTABLE}" --no-optional-locks -C "${SPARK_SOURCE_DIR}"
                status --porcelain --untracked-files=no
        RESULT_VARIABLE _status_result
        OUTPUT_VARIABLE _status_output
        ERROR_QUIET)
    if(_status_result EQUAL 0)
        if("${_status_output}" STREQUAL "")
            set(_tree_state "clean")
        else()
            set(_tree_state "dirty")
        endif()
    endif()
elseif(NOT _override STREQUAL "")
    # Source archives without git metadata: the tree state against the
    # supplied commit cannot be observed and stays unknown.
    set(_commit "${_override}")
endif()

set(_content "/**
 * @file SparkServerBuildIdentity.h
 * @brief Generated by SparkServer/cmake/SparkServerBuildIdentity.cmake. Do not edit.
 */

#pragma once

#define SPARK_SERVER_BUILD_VERSION \"${SPARK_VERSION}\"
#define SPARK_SERVER_BUILD_COMMIT \"${_commit}\"
#define SPARK_SERVER_BUILD_TREE_STATE \"${_tree_state}\"
")

set(_existing "")
if(EXISTS "${SPARK_OUTPUT}")
    file(READ "${SPARK_OUTPUT}" _existing)
endif()
if(NOT _existing STREQUAL _content)
    get_filename_component(_output_dir "${SPARK_OUTPUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${_output_dir}")
    file(WRITE "${SPARK_OUTPUT}" "${_content}")
endif()
