/**
 * @file Assert.h
 * @brief Comprehensive assertion and verification macro system for Spark Engine
 * @author Spark Engine Team
 * @date 2025
 *
 * Provides a rich set of assertion macros that go far beyond the standard C
 * assert(). Assertions in Spark Engine produce detailed diagnostic output
 * including timestamps, file/line location, thread IDs, and formatted user
 * messages before triggering a debugger breakpoint and aborting.
 *
 * ## Macro categories
 *
 * | Macro Family       | Active In     | Purpose                                     |
 * |--------------------|---------------|---------------------------------------------|
 * | ASSERT             | Debug only    | General-purpose expression check             |
 * | ASSERT_MSG         | Debug only    | Expression check with printf-style message   |
 * | ASSERT_ALWAYS      | All builds    | Critical checks that must never be stripped   |
 * | ASSERT_HR          | Debug only    | HRESULT success check (DirectX/COM calls)    |
 * | ASSERT_NOT_NULL    | Debug only    | Pointer non-null check                       |
 * | ASSERT_IN_RANGE    | Debug only    | Value range validation                       |
 * | ASSERT_BOUNDS      | Debug only    | Array index bounds check with diagnostic info|
 * | ASSERT_ENUM_RANGE  | Debug only    | Enum value range validation                  |
 * | VERIFY             | All builds    | Like ASSERT but never compiled out           |
 * | VERIFY_HR          | All builds    | Like ASSERT_HR but never compiled out         |
 *
 * ## Crash handler integration
 *
 * All assertion failures call TriggerCrashHandler() before aborting, which
 * allows the crash handler to generate a minidump if configured to do so.
 *
 * @see CrashHandler.h, DEBUG_BREAK
 */

#pragma once

#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <string>

/**
 * @def DEBUG_BREAK()
 * @brief Trigger a debugger breakpoint
 *
 * Platform-specific implementation:
 * - **MSVC** (all versions, including VS 2026): uses the intrinsic __debugbreak().
 * - **Modern Clang/GCC** (incl. Apple Clang, Intel LLVM, GCC 12+): uses the
 *   portable __builtin_debugtrap() when available via __has_builtin.
 * - **Fallback**: raise(SIGTRAP) on POSIX systems.
 */
#if defined(_MSC_VER)
#include <intrin.h>
#define DEBUG_BREAK() __debugbreak()
#elif defined(__has_builtin) && __has_builtin(__builtin_debugtrap)
// Clang 3.8+, Apple Clang, Intel LLVM (ICPX), GCC 12+
#define DEBUG_BREAK() __builtin_debugtrap()
#else
#include <signal.h>
#define DEBUG_BREAK() raise(SIGTRAP)
#endif

#ifdef _WIN32
#include <windows.h>
#include <dbghelp.h>
#pragma comment(lib, "dbghelp.lib")
#endif

// TriggerCrashHandler is defined in CrashHandler.cpp when available.
// When the crash handler is not built (e.g. missing miniz), provide a no-op
// fallback via a weak symbol (GCC/Clang) so the linker doesn't fail.
#if defined(__GNUC__) || defined(__clang__)
__attribute__((weak)) void TriggerCrashHandler(const char* /*assertMsg*/) {}
#else
void TriggerCrashHandler(const char* assertMsg);
#endif

/**
 * @brief Core assertion failure handling functions
 *
 * The Assert namespace contains the implementation functions called by the
 * ASSERT / VERIFY macros. They are not intended to be called directly — use
 * the macros instead, which automatically capture __FILE__ and __LINE__.
 */
namespace Assert
{
    /**
     * @brief Core assertion failure handler
     *
     * Formats a detailed diagnostic message including timestamp, expression,
     * file/line location, optional printf-style user message, and thread ID.
     * Outputs to stderr, triggers the crash handler, breaks into the debugger,
     * and aborts the process.
     *
     * @param expr Stringified expression that failed (auto-generated by macros via #expr)
     * @param file Source file path where the assertion failed (__FILE__)
     * @param line Line number where the assertion failed (__LINE__)
     * @param fmt  Optional printf-style format string for additional context (may be nullptr)
     * @param ...  Variadic arguments for the format string
     *
     * @note This function never returns — it always calls std::abort().
     */
    inline void Fail(const char* expr, const char* file, int line, const char* fmt = nullptr, ...)
    {
        // Timestamp
        std::time_t t = std::time(nullptr);
        char timeBuf[64];
        std::strftime(timeBuf, sizeof(timeBuf), "%Y-%m-%d %H:%M:%S", std::localtime(&t));

        // Format user message if provided
        char userMsg[512] = {};
        if (fmt)
        {
            va_list args;
            va_start(args, fmt);
            vsnprintf(userMsg, sizeof(userMsg), fmt, args);
            va_end(args);
        }

        // Build the full assertion text
        char fullMsg[2048];
        std::snprintf(fullMsg, sizeof(fullMsg),
                      "===== ASSERTION FAILED =====\n"
                      "Time       : %s\n"
                      "Expression : %s\n"
                      "Location   : %s(%d)\n"
                      "Message    : %s\n"
                      "Thread ID  : 0x%08X\n",
                      timeBuf, expr, file, line, userMsg[0] ? userMsg : "(none)",
#ifdef _WIN32
                      static_cast<unsigned>(GetCurrentThreadId())
#else
                      0u
#endif
        );

        // Print immediately
        std::fprintf(stderr, "%s", fullMsg);
        std::fflush(stderr);

        // Trigger optional crash handler
        TriggerCrashHandler(fullMsg);

        DEBUG_BREAK();
        std::abort();
    }

    /**
     * @brief HRESULT-specific assertion failure handler
     *
     * Similar to Fail() but includes the failing HRESULT value in the diagnostic
     * output, making it easier to identify DirectX/COM error codes.
     *
     * @param expr Stringified expression that returned the failing HRESULT
     * @param file Source file path (__FILE__)
     * @param line Line number (__LINE__)
     * @param hr   The failing HRESULT value
     * @param fmt  Optional printf-style format string for additional context
     * @param ...  Variadic arguments for the format string
     *
     * @note This function never returns — it always calls std::abort().
     */
    inline void FailHResult(const char* expr, const char* file, int line, long hr, const char* fmt = nullptr, ...)
    {
        char userMsg[512] = {};
        if (fmt)
        {
            va_list args;
            va_start(args, fmt);
            vsnprintf(userMsg, sizeof(userMsg), fmt, args);
            va_end(args);
        }

        char fullMsg[2048];
        std::snprintf(fullMsg, sizeof(fullMsg),
                      "===== HRESULT FAILED =====\n"
                      "Expression : %s returned 0x%08lX\n"
                      "Location   : %s(%d)\n"
                      "Message    : %s\n"
                      "Thread ID  : 0x%08X\n",
                      expr, hr, file, line, userMsg[0] ? userMsg : "(none)",
#ifdef _WIN32
                      static_cast<unsigned>(GetCurrentThreadId())
#else
                      0u
#endif
        );

        std::fprintf(stderr, "%s", fullMsg);
        std::fflush(stderr);

        TriggerCrashHandler(fullMsg);
        DEBUG_BREAK();
        std::abort();
    }
} // namespace Assert

// ============================================================================
// Debug-only assertions (compiled out in Release builds)
// ============================================================================

/**
 * @def ASSERT(expr)
 * @brief Debug-only assertion — evaluates @p expr and aborts if false
 * @param expr Boolean expression to check
 */
#if defined(_DEBUG) || defined(DEBUG)
#define ASSERT(expr) ((expr) ? (void)0 : Assert::Fail(#expr, __FILE__, __LINE__))
#else
#define ASSERT(expr) ((void)0)
#endif

/**
 * @def ASSERT_MSG(expr, fmt, ...)
 * @brief Debug-only assertion with a printf-style diagnostic message
 * @param expr Boolean expression to check
 * @param fmt  Printf-style format string
 */
#if defined(_DEBUG) || defined(DEBUG)
#define ASSERT_MSG(expr, fmt, ...) ((expr) ? (void)0 : Assert::Fail(#expr, __FILE__, __LINE__, fmt, ##__VA_ARGS__))
#else
#define ASSERT_MSG(expr, fmt, ...) ((void)0)
#endif

// ============================================================================
// Always-on assertions (active in all builds unless explicitly disabled)
// ============================================================================

/**
 * @def ASSERT_ALWAYS(expr)
 * @brief Assertion that is active in ALL builds (debug and release)
 *
 * Use for invariants that must never be violated, even in production.
 * Can be disabled globally by defining DISABLE_ALWAYS_ASSERTS.
 *
 * @param expr Boolean expression to check
 */

/**
 * @def ASSERT_ALWAYS_MSG(expr, fmt, ...)
 * @brief Always-on assertion with a printf-style diagnostic message
 * @param expr Boolean expression to check
 * @param fmt  Printf-style format string
 */
#if !defined(DISABLE_ALWAYS_ASSERTS)
#define ASSERT_ALWAYS(expr) ((expr) ? (void)0 : Assert::Fail(#expr, __FILE__, __LINE__))
#define ASSERT_ALWAYS_MSG(expr, fmt, ...)                                                                              \
    ((expr) ? (void)0 : Assert::Fail(#expr, __FILE__, __LINE__, fmt, ##__VA_ARGS__))
#else
#define ASSERT_ALWAYS(expr) ((void)0)
#define ASSERT_ALWAYS_MSG(expr, fmt, ...) ((void)0)
#endif

// ============================================================================
// HRESULT-specific assertions (for DirectX/COM calls)
// ============================================================================

/**
 * @def ASSERT_HR(hrExpr)
 * @brief Debug-only assertion that checks an HRESULT for success
 *
 * Evaluates the expression, checks if FAILED(hr), and triggers FailHResult()
 * with the hex HRESULT value if the call failed.
 *
 * @param hrExpr Expression returning an HRESULT
 */

/**
 * @def ASSERT_HR_MSG(hrExpr, fmt, ...)
 * @brief Debug-only HRESULT assertion with a diagnostic message
 * @param hrExpr Expression returning an HRESULT
 * @param fmt    Printf-style format string
 */
#if defined(_DEBUG) || defined(DEBUG)
#define ASSERT_HR(hrExpr)                                                                                              \
    do                                                                                                                 \
    {                                                                                                                  \
        long _hr = static_cast<long>(hrExpr);                                                                          \
        if (FAILED(_hr))                                                                                               \
            Assert::FailHResult(#hrExpr, __FILE__, __LINE__, _hr);                                                     \
    } while (0)

#define ASSERT_HR_MSG(hrExpr, fmt, ...)                                                                                \
    do                                                                                                                 \
    {                                                                                                                  \
        long _hr = static_cast<long>(hrExpr);                                                                          \
        if (FAILED(_hr))                                                                                               \
            Assert::FailHResult(#hrExpr, __FILE__, __LINE__, _hr, fmt, ##__VA_ARGS__);                                 \
    } while (0)
#else
#define ASSERT_HR(hrExpr) ((void)(hrExpr))
#define ASSERT_HR_MSG(hrExpr, fmt, ...) ((void)(hrExpr))
#endif

// ============================================================================
// Specialized assertion macros
// ============================================================================

/**
 * @def ASSERT_NOT_NULL(ptr)
 * @brief Debug-only null-pointer check with the pointer name in the message
 * @param ptr Pointer to check for non-null
 */
#define ASSERT_NOT_NULL(ptr) ASSERT_MSG((ptr) != nullptr, "Pointer " #ptr " must not be null")

/**
 * @def ASSERT_NOT_NULL_ALWAYS(ptr)
 * @brief Always-on null-pointer check
 * @param ptr Pointer to check for non-null
 */
#define ASSERT_NOT_NULL_ALWAYS(ptr) ASSERT_ALWAYS_MSG((ptr) != nullptr, "Pointer " #ptr " must not be null")

/**
 * @def ASSERT_IN_RANGE(v, min, max)
 * @brief Debug-only range check: asserts min <= v <= max
 * @param v   Value to check
 * @param min Minimum allowed value (inclusive)
 * @param max Maximum allowed value (inclusive)
 */
#define ASSERT_IN_RANGE(v, min, max) ASSERT_MSG((v) >= (min) && (v) <= (max), #v " out of range [" #min "," #max "]")

// ============================================================================
// VERIFY macros (always active, never compiled out)
// ============================================================================

/**
 * @def VERIFY(expr)
 * @brief Like ASSERT but active in ALL builds (debug and release)
 *
 * Use for conditions that should never fail even in production. Unlike
 * ASSERT, VERIFY always evaluates the expression and always triggers
 * a failure if the condition is false.
 *
 * @param expr Boolean expression to check
 */
#define VERIFY(expr) ((expr) ? (void)0 : Assert::Fail(#expr, __FILE__, __LINE__))

/**
 * @def VERIFY_MSG(expr, fmt, ...)
 * @brief VERIFY with a printf-style diagnostic message
 * @param expr Boolean expression to check
 * @param fmt  Printf-style format string
 */
#define VERIFY_MSG(expr, fmt, ...) ((expr) ? (void)0 : Assert::Fail(#expr, __FILE__, __LINE__, fmt, ##__VA_ARGS__))

/**
 * @def VERIFY_HR(hrExpr)
 * @brief HRESULT check active in ALL builds
 * @param hrExpr Expression returning an HRESULT
 */
#define VERIFY_HR(hrExpr)                                                                                              \
    do                                                                                                                 \
    {                                                                                                                  \
        long _hr = static_cast<long>(hrExpr);                                                                          \
        if (FAILED(_hr))                                                                                               \
            Assert::FailHResult(#hrExpr, __FILE__, __LINE__, _hr);                                                     \
    } while (0)

/**
 * @def ASSERT_BOUNDS(index, size)
 * @brief Debug-only bounds check that prints the actual index vs. valid range
 *
 * Produces a diagnostic message like: "i = 42 out of bounds [0, 10)"
 *
 * @param index Array index to validate
 * @param size  Size of the array (valid indices: [0, size))
 */
#define ASSERT_BOUNDS(index, size)                                                                                     \
    ASSERT_MSG(static_cast<long long>(index) >= 0 && static_cast<size_t>(index) < (size),                              \
               #index " = %lld out of bounds [0, %llu)", static_cast<long long>(index),                                \
               static_cast<unsigned long long>(size))

/**
 * @def ASSERT_ENUM_RANGE(val, maxVal)
 * @brief Debug-only enum range check that prints the actual vs. valid range
 *
 * Validates that an enum value is within [0, maxVal). Useful for catching
 * out-of-range enum casts from untrusted data.
 *
 * @param val    Enum value to validate
 * @param maxVal One-past-the-end maximum (typically the COUNT sentinel)
 */
#define ASSERT_ENUM_RANGE(val, maxVal)                                                                                 \
    ASSERT_MSG(static_cast<int>(val) >= 0 && static_cast<int>(val) < static_cast<int>(maxVal),                         \
               #val " enum value %d out of valid range [0, %d)", static_cast<int>(val), static_cast<int>(maxVal))
