#!/usr/bin/env python3
"""RDY-020: every asset-integrity entry carries license and provenance metadata.

The root manifest (schema v2) records, per file, a license identifier and a
provenance statement resolved deterministically from the reviewed policy in
tools/asset-integrity/provenance.json. These tests prove that resolution fails
closed: an unclaimed, ambiguously claimed, stale, or tampered provenance claim
is an error, never a silent default.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "tools" / "asset-integrity" / "verify_asset_integrity.py"
SPEC = importlib.util.spec_from_file_location("verify_asset_integrity_provenance", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
vai = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(vai)

SITE_DATA_DIR = REPO_ROOT / "tools" / "site-data"
sys.path.insert(0, str(SITE_DATA_DIR))
import validate as site_data_validate  # noqa: E402

REPO_POLICY = REPO_ROOT / "tools" / "asset-integrity" / "provenance.json"
REPO_MANIFEST = REPO_ROOT / "Assets" / "assets.integrity.json"


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


GENERATED = b"generated payload\n"
SCENE = b'{"scene": 1}\n'
THIRD_PARTY = b"RIFF third party\n"
UNRECORDED = b"unrecorded payload\n"


class Fixture:
    """A miniature repository: repo/Assets plus evidence and a policy."""

    def __init__(self, base: Path) -> None:
        self.repo = base / "repo"
        self.assets = self.repo / "Assets"
        self.policy_path = self.repo / "tools" / "asset-integrity" / "provenance.json"
        (self.assets / "Generated").mkdir(parents=True)
        (self.assets / "Scenes").mkdir()
        (self.assets / "Third").mkdir()
        (self.assets / "Unrecorded").mkdir()
        self.policy_path.parent.mkdir(parents=True)
        (self.repo / "LICENSE").write_text("Fixture License\n", encoding="utf-8")
        (self.repo / "tools" / "gen.py").write_text("# generator\n", encoding="utf-8")
        (self.assets / "Generated" / "a.bin").write_bytes(GENERATED)
        (self.assets / "Scenes" / "level.scene").write_bytes(SCENE)
        (self.assets / "Third" / "shot.wav").write_bytes(THIRD_PARTY)
        (self.assets / "Unrecorded" / "blob.png").write_bytes(UNRECORDED)
        self.records = {
            "files": [
                {
                    "path": "Third/shot.wav",
                    "source_pack": "Fixture Pack",
                    "author": "Fixture Author",
                    "url": "https://example.invalid/pack",
                    "license": "CC0-1.0",
                }
            ]
        }
        self.write_records()
        self.policy = {
            "version": 1,
            "root": "Assets",
            "licenses": {
                "CC0-1.0": {"name": "Creative Commons Zero v1.0 Universal"},
                "LicenseRef-Fixture": {"name": "Fixture License"},
                "NOASSERTION": {"name": "No license asserted"},
            },
            "rules": [
                {
                    "id": "generator",
                    "license": "CC0-1.0",
                    "provenance": "Generated by tools/gen.py",
                    "evidence": ["tools/gen.py"],
                    "files": {"Generated/a.bin": digest(GENERATED)},
                },
                {
                    "id": "authored",
                    "license": "LicenseRef-Fixture",
                    "provenance": "Repository-authored content",
                    "evidence": ["LICENSE"],
                    "prefixes": ["Scenes/", "Third/"],
                },
                {
                    "id": "third-party",
                    "license": "CC0-1.0",
                    "provenance": "Third-party import",
                    "evidence": ["Assets/Third/records.json"],
                    "records": [{"path": "Assets/Third/records.json", "format": "terrafront-asset-manifest"}],
                },
                {
                    "id": "unrecorded",
                    "license": "NOASSERTION",
                    "provenance": "No tracked origin record",
                    "evidence": [],
                    "gap": "RDY-020",
                    "prefixes": ["Unrecorded/"],
                },
            ],
        }
        self.write_policy()

    def write_records(self) -> None:
        (self.assets / "Third" / "records.json").write_text(
            json.dumps(self.records, indent=2) + "\n", encoding="utf-8")

    def write_policy(self) -> None:
        self.policy_path.write_text(json.dumps(self.policy, indent=2) + "\n", encoding="utf-8")

    def rule(self, rule_id: str) -> dict:
        return next(rule for rule in self.policy["rules"] if rule["id"] == rule_id)

    def generate(self) -> tuple[dict, list]:
        return vai.generate_manifest(self.assets, provenance_policy=self.policy_path)

    def generate_to_disk(self) -> Path:
        manifest, errors = self.generate()
        if errors:
            raise AssertionError("\n".join(str(error) for error in errors))
        path = self.assets / vai.MANIFEST_FILENAME
        vai.write_manifest(manifest, path)
        return path

    def verify(self, **kwargs) -> list:
        kwargs.setdefault("provenance_policy", self.policy_path)
        return vai.verify_manifest(self.assets / vai.MANIFEST_FILENAME, self.assets, **kwargs)


def categories(errors) -> set[str]:
    return {error.category for error in errors}


class RepositoryProvenanceTests(unittest.TestCase):
    def test_repository_manifest_records_license_and_provenance_for_every_entry(self) -> None:
        manifest = vai.load_manifest(REPO_MANIFEST)
        self.assertEqual(manifest["version"], 2)
        self.assertGreater(manifest["fileCount"], 0)
        for entry in manifest["entries"]:
            with self.subTest(path=entry["path"]):
                self.assertEqual(set(entry), {"path", "sha256", "size", "license", "provenance"})
                self.assertTrue(entry["license"])
                self.assertTrue(entry["provenance"])

    def test_repository_manifest_matches_reviewed_policy(self) -> None:
        errors = vai.verify_manifest(
            REPO_MANIFEST, REPO_ROOT / "Assets",
            provenance_policy=REPO_POLICY, require_provenance=True)
        self.assertEqual(errors, [], "\n".join(str(error) for error in errors))

    def test_unasserted_repository_licenses_are_owned_gaps(self) -> None:
        policy = vai.load_provenance_policy(REPO_POLICY)
        for rule in policy["rules"]:
            with self.subTest(rule=rule["id"]):
                if rule["license"] == "NOASSERTION":
                    self.assertRegex(rule.get("gap", ""), r"^[A-Z]+-[0-9]{3}$")
                else:
                    self.assertNotIn("gap", rule)
                    self.assertTrue(rule["evidence"])

    def test_regeneration_from_policy_is_byte_identical_to_tracked_manifest(self) -> None:
        manifest, errors = vai.generate_manifest(REPO_ROOT / "Assets", provenance_policy=REPO_POLICY)
        self.assertEqual(errors, [], "\n".join(str(error) for error in errors))
        again, errors_again = vai.generate_manifest(REPO_ROOT / "Assets", provenance_policy=REPO_POLICY)
        self.assertEqual(errors_again, [])
        self.assertEqual(vai.manifest_bytes(manifest), vai.manifest_bytes(again))
        self.assertEqual(vai.manifest_bytes(manifest), REPO_MANIFEST.read_bytes())

    def test_check_all_cli_reports_provenance_summary(self) -> None:
        result = subprocess.run(
            [sys.executable, "-B", str(SCRIPT), "check-all"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=300, check=False)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertRegex(result.stdout, r"provenance: \d+ entries, \d+ license-asserted, \d+ NOASSERTION")


class ProvenanceGenerationTests(unittest.TestCase):
    def test_generation_attaches_license_and_provenance(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            manifest, errors = fixture.generate()
        self.assertEqual(errors, [], errors)
        self.assertEqual(manifest["version"], 2)
        by_path = {entry["path"]: entry for entry in manifest["entries"]}
        self.assertEqual(by_path["Generated/a.bin"]["license"], "CC0-1.0")
        self.assertIn("tools/gen.py", by_path["Generated/a.bin"]["provenance"])
        self.assertEqual(by_path["Scenes/level.scene"]["license"], "LicenseRef-Fixture")
        # An exact record claim beats the broader "Third/" prefix claim.
        self.assertEqual(by_path["Third/shot.wav"]["license"], "CC0-1.0")
        self.assertIn("Fixture Pack by Fixture Author", by_path["Third/shot.wav"]["provenance"])
        # The record file itself falls back to the longest matching prefix.
        self.assertEqual(by_path["Third/records.json"]["license"], "LicenseRef-Fixture")
        self.assertEqual(by_path["Unrecorded/blob.png"]["license"], "NOASSERTION")
        self.assertIn("RDY-020", by_path["Unrecorded/blob.png"]["provenance"])

    def test_cli_generation_is_deterministic_and_verifies(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            args = argparse.Namespace(root=str(fixture.assets), output=None, provenance=str(fixture.policy_path))
            self.assertEqual(vai.cmd_generate(args), 0)
            first = (fixture.assets / vai.MANIFEST_FILENAME).read_bytes()
            self.assertEqual(vai.cmd_generate(args), 0)
            self.assertEqual((fixture.assets / vai.MANIFEST_FILENAME).read_bytes(), first)
            self.assertEqual(fixture.verify(require_provenance=True), [])

    def test_unclaimed_file_refuses_generation(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            (fixture.assets / "Stray").mkdir()
            (fixture.assets / "Stray" / "new.bin").write_bytes(b"new")
            _, errors = fixture.generate()
            args = argparse.Namespace(root=str(fixture.assets), output=None, provenance=str(fixture.policy_path))
            self.assertEqual(vai.cmd_generate(args), 1)
            self.assertFalse((fixture.assets / vai.MANIFEST_FILENAME).exists())
        self.assertIn("provenance-unclaimed", categories(errors))

    def test_hash_bound_claim_goes_stale_when_bytes_change(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            (fixture.assets / "Generated" / "a.bin").write_bytes(b"hand edited\n")
            _, errors = fixture.generate()
        self.assertIn("provenance-stale", categories(errors))

    def test_exact_claim_for_absent_file_fails(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.rule("generator")["files"]["Generated/gone.bin"] = "0" * 64
            fixture.write_policy()
            _, errors = fixture.generate()
        self.assertIn("provenance-record-missing", categories(errors))

    def test_unused_prefix_claim_fails(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.rule("authored")["prefixes"].append("Nothing/")
            fixture.write_policy()
            _, errors = fixture.generate()
        self.assertIn("provenance-unused-claim", categories(errors))

    def test_two_exact_claims_on_one_file_are_ambiguous(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.rule("authored")["files"] = {"Generated/a.bin": digest(GENERATED)}
            fixture.write_policy()
            _, errors = fixture.generate()
        self.assertIn("provenance-ambiguous", categories(errors))

    def test_duplicate_prefix_across_rules_is_ambiguous(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.rule("unrecorded")["prefixes"].append("Scenes/")
            fixture.write_policy()
            _, errors = fixture.generate()
        self.assertIn("provenance-ambiguous", categories(errors))

    def test_record_license_must_agree_with_rule(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.records["files"][0]["license"] = "CC-BY-4.0"
            fixture.write_records()
            fixture.rule("generator")["files"] = {"Generated/a.bin": digest(GENERATED)}
            fixture.write_policy()
            _, errors = fixture.generate()
        self.assertIn("provenance-record-conflict", categories(errors))

    def test_record_naming_absent_file_fails(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.records["files"].append(dict(fixture.records["files"][0], path="Third/gone.wav"))
            fixture.write_records()
            _, errors = fixture.generate()
        self.assertIn("provenance-record-missing", categories(errors))

    def test_superseded_record_must_be_explicitly_excluded(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.rule("third-party")["records"][0]["exclude"] = ["Third/shot.wav"]
            fixture.write_policy()
            manifest, errors = fixture.generate()
            self.assertEqual(errors, [])
            by_path = {entry["path"]: entry for entry in manifest["entries"]}
            # The excluded record falls back to the prefix claim.
            self.assertEqual(by_path["Third/shot.wav"]["license"], "LicenseRef-Fixture")

            fixture.rule("third-party")["records"][0]["exclude"] = ["Third/not-a-record.wav"]
            fixture.write_policy()
            _, errors = fixture.generate()
        self.assertIn("provenance-policy", categories(errors))

    def test_hash_bound_record_formats_detect_stale_bytes(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            starter = {
                "assets": [
                    {"path": "Assets/Scenes/level.obj", "sha256": digest(b"obj"), "mtlSha256": digest(b"mtl")},
                    {"path": "Templates/Elsewhere/model.obj", "sha256": "0" * 64, "mtlSha256": "0" * 64},
                ]
            }
            (fixture.assets / "Scenes" / "level.obj").write_bytes(b"obj")
            (fixture.assets / "Scenes" / "level.mtl").write_bytes(b"mtl")
            (fixture.repo / "starter.json").write_text(json.dumps(starter), encoding="utf-8")
            fixture.policy["rules"].append({
                "id": "starter",
                "license": "LicenseRef-Fixture",
                "provenance": "Starter model pipeline",
                "evidence": ["starter.json"],
                "records": [{"path": "starter.json", "format": "starter-model-manifest"}],
            })
            fixture.write_policy()
            manifest, errors = fixture.generate()
            self.assertEqual(errors, [])
            by_path = {entry["path"]: entry for entry in manifest["entries"]}
            self.assertIn("Starter model pipeline", by_path["Scenes/level.mtl"]["provenance"])

            (fixture.assets / "Scenes" / "level.mtl").write_bytes(b"edited mtl")
            _, errors = fixture.generate()
        self.assertIn("provenance-stale", categories(errors))


class ProvenancePolicyValidationTests(unittest.TestCase):
    def assert_policy_error(self, mutate) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            mutate(fixture.policy)
            fixture.write_policy()
            _, errors = fixture.generate()
        self.assertIn("provenance-policy", categories(errors), errors)

    def test_noassertion_rule_requires_owning_gap(self) -> None:
        self.assert_policy_error(lambda policy: policy["rules"][3].pop("gap"))

    def test_asserted_license_rejects_gap_and_requires_evidence(self) -> None:
        self.assert_policy_error(lambda policy: policy["rules"][0].__setitem__("gap", "RDY-020"))
        self.assert_policy_error(lambda policy: policy["rules"][0].__setitem__("evidence", []))

    def test_unknown_license_unknown_key_and_duplicate_id_fail(self) -> None:
        self.assert_policy_error(lambda policy: policy["rules"][0].__setitem__("license", "MIT"))
        self.assert_policy_error(lambda policy: policy["rules"][0].__setitem__("licence", "CC0-1.0"))
        self.assert_policy_error(lambda policy: policy["rules"][1].__setitem__("id", "generator"))

    def test_missing_or_unsafe_evidence_fails(self) -> None:
        self.assert_policy_error(lambda policy: policy["rules"][0].__setitem__("evidence", ["tools/absent.py"]))
        self.assert_policy_error(lambda policy: policy["rules"][0].__setitem__("evidence", ["../outside.py"]))

    def test_unsafe_claim_paths_and_unknown_record_format_fail(self) -> None:
        self.assert_policy_error(
            lambda policy: policy["rules"][1].__setitem__("prefixes", ["../Scenes/"]))
        self.assert_policy_error(
            lambda policy: policy["rules"][1].__setitem__("prefixes", ["Scenes"]))
        self.assert_policy_error(
            lambda policy: policy["rules"][2]["records"][0].__setitem__("format", "guess"))

    def test_policy_root_must_match_asset_root(self) -> None:
        self.assert_policy_error(lambda policy: policy.__setitem__("root", "Other"))

    def test_absent_policy_fails_closed(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.policy_path.unlink()
            _, errors = fixture.generate()
            args = argparse.Namespace(root=str(fixture.assets), output=None, provenance=str(fixture.policy_path))
            self.assertEqual(vai.cmd_generate(args), 1)
        self.assertIn("provenance-policy", categories(errors))


class ProvenanceVerificationTests(unittest.TestCase):
    def test_tampered_license_is_detected(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            path = fixture.generate_to_disk()
            data = json.loads(path.read_text(encoding="utf-8"))
            data["entries"][-1]["license"] = "CC0-1.0"
            path.write_bytes(vai.manifest_bytes(data))
            errors = fixture.verify()
        self.assertIn("provenance-mismatch", categories(errors))

    def test_tampered_provenance_text_is_detected(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            path = fixture.generate_to_disk()
            data = json.loads(path.read_text(encoding="utf-8"))
            data["entries"][0]["provenance"] = "Totally original"
            path.write_bytes(vai.manifest_bytes(data))
            errors = fixture.verify()
        self.assertIn("provenance-mismatch", categories(errors))

    def test_v2_entry_without_license_fields_fails_to_load(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            path = fixture.generate_to_disk()
            for mutation in ("drop", "empty", "control"):
                data = json.loads(path.read_text(encoding="utf-8"))
                entry = data["entries"][0]
                if mutation == "drop":
                    del entry["license"]
                elif mutation == "empty":
                    entry["provenance"] = ""
                else:
                    entry["provenance"] = "bad\u0007text"
                path.write_bytes(vai.manifest_bytes(data))
                with self.subTest(mutation=mutation):
                    self.assertEqual(fixture.verify()[0].category, "manifest-load")

    def test_legacy_manifest_fails_when_provenance_is_required(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            legacy, errors = vai.generate_manifest(fixture.assets)
            self.assertEqual(errors, [])
            self.assertEqual(legacy["version"], 1)
            vai.write_manifest(legacy, fixture.assets / vai.MANIFEST_FILENAME)
            # Integrity-only verification of a legacy package manifest still works...
            self.assertEqual(vai.verify_manifest(fixture.assets / vai.MANIFEST_FILENAME, fixture.assets), [])
            # ...but a provenance-required gate refuses it.
            errors = fixture.verify(require_provenance=True)
        self.assertIn("provenance-missing", categories(errors))

    def test_absent_manifest_fails_closed(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            errors = fixture.verify(require_provenance=True)
        self.assertEqual(categories(errors), {"manifest-load"})

    def test_integrity_failures_still_reported_with_provenance(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.generate_to_disk()
            (fixture.assets / "Scenes" / "level.scene").write_bytes(b"modified")
            (fixture.assets / "Scenes" / "extra.scene").write_bytes(b"extra")
            (fixture.assets / "Unrecorded" / "blob.png").unlink()
            errors = fixture.verify(require_provenance=True)
        self.assertTrue({"hash-mismatch", "undeclared", "missing"} <= categories(errors), errors)


class SiteDataProvenanceGateTests(unittest.TestCase):
    def make_root(self, base: Path, *, v2: bool) -> Path:
        fixture = Fixture(base)
        root = fixture.repo
        (root / "Shaders").mkdir()
        graphics = root / "SparkEngine" / "Source" / "Graphics"
        graphics.mkdir(parents=True)
        (graphics / "AssetPipeline.cpp").write_text("// fixture\n", encoding="utf-8")
        (root / "tools" / "asset-integrity" / SCRIPT.name).write_bytes(SCRIPT.read_bytes())
        if v2:
            fixture.generate_to_disk()
        else:
            legacy, errors = vai.generate_manifest(fixture.assets)
            assert not errors
            vai.write_manifest(legacy, fixture.assets / vai.MANIFEST_FILENAME)
        return root

    def validate_fixture(self, root: Path) -> list[str]:
        with (
            mock.patch.object(site_data_validate, "REPO_ROOT", root),
            mock.patch.object(site_data_validate, "validate_assets", return_value=[]),
        ):
            validator = site_data_validate.Validator({})
            validator.validate_asset_surface()
        return validator.errors

    def test_site_data_gate_accepts_policy_consistent_v2_manifest(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            errors = self.validate_fixture(self.make_root(Path(temporary), v2=True))
        self.assertEqual(errors, [])

    def test_site_data_gate_rejects_manifest_without_provenance(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            errors = self.validate_fixture(self.make_root(Path(temporary), v2=False))
        self.assertTrue(any("provenance" in error for error in errors), errors)

    def test_site_data_gate_rejects_missing_policy(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = self.make_root(Path(temporary), v2=True)
            (root / "tools" / "asset-integrity" / "provenance.json").unlink()
            errors = self.validate_fixture(root)
        self.assertTrue(any("provenance" in error for error in errors), errors)


if __name__ == "__main__":
    unittest.main()
