/**
 * @file FormationSystem.h
 * @brief Formation management for AI groups
 * @author Spark Engine Team
 * @date 2026
 *
 * @details
 * Provides a formation system that arranges groups of AI entities into
 * tactical shapes (line, wedge, column, circle, spread). Each formation
 * has a leader entity whose position and heading drive the world-space
 * positions of all slots. Agents are assigned to slots and query their
 * target position each frame to maintain formation.
 *
 * ## Architecture
 * ```
 * FormationSystem (singleton)
 *   ├── m_templates       (built-in templates per FormationType)
 *   ├── m_formations      (active formation instances, keyed by ID)
 *   └── Update(dt)
 *         └── For each formation: update center/heading from leader
 * ```
 *
 * ## Usage
 * @code
 *   auto& fs = Spark::AI::FormationSystem::GetInstance();
 *   fs.Initialize();
 *
 *   uint32_t fid = fs.CreateFormation(FormationType::Wedge, leaderEntity, 5, 3.0f);
 *   fs.AssignToSlot(fid, soldierA);
 *   fs.AssignToSlot(fid, soldierB);
 *
 *   // Each frame:
 *   fs.Update(deltaTime);
 *   XMFLOAT3 target = fs.GetSlotWorldPosition(fid, 0);
 * @endcode
 *
 * @see GroupAI.h (group tactics reference formations)
 */

#pragma once

#include "../../Core/Platform.h"

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

namespace Spark::AI
{

    // =========================================================================
    // Formation Types
    // =========================================================================

    /** @brief Supported formation shapes. */
    enum class FormationType : uint8_t
    {
        Line,   ///< Side-by-side horizontal line
        Wedge,  ///< V-shaped arrowhead (leader at front)
        Column, ///< Single-file behind leader
        Circle, ///< Ring around formation center
        Spread  ///< Loose scatter with randomized offsets
    };

    // =========================================================================
    // Formation Data Structures
    // =========================================================================

    /**
     * @brief A single position slot within a formation.
     *
     * Each slot has a local-space offset from the formation center.
     * When an entity is assigned, `occupied` is set to true.
     */
    struct FormationSlot
    {
        XMFLOAT3 localOffset{0.0f, 0.0f, 0.0f}; ///< Offset from formation center (local space)
        uint32_t assignedEntity = 0;            ///< Entity occupying this slot (0 = unassigned)
        bool occupied = false;                  ///< Whether this slot is currently taken
    };

    /**
     * @brief Template defining the shape and spacing for a formation type.
     *
     * Templates are generated by the FormationSystem at initialization for
     * each FormationType. They define the local-space offsets for each slot.
     */
    struct FormationTemplate
    {
        FormationType type = FormationType::Line;
        float spacing = 3.0f;             ///< Distance between adjacent slots
        std::vector<FormationSlot> slots; ///< Template slot positions
    };

    /**
     * @brief A live formation instance with assigned entities.
     *
     * Created via CreateFormation(). The center and heading are updated
     * each frame from the leader entity's position and facing direction.
     */
    struct FormationInstance
    {
        uint32_t id = 0;                          ///< Unique formation identifier
        FormationType type = FormationType::Line; ///< Shape of this formation
        uint32_t leaderEntity = 0;                ///< Entity driving position and heading
        XMFLOAT3 center{0.0f, 0.0f, 0.0f};        ///< World-space center (from leader)
        float heading = 0.0f;                     ///< Facing direction in radians
        std::vector<FormationSlot> slots;         ///< Active slots with assignments
    };

    // =========================================================================
    // FormationSystem
    // =========================================================================

    /**
     * @class FormationSystem
     * @brief Singleton that manages tactical formations for AI groups.
     *
     * Provides creation, assignment, and per-frame updates for formations.
     * Slot world positions are computed by rotating local offsets by the
     * formation heading and translating by the formation center.
     */
    class FormationSystem
    {
      public:
        /** @brief Get the singleton instance. */
        [[deprecated("Use EngineContext::Get()->GetSystem<FormationSystem>() instead")]]
        static FormationSystem& GetInstance()
        {
            static FormationSystem s;
            return s;
        }

        /** @brief Initialize the system and generate built-in templates. */
        void Initialize();

        /** @brief Clean up all active formations. */
        void Shutdown();

        /**
         * @brief Create a new formation.
         * @param type          Shape of the formation.
         * @param leaderEntity  Entity whose position drives the formation center.
         * @param memberCount   Number of slots (excluding leader).
         * @param spacing       Distance between adjacent slots.
         * @return Unique formation ID, or 0 on failure.
         */
        uint32_t CreateFormation(FormationType type, uint32_t leaderEntity, uint32_t memberCount, float spacing = 3.0f);

        /**
         * @brief Disband and remove a formation.
         * @param formationID ID of the formation to remove.
         */
        void DisbandFormation(uint32_t formationID);

        /**
         * @brief Assign an entity to the next available slot.
         * @param formationID Formation to assign into.
         * @param entityID    Entity to place in a slot.
         * @return Slot index assigned, or -1 if no free slot.
         */
        int AssignToSlot(uint32_t formationID, uint32_t entityID);

        /**
         * @brief Remove an entity from a formation.
         * @param formationID Formation to remove from.
         * @param entityID    Entity to remove.
         */
        void RemoveFromFormation(uint32_t formationID, uint32_t entityID);

        /**
         * @brief Get the world-space position of a formation slot.
         * @param formationID Formation ID.
         * @param slotIndex   Index of the slot.
         * @return World-space position, or {0,0,0} if invalid.
         */
        XMFLOAT3 GetSlotWorldPosition(uint32_t formationID, int slotIndex) const;

        /**
         * @brief Update all formations (recalculate centers from leaders).
         * @param deltaTime Frame time in seconds (reserved for smooth transitions).
         */
        void Update(float deltaTime);

        /**
         * @brief Get a formation by ID.
         * @param formationID Formation ID.
         * @return Pointer to the formation, or nullptr if not found.
         */
        const FormationInstance* GetFormation(uint32_t formationID) const;

        /** @brief Get the number of active formations. */
        size_t GetFormationCount() const { return m_formations.size(); }

      private:
        FormationSystem() = default;

        /** @brief Generate slot offsets for a given type, count, and spacing. */
        std::vector<FormationSlot> GenerateSlots(FormationType type, uint32_t count, float spacing) const;

        std::unordered_map<uint32_t, FormationInstance> m_formations;
        uint32_t m_nextID = 1;
        bool m_initialized = false;
    };

} // namespace Spark::AI
