#!/usr/bin/env python3
"""Render the code-session-ready engine handoff from the readiness contract."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Iterable

from common import REPO_ROOT, SiteDataError, load_contract, write_text


OUTPUT_PATH = REPO_ROOT / "docs" / "readiness" / "ENGINE_READINESS_HANDOFF.md"


def inline(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def bullets(values: Iterable[str], *, empty: str = "None declared.") -> list[str]:
    items = list(values)
    return [f"- {value}" for value in items] if items else [f"- {empty}"]


def numbered(values: Iterable[str], *, empty: str = "None declared.") -> list[str]:
    items = list(values)
    return [f"{index}. {value}" for index, value in enumerate(items, start=1)] if items else [f"1. {empty}"]


def code_block(commands: Iterable[str]) -> list[str]:
    values = list(commands)
    if not values:
        return ["_No command declared._"]
    return ["```bash", *values, "```"]


def render_work_item(item: dict[str, Any]) -> list[str]:
    identifier = item["id"]
    lines = [
        f"### {identifier} — {item['title']}",
        "",
        f"**Priority:** {item['priority']} · **Status:** {item['status']} · "
        f"**Wave:** {item['wave']} · **Area:** {item['area']} · "
        f"**Owner:** {item['owner']} · **Release-blocking:** {'yes' if item['blocking'] else 'no'}",
        "",
        item["rationale"],
        "",
        "**Dependency contract**",
        "",
        f"- Depends on: {', '.join(f'`{value}`' for value in item['dependencies']) or 'nothing'}",
        f"- Safe parallel work: {', '.join(f'`{value}`' for value in item['parallelWith']) or 'none declared'}",
        "",
        "**Source context**",
        "",
        *bullets(f"`{value}`" for value in item["sourceContext"]),
        "",
        "**Entry points**",
        "",
        *bullets(f"`{value}`" for value in item["entryPoints"]),
        "",
        "**Implementation scope**",
        "",
        *bullets(item["implementationScope"]),
        "",
        "**Acceptance criteria**",
        "",
        *numbered(item["acceptanceCriteria"]),
        "",
        "**Required commands**",
        "",
        *code_block(item["commands"]),
        "",
        "**Automated evidence**",
        "",
        f"- Test selectors: {', '.join(f'`{value}`' for value in item['testSelectors']) or 'none declared'}",
        f"- Required CI jobs: {', '.join(f'`{value}`' for value in item['requiredCiJobs']) or 'none declared'}",
        "- Performance / reliability budgets:",
        *[f"  - {value}" for value in item["performanceBudgets"]],
        "",
        "**Same-change updates**",
        "",
        "- Documentation:",
        *[f"  - `{value}`" for value in item["documentationUpdates"]],
        "- Readiness contract:",
        *[f"  - {value}" for value in item["readinessChanges"]],
        "- Website impact:",
        *[f"  - {value}" for value in item["websiteImpact"]],
        "",
        "**Risks and boundaries**",
        "",
        "- Risks:",
        *[f"  - {value}" for value in item["risks"]],
        "- Out of scope:",
        *[f"  - {value}" for value in item["outOfScope"]],
        "",
        "**Definition of done**",
        "",
        *bullets(item["definitionOfDone"]),
        "",
    ]
    return lines


def render_handoff(contract: dict[str, Any]) -> str:
    readiness = contract["readiness"]
    global_release = readiness["globalRelease"]
    work_items = contract["workItems"]
    work_by_id = {item["id"]: item for item in work_items}
    capabilities = readiness["capabilities"]
    gates = readiness["gates"]
    execution = readiness["execution"]
    first_id = execution.get("firstUnblockedWorkItemId")
    first = work_by_id.get(first_id)
    open_blockers = [item for item in work_items if item["blocking"] and item["status"] != "done"]
    gate_counts = {
        state: sum(1 for gate in gates if gate["state"] == state)
        for state in ("passing", "at-risk", "blocked", "not-evaluated")
    }

    lines: list[str] = [
        "<!-- Generated by tools/site-data/render_handoff.py. Edit docs/site/readiness.json or docs/readiness/work-items/*.json, then regenerate. -->",
        "# SparkEngine engine-readiness handoff",
        "",
        "> This is the complete dependency-ordered implementation handoff for taking SparkEngine from its current source-usable state to an evidence-backed release. It is generated from the repository readiness contract and must change in the same commit as implementation, tests, documentation, readiness evidence, and public wording.",
        "",
        "## Current verdict",
        "",
        f"**{global_release['label']} — `{global_release['state']}`.** {global_release['summary']}",
        "",
        f"- Capabilities tracked: **{len(capabilities)}**",
        f"- Blocking release gates: **{sum(1 for gate in gates if gate['blocking'])}**",
        f"- Gate states: **{gate_counts['passing']} passing**, **{gate_counts['at-risk']} at risk**, **{gate_counts['blocked']} blocked**, **{gate_counts['not-evaluated']} not evaluated**",
        f"- Work items: **{len(work_items)} total**, **{len(open_blockers)} unfinished release blockers**",
        f"- First unblocked item: **`{first_id}` — {first['title'] if first else 'none'}**",
        "",
        "### Release means all of the following",
        "",
        *bullets(global_release["definition"]),
        "",
        "### Promotion rules",
        "",
        *numbered(readiness["statusPromotionRules"]),
        "",
        "## Start the next code session here",
        "",
    ]

    if first:
        lines.extend(
            [
                f"Open **`{first['id']}` — {first['title']}**. Its dependencies are satisfied under the current ledger. Do not skip ahead to a dependent item or weaken a gate to manufacture a pass.",
                "",
                "### Session entry points",
                "",
                *bullets(f"`{value}`" for value in first["entryPoints"]),
                "",
                "### Session acceptance",
                "",
                *numbered(first["acceptanceCriteria"]),
                "",
                "### Session verification",
                "",
                *code_block(first["commands"]),
                "",
                "Before ending the session, update the item status/evidence and regenerate this file. If new work is discovered, give it a stable ID, owner, dependencies, acceptance criteria, tests, documentation impact, and public-wording impact.",
                "",
            ]
        )

    for profile in readiness.get("releaseProfiles", []):
        boundaries = profile.get("boundaries") or {}
        lines.extend(
            [
                "## Declared release profile — `" + profile["id"] + "`",
                "",
                f"**{profile['name']} — `{profile['state']}`.** Owner: {profile['owner']}.",
                "",
                profile["summary"],
                "",
                "| Dimension | Declared value | In-profile capabilities | Evidence |",
                "|---|---|---|---|",
            ]
        )
        for dimension in profile.get("scope", []):
            capabilities_cell = ", ".join(f"`{value}`" for value in dimension["capabilityIds"]) or "—"
            evidence_cell = ", ".join(
                f"`{entry['path']}`" + (f" ({entry['job']})" if entry.get("job") else "")
                for entry in dimension.get("evidence", [])
            ) or "—"
            lines.append(
                f"| {inline(dimension['label'])} | {inline(dimension['value'])} | "
                f"{capabilities_cell} | {inline(evidence_cell)} |"
            )
        lines.extend(
            [
                "",
                "### Profile boundaries",
                "",
                "Every capability is classified exactly once. Nothing outside the profile may be presented as supported.",
                "",
                f"- In profile: {', '.join(f'`{value}`' for value in profile['includedCapabilityIds']) or 'none'}",
                f"- Experimental: {', '.join(f'`{value}`' for value in boundaries.get('experimentalCapabilityIds', [])) or 'none'}",
                f"- Unsupported: {', '.join(f'`{value}`' for value in boundaries.get('unsupportedCapabilityIds', [])) or 'none'}",
                "",
                "### Profile gates",
                "",
                f"- Required: {', '.join(f'`{value}`' for value in profile['requiredGateIds']) or 'none'}",
                "- Explicitly excluded:",
                *[
                    f"  - `{entry['gateId']}` — {entry['reason']}"
                    for entry in profile.get("excludedGates", [])
                ],
                "",
                f"- Blocking work: {', '.join(f'`{value}`' for value in profile['blockingWorkItemIds']) or 'none'}",
                "",
                "### Profile limitations",
                "",
                *bullets(profile.get("limitations", [])),
                "",
                f"- Public surfaces this profile owns: "
                f"{', '.join(f'`{value}`' for value in profile.get('publicClaimSurfaces', [])) or 'none declared'}",
                "",
            ]
        )

    lines.extend(
        [
            "## Release-gate ledger",
            "",
            "| Gate | Area | State | Blocking | What must become true | Blocking work |",
            "|---|---|---|:---:|---|---|",
        ]
    )
    for gate in gates:
        criteria = "; ".join(gate["acceptanceCriteria"])
        blockers = ", ".join(f"`{value}`" for value in gate["blockingWorkItemIds"]) or "—"
        lines.append(
            f"| `{gate['id']}` {inline(gate['name'])} | {inline(gate['area'])} | **{inline(gate['state'])}** | "
            f"{'yes' if gate['blocking'] else 'no'} | {inline(criteria)} | {blockers} |"
        )

    lines.extend(
        [
            "",
            "## Capability truth ledger",
            "",
            "Implementation, verification, support, and release are intentionally separate. The weakest relevant dimension controls public framing.",
            "",
            "| Capability | Owner | Implementation | Verification | Support | Release | Required gates | Open work |",
            "|---|---|---|---|---|---|---|---|",
        ]
    )
    for capability in capabilities:
        lines.append(
            f"| `{capability['id']}` {inline(capability['name'])} | {inline(capability['owner'])} | "
            f"{capability['implementation']} | {capability['verification']} | {capability['support']} | "
            f"**{capability['release']}** | {', '.join(f'`{value}`' for value in capability['requiredGateIds']) or '—'} | "
            f"{', '.join(f'`{value}`' for value in capability['blockingWorkItemIds']) or '—'} |"
        )

    lines.extend(["", "## Dependency-ordered execution", "", *numbered(execution["rules"]), ""])
    for wave in execution["waves"]:
        wave_items = [work_by_id[identifier] for identifier in wave["workItemIds"]]
        lines.extend(
            [
                f"### Wave {wave['id']} — {wave['name']}",
                "",
                wave["objective"],
                "",
                "| Work item | Priority | Status | Depends on | Safe parallel work |",
                "|---|---|---|---|---|",
            ]
        )
        for item in wave_items:
            dependencies = ", ".join(f"`{value}`" for value in item["dependencies"]) or "—"
            parallel = ", ".join(f"`{value}`" for value in item["parallelWith"]) or "—"
            lines.append(
                f"| [`{item['id']}`](#{item['id'].lower()}--{item['title'].lower().replace(' ', '-').replace(',', '')}) "
                f"{inline(item['title'])} | {item['priority']} | **{item['status']}** | {dependencies} | {parallel} |"
            )
        lines.append("")

    parity = contract.get("parityDimensions")
    if parity:
        dimensions = parity["dimensions"]
        lines.extend(
            [
                "## Game-module parity baseline",
                "",
                "Scores are evidence pointers, not percentages: `0` absent/dead, `1` data-model/mock/debug/in-memory prototype, `2` genuinely integrated/playable but not release-gated, `3` validated shipping candidate, and `N/A` intentionally excluded and documented.",
                "",
                "| Module | " + " | ".join(dimensions) + " |",
                "|---|" + "|".join(":---:" for _ in dimensions) + "|",
            ]
        )
        for module, scores in parity["currentScores"].items():
            lines.append(f"| `{module}` | " + " | ".join(str(value) for value in scores) + " |")
        lines.append("")

    lines.extend(["## Work-item implementation briefs", ""])
    for wave in execution["waves"]:
        lines.extend([f"## Wave {wave['id']} briefs", ""])
        for identifier in wave["workItemIds"]:
            lines.extend(render_work_item(work_by_id[identifier]))

    lines.extend(
        [
            "## End-of-session handoff rule",
            "",
            "A code session is not complete because a patch exists. It is complete only when production behavior, production-source tests, fail-closed CI evidence, documentation, the readiness contract, this generated handoff, and repository-driven website impact agree at the same commit. Leave the next first-unblocked work item explicit.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the tracked handoff differs")
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = parser.parse_args()
    try:
        rendered = render_handoff(load_contract())
        output = args.output if args.output.is_absolute() else REPO_ROOT / args.output
        if args.check:
            current = output.read_text(encoding="utf-8") if output.exists() else None
            if current != rendered:
                raise SiteDataError(
                    f"{output.relative_to(REPO_ROOT)} is stale; run tools/site-data/render_handoff.py"
                )
            print(f"Handoff is current: {output.relative_to(REPO_ROOT)}")
            return 0
        write_text(output, rendered)
        print(f"Rendered {output.relative_to(REPO_ROOT)}")
        return 0
    except (SiteDataError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
