/**
 * @file Main.cpp
 * @brief TERRAFRONT module — IModule exports and lifecycle (OnLoad boot
 *        order, OnUnload teardown). The per-frame callbacks (OnUpdate /
 *        OnFixedUpdate / OnRender / OnImGui and friends) live in
 *        MainFrame.cpp, split per the repo file-size rule (TFHUDDraw
 *        pattern — same class, feature-owned translation units).
 *
 * FROZEN: implementation agents do NOT edit this file. Each system is booted
 * here in dependency order with the uniform lifecycle; systems talk through
 * TFGameContext and TFEventBus, never through globals.
 */

#include "Core/SparkGameMMOFPS.h"

#include "Data/TFDataTables.h"
#include "World/TFWorldSetup.h"
#include "Net/TFReplication.h"
#include "Net/TFServerSim.h"
#include "Net/TFClientNet.h"
#include "World/TFRegionSystem.h"
#include "World/TFTravelSystem.h" // continents lane: sanctuary/warpgate travel
#include "Game/TFPlayerSystem.h"
#include "Game/TFWeaponSystem.h"
#include "Game/TFDamageSystem.h"
#include "Game/TFVehicleSystem.h"
#include "Game/TFColossusSystem.h"
#include "Game/TFDeployableSystem.h"
#include "Game/TFProgressionSystem.h"
#include "Game/TFDirectiveSystem.h"
#include "Game/TFSquadSystem.h"
#include "Game/TFBotSystem.h"
#include "Game/TFAudioAmbience.h" // audio-polish lane: zone beds + distant combat layer
#include "Game/TFFootsteps.h"     // audio-wave-2 lane (W10): footstep audio
#include "UI/TFHUD.h"
#include "UI/TFLoadoutScreen.h" // loadout-depth wave: owns m_loadoutUI (complete type for dtor)
#include "UI/TFMapScreen.h"
#include "UI/TFSpawnScreen.h"
#include "UI/TFScoreboard.h"

// Outfits lane: PS2-style clans (server-authoritative system + ImGui panel).
#include "Game/TFOutfitSystem.h"
#include "Game/TFAbilitySystem.h" // class-abilities lane (W9)
#include "Game/TFGrenadeSystem.h" // grenades lane (W10)
#include "Game/TFMedalSystem.h"   // medals-scoreboard lane (W10)
#include "World/TFAlertSystem.h"  // alerts lane (W11): continent timed events
#include "Game/TFPingSystem.h"    // ping-system lane (W11)
#include "UI/TFPingUI.h"          // ping-system lane (W11)
#include "UI/TFOutfitPanel.h"

// W5 onboarding (Task 6, additive): persistence + account/character core
// logic and the client login/char-select/enter-world UI. See DESIGN.md
// "W5 — Onboarding".
#include "Persistence/TFDatabase.h"
#include "Persistence/TFShutdownOrder.h"
#include "Account/TFAccountSystem.h"
#include "Account/TFCharacterSystem.h"
#include "UI/TFLoginFlow.h"

// chat-social lane (additive): social core + chat window + social panel.
#include "Game/TFSocialSystem.h"
#include "UI/TFChatWindow.h"
#include "UI/TFSocialPanel.h"

// W8 ui-polish lane: directives panel + vehicle terminal props.
#include "UI/TFDirectivePanel.h"
#include "Game/TFVehicleTerminal.h"

// W10 nameplates lane: over-pawn name/outfit/health plates.
#include "UI/TFNameplates.h"
// W11 squad-v2 lane: squad list HUD + waypoint beacon + request pings.
#include "UI/TFSquadHUD.h"
#include "UI/TFDeathRecap.h"  // death-recap lane (W11)
#include "World/TFDayNight.h" // W12 time-of-day lane: day/night clock + lighting
#include "Game/TFSpectator.h" // W12 spectator-mode lane
#include "UI/TFKeybinds.h"    // grenades lane (W10): ThrowGrenade rebind seam

#include "Utils/SparkConsole.h"
#include "Utils/LogMacros.h"

#include <Spark/ModuleDllMain.h>

SPARK_IMPLEMENT_MODULE(TerrafrontModule)

using namespace Terrafront;

TerrafrontModule::TerrafrontModule() = default;

TerrafrontModule::~TerrafrontModule()
{
    if (m_initialized)
        OnUnload();
}

Spark::ModuleInfo TerrafrontModule::GetModuleInfo() const
{
    Spark::ModuleInfo info{};
    info.name = "TERRAFRONT - Combined-Arms MMOFPS";
    info.version = "0.1.0";
    info.sdkVersion = SPARK_SDK_VERSION;
    info.loadOrder = 1002; // after SparkGame (1000) and SparkGameMMO (1001)
    return info;
}

bool TerrafrontModule::OnLoad(Spark::IEngineContext* context)
{
    if (!context)
        return false;

    m_context = context;
    m_ctx.engine = context;

    SPARK_LOG_INFO(Spark::LogCategory::Game, "Loading TERRAFRONT module");
    auto& console = Spark::SimpleConsole::GetInstance();
    console.LogInfo("[TF] TERRAFRONT loading - Veyra awaits.");

    // ---- construct all systems (order == member declaration order) ----
    m_data = std::make_unique<TFDataTables>();
    m_world = std::make_unique<TFWorldSetup>();
    m_replication = std::make_unique<TFReplication>();
    m_serverSim = std::make_unique<TFServerSim>();
    m_clientNet = std::make_unique<TFClientNet>();
    m_regions = std::make_unique<TFRegionSystem>();
    m_players = std::make_unique<TFPlayerSystem>();
    m_weapons = std::make_unique<TFWeaponSystem>();
    m_damage = std::make_unique<TFDamageSystem>();
    m_vehicles = std::make_unique<TFVehicleSystem>();
    m_colossus = std::make_unique<TFColossusSystem>();
    m_deployables = std::make_unique<TFDeployableSystem>();
    m_progression = std::make_unique<TFProgressionSystem>();
    m_directives = std::make_unique<TFDirectiveSystem>();
    m_squads = std::make_unique<TFSquadSystem>();
    m_bots = std::make_unique<TFBotSystem>();
    m_ambience = std::make_unique<TFAudioAmbience>(); // audio-polish lane
    m_footsteps = std::make_unique<TFFootsteps>();    // audio-wave-2 lane (W10)
    m_hud = std::make_unique<TFHUD>();
    m_map = std::make_unique<TFMapScreen>();
    m_spawnUI = std::make_unique<TFSpawnScreen>();
    m_loadoutUI = std::make_unique<TFLoadoutScreen>(); // loadout-depth wave
    m_scoreboard = std::make_unique<TFScoreboard>();
    m_travel = std::make_unique<TFTravelSystem>();  // continents lane
    m_outfits = std::make_unique<TFOutfitSystem>(); // outfits lane
    m_outfitPanel = std::make_unique<TFOutfitPanel>();
    m_abilities = std::make_unique<TFAbilitySystem>(); // class-abilities lane (W9)
    m_grenades = std::make_unique<TFGrenadeSystem>();  // grenades lane (W10)
    m_medals = std::make_unique<TFMedalSystem>();      // medals-scoreboard lane (W10)
    m_alerts = std::make_unique<TFAlertSystem>();      // alerts lane (W11)
    m_pingSystem = std::make_unique<TFPingSystem>();   // ping-system lane (W11)
    m_pingUI = std::make_unique<TFPingUI>();

    // W5 onboarding (Task 6, additive): db -> account -> characters ->
    // loginFlow, after every system above (DESIGN.md "W5 — Onboarding").
    m_db = std::make_unique<TFDatabase>();
    m_account = std::make_unique<TFAccountSystem>();
    m_characters = std::make_unique<TFCharacterSystem>();
    m_loginFlow = std::make_unique<TFLoginFlow>();

    // chat-social lane (additive): social core before its two UI consumers.
    m_social = std::make_unique<TFSocialSystem>();
    m_chatWindow = std::make_unique<TFChatWindow>();
    m_socialPanel = std::make_unique<TFSocialPanel>();

    // W8 ui-polish lane.
    m_directivePanel = std::make_unique<TFDirectivePanel>();
    m_vehicleTerminals = std::make_unique<TFVehicleTerminal>();

    // W10 nameplates lane.
    m_nameplates = std::make_unique<TFNameplates>();

    // W11 squad-v2 lane.
    m_squadHUD = std::make_unique<TFSquadHUD>();

    // W11 death-recap lane.
    m_deathRecap = std::make_unique<TFDeathRecap>();

    // W12 time-of-day lane.
    m_dayNight = std::make_unique<TFDayNight>();

    // W12 spectator-mode lane.
    m_spectator = std::make_unique<TFSpectator>();

    // ---- publish context pointers before any Initialize ----
    m_ctx.data = m_data.get();
    m_ctx.world = m_world.get();
    m_ctx.replication = m_replication.get();
    m_ctx.serverSim = m_serverSim.get();
    m_ctx.clientNet = m_clientNet.get();
    m_ctx.regions = m_regions.get();
    m_ctx.players = m_players.get();
    m_ctx.weapons = m_weapons.get();
    m_ctx.damage = m_damage.get();
    m_ctx.vehicles = m_vehicles.get();
    m_ctx.colossus = m_colossus.get();
    m_ctx.deployables = m_deployables.get();
    m_ctx.progression = m_progression.get();
    m_ctx.directives = m_directives.get();
    m_ctx.squads = m_squads.get();
    m_ctx.outfits = m_outfits.get();     // outfits lane
    m_ctx.abilities = m_abilities.get(); // class-abilities lane (W9)
    m_ctx.grenades = m_grenades.get();   // grenades lane (W10)
    m_ctx.pings = m_pingSystem.get();    // ping-system lane (W11)
    m_ctx.alerts = m_alerts.get();       // minimap-v2 lane (W13): corner-minimap alert overlay
    m_ctx.hud = m_hud.get();
    m_ctx.map = m_map.get();
    m_ctx.spawnUI = m_spawnUI.get();
    m_ctx.loadoutUI = m_loadoutUI.get(); // loadout-depth wave
    m_ctx.scoreboard = m_scoreboard.get();
    m_ctx.travel = m_travel.get(); // continents lane

    // W5 onboarding (Task 6, additive).
    m_ctx.db = m_db.get();
    m_ctx.account = m_account.get();
    m_ctx.characters = m_characters.get();
    m_ctx.loginFlow = m_loginFlow.get();

    // chat-social lane (additive).
    m_ctx.social = m_social.get();
    m_ctx.chatWindow = m_chatWindow.get();
    m_ctx.socialPanel = m_socialPanel.get();
    m_chatWindow->SetSocial(m_social.get());
    m_socialPanel->SetSocial(m_social.get());

    // Persistence is authority-owned. A pure client must never load a stale
    // snapshot and flush it over the dedicated server's account database at
    // shutdown. TFServerSim opens the database lazily on the first login or
    // registration request; clients keep these interfaces wired only for the
    // shared onboarding types and reply flow.
    m_account->SetDatabase(m_db.get());
    m_characters->SetDatabase(m_db.get());

    // ---- initialize in dependency order ----
    struct Boot
    {
        const char* name;
        bool ok;
    };
    // From this point onward, every failure must run the same reverse-order
    // teardown as a normal unload. Several Initialize methods install console
    // and network callbacks that capture their owning system.
    m_initialized = true;
    const Boot boots[] = {
        {"TFDataTables", m_data->Initialize(m_ctx, m_events)},
        {"TFWorldSetup", m_world->Initialize(m_ctx, m_events)},
        {"TFReplication", m_replication->Initialize(m_ctx, m_events)},
        {"TFServerSim", m_serverSim->Initialize(m_ctx, m_events)},
        {"TFClientNet", m_clientNet->Initialize(m_ctx, m_events)},
        {"TFRegionSystem", m_regions->Initialize(m_ctx, m_events)},
        {"TFPlayerSystem", m_players->Initialize(m_ctx, m_events)},
        {"TFWeaponSystem", m_weapons->Initialize(m_ctx, m_events)},
        {"TFDamageSystem", m_damage->Initialize(m_ctx, m_events)},
        {"TFVehicleSystem", m_vehicles->Initialize(m_ctx, m_events)},
        {"TFColossusSystem", m_colossus->Initialize(m_ctx, m_events)},
        {"TFDeployableSystem", m_deployables->Initialize(m_ctx, m_events)},
        {"TFProgressionSystem", m_progression->Initialize(m_ctx, m_events)},
        // W6 directives: must init AFTER progression (payouts route through it).
        {"TFDirectiveSystem", m_directives->Initialize(m_ctx, m_events)},
        {"TFSquadSystem", m_squads->Initialize(m_ctx, m_events)},
        // Outfits lane: after squads (uses the same session surface).
        {"TFOutfitSystem", m_outfits->Initialize(m_ctx, m_events)},
        // class-abilities lane (W9): after players/damage/deployables, before bots.
        {"TFAbilitySystem", m_abilities->Initialize(m_ctx, m_events)},
        // grenades lane (W10): after players/damage/vehicles/deployables, before bots.
        {"TFGrenadeSystem", m_grenades->Initialize(m_ctx, m_events)},
        // medals-scoreboard lane (W10): after players/squads/progression (reads all
        // three); self-wires to ctx.scoreboard (context pointers already published).
        {"TFMedalSystem", m_medals->Initialize(m_ctx, m_events)},
        // alerts lane (W11): after regions/players/progression (reads all three
        // through ctx); before bots so chaos runs see a live scheduler.
        {"TFAlertSystem", m_alerts->Initialize(m_ctx, m_events)},
        // ping-system lane (W11): squad-scoped tactical pings.
        {"TFPingSystem", m_pingSystem->Initialize(m_ctx, m_events)},
        // W12 time-of-day lane: independent (engine gfx + NetworkManager only).
        {"TFDayNight", m_dayNight->Initialize(m_ctx, m_events)},
        {"TFBotSystem", m_bots->Initialize(m_ctx, m_events)},
        {"TFAudioAmbience", m_ambience->Initialize(m_ctx, m_events)}, // audio-polish: after weapons/data
        {"TFFootsteps", m_footsteps->Initialize(m_ctx, m_events)}, // audio-wave-2 (W10): after players/vehicles/world
        {"TFHUD", m_hud->Initialize(m_ctx, m_events)},
        {"TFMapScreen", m_map->Initialize(m_ctx, m_events)},
        {"TFSpawnScreen", m_spawnUI->Initialize(m_ctx, m_events)},
        {"TFLoadoutScreen", m_loadoutUI->Initialize(m_ctx, m_events)}, // loadout-depth wave
        {"TFScoreboard", m_scoreboard->Initialize(m_ctx, m_events)},
        // continents lane: must run AFTER world/serverSim/regions/players.
        {"TFTravelSystem", m_travel->Initialize(m_ctx, m_events)},
        // W5 onboarding (Task 6, additive).
        {"TFLoginFlow", m_loginFlow->Initialize(m_ctx, m_events)},
        // chat-social lane: social core before its two UI consumers.
        {"TFSocialSystem", m_social->Initialize(m_ctx, m_events)},
        {"TFChatWindow", m_chatWindow->Initialize(m_ctx, m_events)},
        {"TFSocialPanel", m_socialPanel->Initialize(m_ctx, m_events)},
        // Outfits lane: panel takes the system by reference (3-arg Initialize)
        // so it does not depend on ctx.outfits publish order.
        {"TFOutfitPanel", m_outfitPanel->Initialize(m_ctx, m_events, *m_outfits)},
        // W8 ui-polish lane: after directives/clientNet/regions (read-only consumers).
        {"TFDirectivePanel", m_directivePanel->Initialize(m_ctx, m_events)},
        {"TFVehicleTerminal", m_vehicleTerminals->Initialize(m_ctx, m_events)},
        // W10 nameplates lane: pure consumer of replicated state — booted last.
        {"TFNameplates", m_nameplates->Initialize(m_ctx, m_events)},
        // W11 squad-v2 lane: pure consumer of squad/pawn mirrors — booted last.
        {"TFSquadHUD", m_squadHUD->Initialize(m_ctx, m_events)},
        // W11 death-recap lane: pure consumer — self-wires the ctx.damage
        // mirror + its own socket handler; booted last.
        {"TFDeathRecap", m_deathRecap->Initialize(m_ctx, m_events)},
        // W11 ping-system lane: UI layer takes the system by reference (3-arg
        // Initialize, TFOutfitPanel precedent) — booted last.
        {"TFPingUI", m_pingUI->Initialize(m_ctx, m_events, *m_pingSystem)},
        // W12 spectator-mode lane: client-only dead-time camera, pure consumer — booted last.
        {"TFSpectator", m_spectator->Initialize(m_ctx, m_events)},
    };
    for (const Boot& b : boots)
    {
        if (!b.ok)
        {
            console.LogError(std::string("[TF] Failed to initialize ") + b.name);
            OnUnload();
            return false;
        }
    }

    // Killcam lane (W13): direct pointer hookup between the two sibling
    // lanes (neither TFDeathRecap nor TFSpectator lives on TFGameContext).
    // Both Initialize()'d above; wires TFDeathRecap's push notify to
    // TFSpectator's killer-follow gate.
    m_spectator->SetDeathRecapSource(*m_deathRecap);

    // grenades lane (W10): route the throw key through the TFKeybinds table
    // (defaults to 'G' either way; this makes runtime rebinds take effect).
    m_grenades->SetThrowKey(TFKeys::KeyFor(TFKeys::Action::ThrowGrenade));

    RegisterConsoleCommands();

    console.LogInfo("[TF] TERRAFRONT loaded. Factions: Meridian Accord / Aurum Combine / Helix Covenant.");
    console.LogInfo("[TF] Try: tf_status | tf_host | tf_connect <ip>; then complete the login/character flow.");
    return true;
}

bool TerrafrontModule::CanUnload()
{
    if (!m_initialized)
        return true;

    // Persistence is the teardown gate. If any store cannot become durable,
    // leave every system and callback intact so the caller can repair the I/O
    // failure and retry OnUnload() without dangling cross-system references.
    if (!CheckpointPersistenceBeforeTeardown(*m_social, *m_outfits, *m_progression, *m_regions))
    {
        SPARK_LOG_ERROR(Spark::LogCategory::Game,
                        "[TF] unload refused: persistence checkpoint failed; module remains initialized for retry");
        return false;
    }
    return true;
}

void TerrafrontModule::OnUnload()
{
    if (!m_initialized)
        return;

    // ModuleManager has already run CanUnload() for a normal shutdown. Do not
    // repeat a fallible checkpoint after the manager has committed to teardown:
    // a second failure could otherwise make this void callback return early
    // while the manager still marks the module shut down. Failed OnLoad paths
    // also call this directly and have no durable state that needs a gate.

    SPARK_LOG_INFO(Spark::LogCategory::Game, "Unloading TERRAFRONT module");

    // Remove module-level callbacks before tearing down any system they read.
    // SimpleConsole serializes dispatch and unregister with its lifecycle lock.
    UnregisterConsoleCommands();

    // reverse boot order
    // W5 onboarding (Task 6, additive): loginFlow/db were constructed last,
    // so they shut down first. TFAccountSystem/TFCharacterSystem are plain
    // core-logic classes with no Shutdown() of their own.
    // chat-social + outfits lanes (reverse boot order; outfit panel booted last).
    // W8 ui-polish lane (booted last, shut down first).
    // W11 lanes (booted last, shut down first): ping UI, death recap, squad HUD.
    m_spectator->Shutdown();  // W12 spectator-mode lane
    m_pingUI->Shutdown();     // W11 ping-system lane
    m_deathRecap->Shutdown(); // W11 death-recap lane
    m_squadHUD->Shutdown();   // W11 squad-v2 lane
    // W10 nameplates lane (booted last, shut down first).
    m_nameplates->Shutdown();
    m_vehicleTerminals->Shutdown();
    m_directivePanel->Shutdown();

    m_outfitPanel->Shutdown();
    m_socialPanel->Shutdown();
    m_chatWindow->Shutdown();
    m_social->Shutdown();

    m_loginFlow->Shutdown();

    m_travel->Shutdown(); // continents lane
    m_scoreboard->Shutdown();
    m_spawnUI->Shutdown();
    m_loadoutUI->Shutdown(); // loadout-depth wave
    m_map->Shutdown();
    m_hud->Shutdown();
    m_footsteps->Shutdown(); // audio-wave-2 lane (W10)
    m_ambience->Shutdown();  // audio-polish lane
    m_bots->Shutdown();
    m_dayNight->Shutdown();   // W12 time-of-day lane: unregisters tf_time + wire handler
    m_pingSystem->Shutdown(); // ping-system lane (W11)
    m_alerts->Shutdown();     // alerts lane (W11): unregisters tf_alert + wire handler
    m_medals->Shutdown();     // medals-scoreboard lane (W10): unhooks the scoreboard pointer
    m_grenades->Shutdown();   // grenades lane (W10)
    m_abilities->Shutdown();  // class-abilities lane (W9): restores ghosted meshes + uninstalls the damage filter
    m_outfits->Shutdown();
    m_squads->Shutdown();
    m_directives->Shutdown(); // W6: before progression (reverse of init order)
    FlushProgressionThenCloseDatabase(*m_progression, *m_db);
    m_deployables->Shutdown();
    m_colossus->Shutdown();
    m_vehicles->Shutdown();
    m_damage->Shutdown();
    m_weapons->Shutdown();
    m_players->Shutdown();
    m_regions->Shutdown();
    m_clientNet->Shutdown();
    m_serverSim->Shutdown();
    m_replication->Shutdown();
    m_world->Shutdown();
    m_data->Shutdown();

    m_events.Clear();
    m_initialized = false;
}
