/**
 * @file Main.cpp
 * @brief TERRAFRONT module — IModule implementation and exports.
 *
 * FROZEN: implementation agents do NOT edit this file. Each system is booted
 * here in dependency order with the uniform lifecycle; systems talk through
 * TFGameContext and TFEventBus, never through globals.
 */

#include "Core/SparkGameMMOFPS.h"

#include "Data/TFDataTables.h"
#include "World/TFWorldSetup.h"
#include "Net/TFReplication.h"
#include "Net/TFServerSim.h"
#include "Net/TFClientNet.h"
#include "World/TFRegionSystem.h"
#include "Game/TFPlayerSystem.h"
#include "Game/TFWeaponSystem.h"
#include "Game/TFDamageSystem.h"
#include "Game/TFVehicleSystem.h"
#include "Game/TFColossusSystem.h"
#include "Game/TFDeployableSystem.h"
#include "Game/TFProgressionSystem.h"
#include "Game/TFSquadSystem.h"
#include "Game/TFBotSystem.h"
#include "UI/TFHUD.h"
#include "UI/TFMapScreen.h"
#include "UI/TFSpawnScreen.h"
#include "UI/TFScoreboard.h"

#include "Utils/SparkConsole.h"
#include "Utils/LogMacros.h"

#include <Spark/ModuleDllMain.h>

SPARK_IMPLEMENT_MODULE(TerrafrontModule)

using namespace Terrafront;

TerrafrontModule::TerrafrontModule() = default;

TerrafrontModule::~TerrafrontModule()
{
    if (m_initialized)
        OnUnload();
}

Spark::ModuleInfo TerrafrontModule::GetModuleInfo() const
{
    Spark::ModuleInfo info{};
    info.name = "TERRAFRONT - Combined-Arms MMOFPS";
    info.version = "0.1.0";
    info.sdkVersion = SPARK_SDK_VERSION;
    info.loadOrder = 1002; // after SparkGame (1000) and SparkGameMMO (1001)
    return info;
}

bool TerrafrontModule::OnLoad(Spark::IEngineContext* context)
{
    if (!context)
        return false;

    m_context = context;
    m_ctx.engine = context;

    SPARK_LOG_INFO(Spark::LogCategory::Game, "Loading TERRAFRONT module");
    auto& console = Spark::SimpleConsole::GetInstance();
    console.LogInfo("[TF] TERRAFRONT loading - Veyra awaits.");

    // ---- construct all systems (order == member declaration order) ----
    m_data        = std::make_unique<TFDataTables>();
    m_world       = std::make_unique<TFWorldSetup>();
    m_replication = std::make_unique<TFReplication>();
    m_serverSim   = std::make_unique<TFServerSim>();
    m_clientNet   = std::make_unique<TFClientNet>();
    m_regions     = std::make_unique<TFRegionSystem>();
    m_players     = std::make_unique<TFPlayerSystem>();
    m_weapons     = std::make_unique<TFWeaponSystem>();
    m_damage      = std::make_unique<TFDamageSystem>();
    m_vehicles    = std::make_unique<TFVehicleSystem>();
    m_colossus    = std::make_unique<TFColossusSystem>();
    m_deployables = std::make_unique<TFDeployableSystem>();
    m_progression = std::make_unique<TFProgressionSystem>();
    m_squads      = std::make_unique<TFSquadSystem>();
    m_bots        = std::make_unique<TFBotSystem>();
    m_hud         = std::make_unique<TFHUD>();
    m_map         = std::make_unique<TFMapScreen>();
    m_spawnUI     = std::make_unique<TFSpawnScreen>();
    m_scoreboard  = std::make_unique<TFScoreboard>();

    // ---- publish context pointers before any Initialize ----
    m_ctx.data        = m_data.get();
    m_ctx.world       = m_world.get();
    m_ctx.replication = m_replication.get();
    m_ctx.serverSim   = m_serverSim.get();
    m_ctx.clientNet   = m_clientNet.get();
    m_ctx.regions     = m_regions.get();
    m_ctx.players     = m_players.get();
    m_ctx.weapons     = m_weapons.get();
    m_ctx.damage      = m_damage.get();
    m_ctx.vehicles    = m_vehicles.get();
    m_ctx.colossus    = m_colossus.get();
    m_ctx.deployables = m_deployables.get();
    m_ctx.progression = m_progression.get();
    m_ctx.squads      = m_squads.get();
    m_ctx.hud         = m_hud.get();
    m_ctx.map         = m_map.get();
    m_ctx.spawnUI     = m_spawnUI.get();
    m_ctx.scoreboard  = m_scoreboard.get();

    // ---- initialize in dependency order ----
    struct Boot { const char* name; bool ok; };
    const Boot boots[] = {
        { "TFDataTables",        m_data->Initialize(m_ctx, m_events) },
        { "TFWorldSetup",        m_world->Initialize(m_ctx, m_events) },
        { "TFReplication",       m_replication->Initialize(m_ctx, m_events) },
        { "TFServerSim",         m_serverSim->Initialize(m_ctx, m_events) },
        { "TFClientNet",         m_clientNet->Initialize(m_ctx, m_events) },
        { "TFRegionSystem",      m_regions->Initialize(m_ctx, m_events) },
        { "TFPlayerSystem",      m_players->Initialize(m_ctx, m_events) },
        { "TFWeaponSystem",      m_weapons->Initialize(m_ctx, m_events) },
        { "TFDamageSystem",      m_damage->Initialize(m_ctx, m_events) },
        { "TFVehicleSystem",     m_vehicles->Initialize(m_ctx, m_events) },
        { "TFColossusSystem",    m_colossus->Initialize(m_ctx, m_events) },
        { "TFDeployableSystem",  m_deployables->Initialize(m_ctx, m_events) },
        { "TFProgressionSystem", m_progression->Initialize(m_ctx, m_events) },
        { "TFSquadSystem",       m_squads->Initialize(m_ctx, m_events) },
        { "TFBotSystem",         m_bots->Initialize(m_ctx, m_events) },
        { "TFHUD",               m_hud->Initialize(m_ctx, m_events) },
        { "TFMapScreen",         m_map->Initialize(m_ctx, m_events) },
        { "TFSpawnScreen",       m_spawnUI->Initialize(m_ctx, m_events) },
        { "TFScoreboard",        m_scoreboard->Initialize(m_ctx, m_events) },
    };
    for (const Boot& b : boots)
    {
        if (!b.ok)
        {
            console.LogError(std::string("[TF] Failed to initialize ") + b.name);
            return false;
        }
    }

    RegisterConsoleCommands();

    console.LogInfo("[TF] TERRAFRONT loaded. Factions: Meridian Accord / Aurum Combine / Helix Covenant.");
    console.LogInfo("[TF] Try: tf_status | tf_host | tf_connect <ip> | tf_faction <mra|auc|hlx>");
    m_initialized = true;
    return true;
}

void TerrafrontModule::OnUnload()
{
    if (!m_initialized)
        return;

    SPARK_LOG_INFO(Spark::LogCategory::Game, "Unloading TERRAFRONT module");

    // reverse boot order
    m_scoreboard->Shutdown();
    m_spawnUI->Shutdown();
    m_map->Shutdown();
    m_hud->Shutdown();
    m_bots->Shutdown();
    m_squads->Shutdown();
    m_progression->Shutdown();
    m_deployables->Shutdown();
    m_colossus->Shutdown();
    m_vehicles->Shutdown();
    m_damage->Shutdown();
    m_weapons->Shutdown();
    m_players->Shutdown();
    m_regions->Shutdown();
    m_clientNet->Shutdown();
    m_serverSim->Shutdown();
    m_replication->Shutdown();
    m_world->Shutdown();
    m_data->Shutdown();

    m_events.Clear();
    m_initialized = false;
}

void TerrafrontModule::OnUpdate(float dt)
{
    if (!m_initialized || m_paused)
        return;

    m_data->Update(dt);
    m_world->Update(dt);
    m_replication->Update(dt);
    m_serverSim->Update(dt);
    m_clientNet->Update(dt);
    m_regions->Update(dt);
    m_players->Update(dt);
    m_weapons->Update(dt);
    m_damage->Update(dt);
    m_vehicles->Update(dt);
    m_colossus->Update(dt);
    m_deployables->Update(dt);
    m_progression->Update(dt);
    m_squads->Update(dt);
    m_bots->Update(dt);
    m_hud->Update(dt);
    m_map->Update(dt);
    m_spawnUI->Update(dt);
    m_scoreboard->Update(dt);
}

void TerrafrontModule::OnFixedUpdate(float fdt)
{
    if (!m_initialized || m_paused)
        return;

    // Authoritative simulation runs on the fixed step.
    m_serverSim->FixedUpdate(fdt);
    m_players->FixedUpdate(fdt);
    m_weapons->FixedUpdate(fdt);
    m_vehicles->FixedUpdate(fdt);
    m_regions->FixedUpdate(fdt);
    m_bots->FixedUpdate(fdt);
    m_replication->FixedUpdate(fdt);
}

void TerrafrontModule::OnRender() {}

void TerrafrontModule::OnResize(int, int) {}

void TerrafrontModule::OnPause()  { m_paused = true; }
void TerrafrontModule::OnResume() { m_paused = false; }

void TerrafrontModule::OnImGui()
{
    if (!m_initialized)
        return;

    if (m_ctx.HasLocalPlayer())
    {
        m_hud->RenderUI();
        m_map->RenderUI();
        m_spawnUI->RenderUI();
        m_scoreboard->RenderUI();
    }

    // Debug panels (toggled inside each system; hidden by default)
    m_data->RenderDebugUI();
    m_world->RenderDebugUI();
    m_replication->RenderDebugUI();
    m_serverSim->RenderDebugUI();
    m_clientNet->RenderDebugUI();
    m_regions->RenderDebugUI();
    m_players->RenderDebugUI();
    m_weapons->RenderDebugUI();
    m_damage->RenderDebugUI();
    m_vehicles->RenderDebugUI();
    m_colossus->RenderDebugUI();
    m_deployables->RenderDebugUI();
    m_progression->RenderDebugUI();
    m_squads->RenderDebugUI();
    m_bots->RenderDebugUI();
}
