/**
 * @file MainFrame.cpp
 * @brief TERRAFRONT module per-frame callbacks: OnUpdate / OnFixedUpdate /
 *        OnRender / OnResize / OnPause / OnResume / OnImGui. Split from
 *        Main.cpp per the repo file-size rule (TFHUDDraw pattern — same
 *        class, feature-owned translation units); Main.cpp keeps the exports
 *        and lifecycle (OnLoad boot order, OnUnload teardown).
 *
 * FROZEN: implementation agents do NOT edit this file. Systems talk through
 * TFGameContext and TFEventBus, never through globals.
 */

#include "Core/SparkGameMMOFPS.h"

#ifdef SPARK_HAS_IMGUI
#include <imgui.h>
#endif

#include "Data/TFDataTables.h"
#include "World/TFWorldSetup.h"
#include "Net/TFReplication.h"
#include "Net/TFServerSim.h"
#include "Net/TFClientNet.h"
#include "World/TFRegionSystem.h"
#include "World/TFTravelSystem.h" // continents lane: sanctuary/warpgate travel
#include "Game/TFPlayerSystem.h"
#include "Game/TFWeaponSystem.h"
#include "Game/TFDamageSystem.h"
#include "Game/TFVehicleSystem.h"
#include "Game/TFColossusSystem.h"
#include "Game/TFDeployableSystem.h"
#include "Game/TFProgressionSystem.h"
#include "Game/TFDirectiveSystem.h"
#include "Game/TFSquadSystem.h"
#include "Game/TFBotSystem.h"
#include "Game/TFAudioAmbience.h" // audio-polish lane: zone beds + distant combat layer
#include "Game/TFFootsteps.h"     // audio-wave-2 lane (W10): footstep audio
#include "UI/TFHUD.h"
#include "UI/TFLoadoutScreen.h" // loadout-depth wave: owns m_loadoutUI (complete type for dtor)
#include "UI/TFMapScreen.h"
#include "UI/TFSpawnScreen.h"
#include "UI/TFScoreboard.h"

// Outfits lane: PS2-style clans (server-authoritative system + ImGui panel).
#include "Game/TFOutfitSystem.h"
#include "Game/TFAbilitySystem.h" // class-abilities lane (W9)
#include "Game/TFGrenadeSystem.h" // grenades lane (W10)
#include "Game/TFMedalSystem.h"   // medals-scoreboard lane (W10)
#include "World/TFAlertSystem.h"  // alerts lane (W11): continent timed events
#include "Game/TFPingSystem.h"    // ping-system lane (W11)
#include "UI/TFPingUI.h"          // ping-system lane (W11)
#include "UI/TFOutfitPanel.h"

// W5 onboarding (Task 6, additive): client login/char-select/enter-world UI.
#include "UI/TFLoginFlow.h"

// chat-social lane (additive): social core + chat window + social panel.
#include "Game/TFSocialSystem.h"
#include "UI/TFChatWindow.h"
#include "UI/TFSocialPanel.h"

// W8 ui-polish lane: directives panel + vehicle terminal props.
#include "UI/TFDirectivePanel.h"
#include "Game/TFVehicleTerminal.h"

// W10 nameplates lane: over-pawn name/outfit/health plates.
#include "UI/TFNameplates.h"
// W11 squad-v2 lane: squad list HUD + waypoint beacon + request pings.
#include "UI/TFSquadHUD.h"
#include "UI/TFDeathRecap.h"  // death-recap lane (W11)
#include "World/TFDayNight.h" // W12 time-of-day lane: day/night clock + lighting
#include "Game/TFSpectator.h" // W12 spectator-mode lane

void TerrafrontModule::OnUpdate(float dt)
{
    if (!m_initialized || m_paused)
        return;

    m_data->Update(dt);
    m_world->Update(dt);
    m_replication->Update(dt);
    m_serverSim->Update(dt);
    m_clientNet->Update(dt);
    m_regions->Update(dt);
    m_players->Update(dt);
    m_weapons->Update(dt);
    m_damage->Update(dt);
    m_vehicles->Update(dt);
    m_colossus->Update(dt);
    m_deployables->Update(dt);
    m_progression->Update(dt);
    m_directives->Update(dt);
    m_squads->Update(dt);
    m_outfits->Update(dt);    // outfits lane: persistence debounce + sweeps
    m_abilities->Update(dt);  // class-abilities lane (W9): F-key + mirror + veil visuals + late-join burst
    m_grenades->Update(dt);   // grenades lane (W10): G-key + mirror extrapolation + HUD count
    m_medals->Update(dt);     // medals-scoreboard lane (W10): 4 Hz row flush + toasts + mirror handlers
    m_alerts->Update(dt);     // alerts lane (W11): scheduler + scoring + 1 Hz broadcast + mirror
    m_pingSystem->Update(dt); // ping-system lane (W11): expiry sweep + mirror aging + handler lifecycle
    m_dayNight->Update(dt);   // W12 time-of-day lane: clock + 30 s sync + lighting drive
    m_bots->Update(dt);
    m_ambience->Update(dt);  // audio-polish lane
    m_footsteps->Update(dt); // audio-wave-2 lane (W10)
    m_hud->Update(dt);
    m_map->Update(dt);
    m_spawnUI->Update(dt);
    m_loadoutUI->Update(dt); // loadout-depth wave
    m_scoreboard->Update(dt);
    m_travel->Update(dt);    // continents lane
    m_loginFlow->Update(dt); // W5 onboarding (Task 6, additive)
    // chat-social lane + outfits panel.
    m_social->Update(dt);
    m_chatWindow->Update(dt);
    m_socialPanel->Update(dt);
    m_outfitPanel->Update(dt);
    // W8 ui-polish lane (directive net mirror + terminal prop upkeep).
    m_directivePanel->Update(dt);
    m_vehicleTerminals->Update(dt);
    // W10 nameplates lane (damage-reveal tracking).
    m_nameplates->Update(dt);
    m_pingUI->Update(dt); // ping-system lane (W11): Q tap/hold input + receive bleeps
    // W11 squad-v2 lane (beacon pulse clock).
    m_squadHUD->Update(dt);
    // W11 death-recap lane (handler lifecycle + respawn-edge clear).
    m_deathRecap->Update(dt);
    // W12 spectator-mode lane (dead-time camera; must run after m_clientNet->Update).
    m_spectator->Update(dt);
}

void TerrafrontModule::OnFixedUpdate(float fdt)
{
    if (!m_initialized || m_paused)
        return;

    // Authoritative simulation runs on the fixed step.
    m_serverSim->FixedUpdate(fdt);
    m_players->FixedUpdate(fdt);
    m_abilities->FixedUpdate(fdt); // class-abilities lane (W9): authoritative ability tick
    m_grenades->FixedUpdate(fdt);  // grenades lane (W10): authoritative grenade sim + fuse
    m_weapons->FixedUpdate(fdt);
    m_vehicles->FixedUpdate(fdt);
    m_regions->FixedUpdate(fdt);
    m_travel->FixedUpdate(fdt); // continents lane: applies queued sanctuary placements
    m_bots->FixedUpdate(fdt);
    m_replication->FixedUpdate(fdt);
}

void TerrafrontModule::OnRender()
{
    // With a module loaded the module owns the frame (the engine-only path
    // just clears). TFWorldSetup issues the full BeginFrame / scene + ECS
    // draws / EndFrame; keep rendering while paused so the window presents.
    if (m_initialized)
        m_world->RenderWorld();
}

void TerrafrontModule::OnResize(int, int) {}

void TerrafrontModule::OnPause()
{
    m_paused = true;
}
void TerrafrontModule::OnResume()
{
    m_paused = false;
}

void TerrafrontModule::OnImGui()
{
    if (!m_initialized)
        return;

    if (m_ctx.HasLocalPlayer())
    {
        // W5 onboarding (Task 6): TFLoginFlow owns the pre-world menu (login /
        // register / character select / create / entering-world splash) and
        // is a no-op once its internal state reaches InWorld. The rest of the
        // gameplay UI now additionally gates on m_ctx.InWorld() so nothing
        // renders before the player has logged in and entered the world.
        m_loginFlow->RenderUI();
        if (m_ctx.InWorld())
        {
            m_hud->RenderUI();
            m_map->RenderUI();
            m_spawnUI->RenderUI();
            m_loadoutUI->RenderUI(); // loadout-depth wave
            m_scoreboard->RenderUI();
            m_medals->RenderUI(); // medals-scoreboard lane (W10): medal toast overlay
            m_alerts->RenderUI(); // alerts lane (W11): top-center alert banner + end splash
            // chat-social lane.
            m_chatWindow->RenderUI();
            m_socialPanel->RenderUI();
            // Outfits lane: standalone 'tf_outfit' window.
            m_outfitPanel->RenderUI();
            // W8 ui-polish: directives panel (J).
            m_directivePanel->RenderUI();
            // continents lane: terminal prompt + continent-select menu
            // (player-facing; NOT debug-gated).
            m_travel->RenderUI();
            // W10 nameplates lane: over-pawn plates (foreground drawlist).
            m_nameplates->RenderUI();
            m_pingUI->RenderUI(); // ping-system lane (W11): ping wheel + distance labels
            // W11 squad-v2 lane: squad list + waypoint beacon.
            m_squadHUD->RenderUI();
            // W11 death-recap lane: recap panel on the death screen.
            m_deathRecap->RenderUI();
            // W12 spectator-mode lane: 'Spectating' label + LMB/RMB cycle clicks.
            m_spectator->RenderUI();
        }
    }

    // Aggregated debug window (tf_debug panels). Several system panels use a
    // bare ImGui::CollapsingHeader with no window of their own, so without an
    // explicit Begin() they leak into ImGui's implicit "Debug" window every
    // frame. Wrap them in one titled window that only appears when the master
    // toggle is on — the HUD stays unobstructed in normal play.
    if (m_debugPanels)
    {
#ifdef SPARK_HAS_IMGUI
        if (ImGui::Begin("TERRAFRONT Debug"))
        {
#endif
            m_data->RenderDebugUI();
            m_world->RenderDebugUI();
            m_replication->RenderDebugUI();
            m_serverSim->RenderDebugUI();
            m_clientNet->RenderDebugUI();
            m_regions->RenderDebugUI();
            m_travel->RenderDebugUI(); // continents lane
            m_players->RenderDebugUI();
            m_weapons->RenderDebugUI();
            m_damage->RenderDebugUI();
            m_vehicles->RenderDebugUI();
            m_colossus->RenderDebugUI();
            m_deployables->RenderDebugUI();
            m_progression->RenderDebugUI();
            m_directives->RenderDebugUI();
            m_squads->RenderDebugUI();
            m_outfits->RenderDebugUI();    // outfits lane
            m_abilities->RenderDebugUI();  // class-abilities lane (W9)
            m_grenades->RenderDebugUI();   // grenades lane (W10)
            m_medals->RenderDebugUI();     // medals-scoreboard lane (W10)
            m_alerts->RenderDebugUI();     // alerts lane (W11)
            m_pingSystem->RenderDebugUI(); // ping-system lane (W11)
            m_bots->RenderDebugUI();
            m_loginFlow->RenderDebugUI();        // W5 onboarding (Task 6, additive)
            m_social->RenderDebugUI();           // chat-social lane
            m_ambience->RenderDebugUI();         // audio-polish lane
            m_footsteps->RenderDebugUI();        // audio-wave-2 lane (W10)
            m_directivePanel->RenderDebugUI();   // W8 ui-polish lane
            m_vehicleTerminals->RenderDebugUI(); // W8 ui-polish lane
            m_nameplates->RenderDebugUI();       // W10 nameplates lane
            m_pingUI->RenderDebugUI();           // W11 ping-system lane
            m_squadHUD->RenderDebugUI();         // W11 squad-v2 lane
            m_deathRecap->RenderDebugUI();       // W11 death-recap lane
            m_dayNight->RenderDebugUI();         // W12 time-of-day lane
            m_spectator->RenderDebugUI();        // W12 spectator-mode lane
#ifdef SPARK_HAS_IMGUI
        }
        ImGui::End();
#endif
    }
}
