/**
 * @file Main.cpp
 * @brief TERRAFRONT module — IModule implementation and exports.
 *
 * FROZEN: implementation agents do NOT edit this file. Each system is booted
 * here in dependency order with the uniform lifecycle; systems talk through
 * TFGameContext and TFEventBus, never through globals.
 */

#include "Core/SparkGameMMOFPS.h"

#ifdef SPARK_HAS_IMGUI
#include <imgui.h>
#endif

#include "Data/TFDataTables.h"
#include "World/TFWorldSetup.h"
#include "Net/TFReplication.h"
#include "Net/TFServerSim.h"
#include "Net/TFClientNet.h"
#include "World/TFRegionSystem.h"
#include "World/TFTravelSystem.h" // continents lane: sanctuary/warpgate travel
#include "Game/TFPlayerSystem.h"
#include "Game/TFWeaponSystem.h"
#include "Game/TFDamageSystem.h"
#include "Game/TFVehicleSystem.h"
#include "Game/TFColossusSystem.h"
#include "Game/TFDeployableSystem.h"
#include "Game/TFProgressionSystem.h"
#include "Game/TFDirectiveSystem.h"
#include "Game/TFSquadSystem.h"
#include "Game/TFBotSystem.h"
#include "Game/TFAudioAmbience.h" // audio-polish lane: zone beds + distant combat layer
#include "UI/TFHUD.h"
#include "UI/TFMapScreen.h"
#include "UI/TFSpawnScreen.h"
#include "UI/TFScoreboard.h"

// Outfits lane: PS2-style clans (server-authoritative system + ImGui panel).
#include "Game/TFOutfitSystem.h"
#include "UI/TFOutfitPanel.h"

// W5 onboarding (Task 6, additive): persistence + account/character core
// logic and the client login/char-select/enter-world UI. See DESIGN.md
// "W5 — Onboarding".
#include "Persistence/TFDatabase.h"
#include "Account/TFAccountSystem.h"
#include "Account/TFCharacterSystem.h"
#include "UI/TFLoginFlow.h"

// chat-social lane (additive): social core + chat window + social panel.
#include "Game/TFSocialSystem.h"
#include "UI/TFChatWindow.h"
#include "UI/TFSocialPanel.h"

// W8 ui-polish lane: directives panel + vehicle terminal props.
#include "UI/TFDirectivePanel.h"
#include "Game/TFVehicleTerminal.h"

#include "Utils/SparkConsole.h"
#include "Utils/LogMacros.h"

#include <Spark/ModuleDllMain.h>

SPARK_IMPLEMENT_MODULE(TerrafrontModule)

using namespace Terrafront;

TerrafrontModule::TerrafrontModule() = default;

TerrafrontModule::~TerrafrontModule()
{
    if (m_initialized)
        OnUnload();
}

Spark::ModuleInfo TerrafrontModule::GetModuleInfo() const
{
    Spark::ModuleInfo info{};
    info.name = "TERRAFRONT - Combined-Arms MMOFPS";
    info.version = "0.1.0";
    info.sdkVersion = SPARK_SDK_VERSION;
    info.loadOrder = 1002; // after SparkGame (1000) and SparkGameMMO (1001)
    return info;
}

bool TerrafrontModule::OnLoad(Spark::IEngineContext* context)
{
    if (!context)
        return false;

    m_context = context;
    m_ctx.engine = context;

    SPARK_LOG_INFO(Spark::LogCategory::Game, "Loading TERRAFRONT module");
    auto& console = Spark::SimpleConsole::GetInstance();
    console.LogInfo("[TF] TERRAFRONT loading - Veyra awaits.");

    // ---- construct all systems (order == member declaration order) ----
    m_data = std::make_unique<TFDataTables>();
    m_world = std::make_unique<TFWorldSetup>();
    m_replication = std::make_unique<TFReplication>();
    m_serverSim = std::make_unique<TFServerSim>();
    m_clientNet = std::make_unique<TFClientNet>();
    m_regions = std::make_unique<TFRegionSystem>();
    m_players = std::make_unique<TFPlayerSystem>();
    m_weapons = std::make_unique<TFWeaponSystem>();
    m_damage = std::make_unique<TFDamageSystem>();
    m_vehicles = std::make_unique<TFVehicleSystem>();
    m_colossus = std::make_unique<TFColossusSystem>();
    m_deployables = std::make_unique<TFDeployableSystem>();
    m_progression = std::make_unique<TFProgressionSystem>();
    m_directives = std::make_unique<TFDirectiveSystem>();
    m_squads = std::make_unique<TFSquadSystem>();
    m_bots = std::make_unique<TFBotSystem>();
    m_ambience = std::make_unique<TFAudioAmbience>(); // audio-polish lane
    m_hud = std::make_unique<TFHUD>();
    m_map = std::make_unique<TFMapScreen>();
    m_spawnUI = std::make_unique<TFSpawnScreen>();
    m_scoreboard = std::make_unique<TFScoreboard>();
    m_travel = std::make_unique<TFTravelSystem>();  // continents lane
    m_outfits = std::make_unique<TFOutfitSystem>(); // outfits lane
    m_outfitPanel = std::make_unique<TFOutfitPanel>();

    // W5 onboarding (Task 6, additive): db -> account -> characters ->
    // loginFlow, after every system above (DESIGN.md "W5 — Onboarding").
    m_db = std::make_unique<TFDatabase>();
    m_account = std::make_unique<TFAccountSystem>();
    m_characters = std::make_unique<TFCharacterSystem>();
    m_loginFlow = std::make_unique<TFLoginFlow>();

    // chat-social lane (additive): social core before its two UI consumers.
    m_social = std::make_unique<TFSocialSystem>();
    m_chatWindow = std::make_unique<TFChatWindow>();
    m_socialPanel = std::make_unique<TFSocialPanel>();

    // W8 ui-polish lane.
    m_directivePanel = std::make_unique<TFDirectivePanel>();
    m_vehicleTerminals = std::make_unique<TFVehicleTerminal>();

    // ---- publish context pointers before any Initialize ----
    m_ctx.data = m_data.get();
    m_ctx.world = m_world.get();
    m_ctx.replication = m_replication.get();
    m_ctx.serverSim = m_serverSim.get();
    m_ctx.clientNet = m_clientNet.get();
    m_ctx.regions = m_regions.get();
    m_ctx.players = m_players.get();
    m_ctx.weapons = m_weapons.get();
    m_ctx.damage = m_damage.get();
    m_ctx.vehicles = m_vehicles.get();
    m_ctx.colossus = m_colossus.get();
    m_ctx.deployables = m_deployables.get();
    m_ctx.progression = m_progression.get();
    m_ctx.directives = m_directives.get();
    m_ctx.squads = m_squads.get();
    m_ctx.outfits = m_outfits.get(); // outfits lane
    m_ctx.hud = m_hud.get();
    m_ctx.map = m_map.get();
    m_ctx.spawnUI = m_spawnUI.get();
    m_ctx.scoreboard = m_scoreboard.get();
    m_ctx.travel = m_travel.get(); // continents lane

    // W5 onboarding (Task 6, additive).
    m_ctx.db = m_db.get();
    m_ctx.account = m_account.get();
    m_ctx.characters = m_characters.get();
    m_ctx.loginFlow = m_loginFlow.get();

    // chat-social lane (additive).
    m_ctx.social = m_social.get();
    m_ctx.chatWindow = m_chatWindow.get();
    m_ctx.socialPanel = m_socialPanel.get();
    m_chatWindow->SetSocial(m_social.get());
    m_socialPanel->SetSocial(m_social.get());

    // Persistence is authority-owned. A pure client must never load a stale
    // snapshot and flush it over the dedicated server's account database at
    // shutdown. TFServerSim opens the database lazily on the first login or
    // registration request; clients keep these interfaces wired only for the
    // shared onboarding types and reply flow.
    m_account->SetDatabase(m_db.get());
    m_characters->SetDatabase(m_db.get());

    // ---- initialize in dependency order ----
    struct Boot
    {
        const char* name;
        bool ok;
    };
    const Boot boots[] = {
        {"TFDataTables", m_data->Initialize(m_ctx, m_events)},
        {"TFWorldSetup", m_world->Initialize(m_ctx, m_events)},
        {"TFReplication", m_replication->Initialize(m_ctx, m_events)},
        {"TFServerSim", m_serverSim->Initialize(m_ctx, m_events)},
        {"TFClientNet", m_clientNet->Initialize(m_ctx, m_events)},
        {"TFRegionSystem", m_regions->Initialize(m_ctx, m_events)},
        {"TFPlayerSystem", m_players->Initialize(m_ctx, m_events)},
        {"TFWeaponSystem", m_weapons->Initialize(m_ctx, m_events)},
        {"TFDamageSystem", m_damage->Initialize(m_ctx, m_events)},
        {"TFVehicleSystem", m_vehicles->Initialize(m_ctx, m_events)},
        {"TFColossusSystem", m_colossus->Initialize(m_ctx, m_events)},
        {"TFDeployableSystem", m_deployables->Initialize(m_ctx, m_events)},
        {"TFProgressionSystem", m_progression->Initialize(m_ctx, m_events)},
        // W6 directives: must init AFTER progression (payouts route through it).
        {"TFDirectiveSystem", m_directives->Initialize(m_ctx, m_events)},
        {"TFSquadSystem", m_squads->Initialize(m_ctx, m_events)},
        // Outfits lane: after squads (uses the same session surface).
        {"TFOutfitSystem", m_outfits->Initialize(m_ctx, m_events)},
        {"TFBotSystem", m_bots->Initialize(m_ctx, m_events)},
        {"TFAudioAmbience", m_ambience->Initialize(m_ctx, m_events)}, // audio-polish: after weapons/data
        {"TFHUD", m_hud->Initialize(m_ctx, m_events)},
        {"TFMapScreen", m_map->Initialize(m_ctx, m_events)},
        {"TFSpawnScreen", m_spawnUI->Initialize(m_ctx, m_events)},
        {"TFScoreboard", m_scoreboard->Initialize(m_ctx, m_events)},
        // continents lane: must run AFTER world/serverSim/regions/players.
        {"TFTravelSystem", m_travel->Initialize(m_ctx, m_events)},
        // W5 onboarding (Task 6, additive).
        {"TFLoginFlow", m_loginFlow->Initialize(m_ctx, m_events)},
        // chat-social lane: social core before its two UI consumers.
        {"TFSocialSystem", m_social->Initialize(m_ctx, m_events)},
        {"TFChatWindow", m_chatWindow->Initialize(m_ctx, m_events)},
        {"TFSocialPanel", m_socialPanel->Initialize(m_ctx, m_events)},
        // Outfits lane: panel takes the system by reference (3-arg Initialize)
        // so it does not depend on ctx.outfits publish order.
        {"TFOutfitPanel", m_outfitPanel->Initialize(m_ctx, m_events, *m_outfits)},
        // W8 ui-polish lane: after directives/clientNet/regions (read-only consumers).
        {"TFDirectivePanel", m_directivePanel->Initialize(m_ctx, m_events)},
        {"TFVehicleTerminal", m_vehicleTerminals->Initialize(m_ctx, m_events)},
    };
    for (const Boot& b : boots)
    {
        if (!b.ok)
        {
            console.LogError(std::string("[TF] Failed to initialize ") + b.name);
            return false;
        }
    }

    RegisterConsoleCommands();

    console.LogInfo("[TF] TERRAFRONT loaded. Factions: Meridian Accord / Aurum Combine / Helix Covenant.");
    console.LogInfo("[TF] Try: tf_status | tf_host | tf_connect <ip> | tf_faction <mra|auc|hlx>");
    m_initialized = true;
    return true;
}

void TerrafrontModule::OnUnload()
{
    if (!m_initialized)
        return;

    SPARK_LOG_INFO(Spark::LogCategory::Game, "Unloading TERRAFRONT module");

    // reverse boot order
    // W5 onboarding (Task 6, additive): loginFlow/db were constructed last,
    // so they shut down first. TFAccountSystem/TFCharacterSystem are plain
    // core-logic classes with no Shutdown() of their own.
    // chat-social + outfits lanes (reverse boot order; outfit panel booted last).
    // W8 ui-polish lane (booted last, shut down first).
    m_vehicleTerminals->Shutdown();
    m_directivePanel->Shutdown();

    m_outfitPanel->Shutdown();
    m_socialPanel->Shutdown();
    m_chatWindow->Shutdown();
    m_social->Shutdown();

    m_loginFlow->Shutdown();
    m_db->Close();

    m_travel->Shutdown(); // continents lane
    m_scoreboard->Shutdown();
    m_spawnUI->Shutdown();
    m_map->Shutdown();
    m_hud->Shutdown();
    m_ambience->Shutdown(); // audio-polish lane
    m_bots->Shutdown();
    m_outfits->Shutdown(); // outfits lane: flushes Saves/outfits.json
    m_squads->Shutdown();
    m_directives->Shutdown(); // W6: before progression (reverse of init order)
    m_progression->Shutdown();
    m_deployables->Shutdown();
    m_colossus->Shutdown();
    m_vehicles->Shutdown();
    m_damage->Shutdown();
    m_weapons->Shutdown();
    m_players->Shutdown();
    m_regions->Shutdown();
    m_clientNet->Shutdown();
    m_serverSim->Shutdown();
    m_replication->Shutdown();
    m_world->Shutdown();
    m_data->Shutdown();

    m_events.Clear();
    m_initialized = false;
}

void TerrafrontModule::OnUpdate(float dt)
{
    if (!m_initialized || m_paused)
        return;

    m_data->Update(dt);
    m_world->Update(dt);
    m_replication->Update(dt);
    m_serverSim->Update(dt);
    m_clientNet->Update(dt);
    m_regions->Update(dt);
    m_players->Update(dt);
    m_weapons->Update(dt);
    m_damage->Update(dt);
    m_vehicles->Update(dt);
    m_colossus->Update(dt);
    m_deployables->Update(dt);
    m_progression->Update(dt);
    m_directives->Update(dt);
    m_squads->Update(dt);
    m_outfits->Update(dt); // outfits lane: persistence debounce + sweeps
    m_bots->Update(dt);
    m_ambience->Update(dt); // audio-polish lane
    m_hud->Update(dt);
    m_map->Update(dt);
    m_spawnUI->Update(dt);
    m_scoreboard->Update(dt);
    m_travel->Update(dt);    // continents lane
    m_loginFlow->Update(dt); // W5 onboarding (Task 6, additive)
    // chat-social lane + outfits panel.
    m_social->Update(dt);
    m_chatWindow->Update(dt);
    m_socialPanel->Update(dt);
    m_outfitPanel->Update(dt);
    // W8 ui-polish lane (directive net mirror + terminal prop upkeep).
    m_directivePanel->Update(dt);
    m_vehicleTerminals->Update(dt);
}

void TerrafrontModule::OnFixedUpdate(float fdt)
{
    if (!m_initialized || m_paused)
        return;

    // Authoritative simulation runs on the fixed step.
    m_serverSim->FixedUpdate(fdt);
    m_players->FixedUpdate(fdt);
    m_weapons->FixedUpdate(fdt);
    m_vehicles->FixedUpdate(fdt);
    m_regions->FixedUpdate(fdt);
    m_travel->FixedUpdate(fdt); // continents lane: applies queued sanctuary placements
    m_bots->FixedUpdate(fdt);
    m_replication->FixedUpdate(fdt);
}

void TerrafrontModule::OnRender()
{
    // With a module loaded the module owns the frame (the engine-only path
    // just clears). TFWorldSetup issues the full BeginFrame / scene + ECS
    // draws / EndFrame; keep rendering while paused so the window presents.
    if (m_initialized)
        m_world->RenderWorld();
}

void TerrafrontModule::OnResize(int, int) {}

void TerrafrontModule::OnPause()
{
    m_paused = true;
}
void TerrafrontModule::OnResume()
{
    m_paused = false;
}

void TerrafrontModule::OnImGui()
{
    if (!m_initialized)
        return;

    if (m_ctx.HasLocalPlayer())
    {
        // W5 onboarding (Task 6): TFLoginFlow owns the pre-world menu (login /
        // register / character select / create / entering-world splash) and
        // is a no-op once its internal state reaches InWorld. The rest of the
        // gameplay UI now additionally gates on m_ctx.InWorld() so nothing
        // renders before the player has logged in and entered the world.
        m_loginFlow->RenderUI();
        if (m_ctx.InWorld())
        {
            m_hud->RenderUI();
            m_map->RenderUI();
            m_spawnUI->RenderUI();
            m_scoreboard->RenderUI();
            // chat-social lane.
            m_chatWindow->RenderUI();
            m_socialPanel->RenderUI();
            // Outfits lane: standalone 'tf_outfit' window.
            m_outfitPanel->RenderUI();
            // W8 ui-polish: directives panel (J).
            m_directivePanel->RenderUI();
            // continents lane: terminal prompt + continent-select menu
            // (player-facing; NOT debug-gated).
            m_travel->RenderUI();
        }
    }

    // Aggregated debug window (tf_debug panels). Several system panels use a
    // bare ImGui::CollapsingHeader with no window of their own, so without an
    // explicit Begin() they leak into ImGui's implicit "Debug" window every
    // frame. Wrap them in one titled window that only appears when the master
    // toggle is on — the HUD stays unobstructed in normal play.
    if (m_debugPanels)
    {
#ifdef SPARK_HAS_IMGUI
        if (ImGui::Begin("TERRAFRONT Debug"))
        {
#endif
            m_data->RenderDebugUI();
            m_world->RenderDebugUI();
            m_replication->RenderDebugUI();
            m_serverSim->RenderDebugUI();
            m_clientNet->RenderDebugUI();
            m_regions->RenderDebugUI();
            m_travel->RenderDebugUI(); // continents lane
            m_players->RenderDebugUI();
            m_weapons->RenderDebugUI();
            m_damage->RenderDebugUI();
            m_vehicles->RenderDebugUI();
            m_colossus->RenderDebugUI();
            m_deployables->RenderDebugUI();
            m_progression->RenderDebugUI();
            m_directives->RenderDebugUI();
            m_squads->RenderDebugUI();
            m_outfits->RenderDebugUI(); // outfits lane
            m_bots->RenderDebugUI();
            m_loginFlow->RenderDebugUI();        // W5 onboarding (Task 6, additive)
            m_social->RenderDebugUI();           // chat-social lane
            m_ambience->RenderDebugUI();         // audio-polish lane
            m_directivePanel->RenderDebugUI();   // W8 ui-polish lane
            m_vehicleTerminals->RenderDebugUI(); // W8 ui-polish lane
#ifdef SPARK_HAS_IMGUI
        }
        ImGui::End();
#endif
    }
}
