cmake_minimum_required(VERSION 3.25)
project(SparkCooker LANGUAGES CXX)
if(BUILD_TESTS)
    enable_testing()
endif()
if(NOT TARGET SparkAssetPipelineCore)
    add_subdirectory("../SparkAssetPipelineCore" "${CMAKE_CURRENT_BINARY_DIR}/SparkAssetPipelineCore")
endif()
add_executable(SparkCooker src/main.cpp)
find_package(Threads REQUIRED)
target_link_libraries(SparkCooker PRIVATE SparkAssetPipelineCore Threads::Threads)
target_compile_features(SparkCooker PRIVATE cxx_std_23)
set_target_properties(SparkCooker PROPERTIES FOLDER "Tools")
install(TARGETS SparkCooker RUNTIME DESTINATION bin COMPONENT tools)
