#!/usr/bin/env python3
"""Authoritative CMake target evidence, read from the CMake File API.

Why not grep CMakeLists.txt
---------------------------
Searching a `CMakeLists.txt` for ``add_library(<target>`` proves nothing about
the build.  The text may sit inside a ``#`` comment, inside a ``block()`` that
never executes, behind an ``if()`` that is false for every real configuration,
or in a file that the parent never ``add_subdirectory()``s.  Conversely a
target declared through a helper function or a loop variable is invisible to
the regex even though it is perfectly real.  A regex over source text answers
"does this string appear", which is not the question.

The CMake File API answers the actual question.  After a successful configure,
CMake writes a codemodel describing the targets it really created: their names,
their types, the library filename each produces, and the source files that
compose them.  That is generated by the same machinery that drives the build,
so it cannot disagree with it.

Contract
--------
`load_target_index` returns a mapping produced from a real configure.  If no
such index is available the caller must treat target evidence as **absent and
blocking** — this module never invents a permissive default.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import strict_json

CODEMODEL_KIND = "codemodel"
CODEMODEL_VERSION = 2
CLIENT_NAME = "client-spark-module-evidence"

SHARED_LIBRARY_TYPES = frozenset({"SHARED_LIBRARY", "MODULE_LIBRARY"})

INDEX_SCHEMA_VERSION = "module-targets-v1"


class TargetEvidenceUnavailable(RuntimeError):
    """No configure-generated target evidence could be read.

    Raised rather than returning an empty index, so that a missing configure
    can never be mistaken for "no targets were found, therefore nothing is
    wrong".
    """


def write_query(build_dir: Path) -> Path:
    """Write the stateless File API query CMake reads during configure."""
    query_dir = build_dir / ".cmake" / "api" / "v1" / "query" / CLIENT_NAME
    query_dir.mkdir(parents=True, exist_ok=True)
    query_file = query_dir / "query.json"
    query_file.write_text(
        json.dumps({"requests": [{"kind": CODEMODEL_KIND, "version": CODEMODEL_VERSION}]}),
        encoding="utf-8",
    )
    return query_file


def _read_json(path: Path) -> Any:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def _find_codemodel(reply_dir: Path) -> Path:
    """Locate the codemodel reply document produced for our query."""
    if not reply_dir.is_dir():
        raise TargetEvidenceUnavailable(
            f"no CMake File API reply directory at {reply_dir} — the project "
            f"has not been configured with a codemodel query"
        )
    index_files = sorted(reply_dir.glob("index-*.json"))
    if not index_files:
        raise TargetEvidenceUnavailable(
            f"no index-*.json in {reply_dir} — configure did not complete"
        )
    index = _read_json(index_files[-1])
    client = index.get("reply", {}).get(CLIENT_NAME, {})
    query_reply = client.get("query.json", {})
    if "error" in query_reply:
        raise TargetEvidenceUnavailable(
            f"CMake rejected the codemodel query: {query_reply['error']}"
        )
    for response in query_reply.get("responses", []):
        if response.get("kind") == CODEMODEL_KIND:
            if "error" in response:
                raise TargetEvidenceUnavailable(
                    f"codemodel response error: {response['error']}"
                )
            return reply_dir / response["jsonFile"]
    # Fall back to a shared stateful reply if some other client asked for one.
    shared = sorted(reply_dir.glob("codemodel-v2-*.json"))
    if shared:
        return shared[-1]
    raise TargetEvidenceUnavailable(
        f"no codemodel response found in {reply_dir}"
    )


def extract_from_reply(reply_dir: Path) -> dict[str, dict[str, Any]]:
    """Build the target index from a CMake File API reply directory."""
    codemodel_path = _find_codemodel(reply_dir)
    codemodel = _read_json(codemodel_path)

    index: dict[str, dict[str, Any]] = {}
    for configuration in codemodel.get("configurations", []):
        for target_ref in configuration.get("targets", []):
            target_file = reply_dir / target_ref["jsonFile"]
            target = _read_json(target_file)
            name = target.get("name", "")
            if not name:
                continue
            sources = sorted(
                {
                    s["path"].replace("\\", "/")
                    for s in target.get("sources", [])
                    if isinstance(s, dict) and s.get("path")
                }
            )
            artifacts = sorted(
                {
                    a["path"].replace("\\", "/")
                    for a in target.get("artifacts", [])
                    if isinstance(a, dict) and a.get("path")
                }
            )
            entry = index.setdefault(
                name,
                {
                    "name": name,
                    "type": target.get("type", ""),
                    "nameOnDisk": target.get("nameOnDisk", ""),
                    "sourceDirectory": (
                        target.get("paths", {}).get("source", "").replace("\\", "/")
                    ),
                    "sources": [],
                    "artifacts": [],
                    "configurations": [],
                },
            )
            entry["sources"] = sorted(set(entry["sources"]) | set(sources))
            entry["artifacts"] = sorted(set(entry["artifacts"]) | set(artifacts))
            cfg = configuration.get("name", "")
            if cfg and cfg not in entry["configurations"]:
                entry["configurations"].append(cfg)
    if not index:
        raise TargetEvidenceUnavailable(
            f"codemodel at {codemodel_path} declares no targets — a configure "
            f"that produces nothing is not evidence that targets exist"
        )
    return index


def write_index(index: dict[str, dict[str, Any]], out_path: Path, *, commit_sha: str,
                generated_at: str, source: str) -> None:
    """Serialise the extracted index as a portable evidence document."""
    document = {
        "schemaVersion": INDEX_SCHEMA_VERSION,
        "generatedAt": generated_at,
        "commitSHA": commit_sha,
        "source": source,
        "targets": index,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n",
                        encoding="utf-8")


def load_target_index(path: Path) -> dict[str, Any]:
    """Load a previously extracted target-evidence document.

    Raises TargetEvidenceUnavailable rather than degrading to a permissive
    empty result, so an unconfigured tree blocks instead of passing.
    """
    if not path.is_file():
        raise TargetEvidenceUnavailable(
            f"target evidence not found at {path} — run "
            f"tools/module-evidence/collect_targets.py after a CMake configure"
        )
    try:
        document = strict_json.load_file(path)
    except strict_json.StrictJSONError as exc:
        raise TargetEvidenceUnavailable(f"target evidence is unusable: {exc}") from exc
    if not isinstance(document, dict):
        raise TargetEvidenceUnavailable(f"{path}: target evidence must be an object")
    version = document.get("schemaVersion")
    if version != INDEX_SCHEMA_VERSION:
        raise TargetEvidenceUnavailable(
            f"{path}: target evidence schemaVersion must be "
            f"{INDEX_SCHEMA_VERSION!r}, got {version!r}"
        )
    targets = document.get("targets")
    if not isinstance(targets, dict) or not targets:
        raise TargetEvidenceUnavailable(
            f"{path}: target evidence declares no targets"
        )
    return document


def check_target(
    index: dict[str, Any],
    target_name: str,
    module_name: str,
    declared_libraries: dict[str, str],
    label: str,
) -> list[str]:
    """Verify one declared module against configure-generated target evidence."""
    targets = index.get("targets", {})
    target = targets.get(target_name)
    if target is None:
        return [
            f"{label}: CMake target {target_name!r} does not exist in the "
            f"configure-generated codemodel — a name in CMakeLists text is not "
            f"proof that CMake created the target"
        ]

    errors: list[str] = []
    ttype = target.get("type", "")
    if ttype not in SHARED_LIBRARY_TYPES:
        errors.append(
            f"{label}: CMake target {target_name!r} has type {ttype!r}; a game "
            f"module must build one of {sorted(SHARED_LIBRARY_TYPES)}"
        )

    sources = target.get("sources", [])
    if not sources:
        errors.append(
            f"{label}: CMake target {target_name!r} has no source files in the "
            f"codemodel — an empty target produces no module"
        )
    else:
        expected_prefix = f"GameModules/{module_name}/Source/"
        in_module = [s for s in sources if s.startswith(expected_prefix)]
        if not in_module:
            errors.append(
                f"{label}: none of the {len(sources)} source files of target "
                f"{target_name!r} live under {expected_prefix} — the declared "
                f"source tree does not build this target"
            )

    # nameOnDisk is what CMake will actually write — but it is toolchain
    # dependent, not a stable literal.  The same target is libSparkGameFPS.dll
    # under MinGW, SparkGameFPS.dll under MSVC and libSparkGameFPS.so under
    # GCC.  Asserting it equals a hardcoded manifest string would fail on a
    # perfectly correct build, so what is checked here is that CMake's filename
    # really is a decoration of *this* target's name.  Whether the manifest's
    # per-platform names follow the convention is checked in the schema layer,
    # against the target name rather than against one toolchain's output.
    name_on_disk = target.get("nameOnDisk", "")
    if name_on_disk and undecorate_library_name(name_on_disk) != target_name:
        errors.append(
            f"{label}: CMake produces {name_on_disk!r} for target "
            f"{target_name!r} — the configured build does not emit a library "
            f"named after this target"
        )
    return errors


_LIBRARY_SUFFIXES = (".dll", ".so", ".dylib")


def undecorate_library_name(filename: str) -> str:
    """Strip the platform prefix/suffix CMake adds, yielding the target name.

    libSparkGameFPS.so -> SparkGameFPS      (GCC/Clang)
    libSparkGameFPS.dll -> SparkGameFPS     (MinGW)
    SparkGameFPS.dll -> SparkGameFPS        (MSVC)
    """
    stem = filename
    for suffix in _LIBRARY_SUFFIXES:
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    if stem.startswith("lib"):
        stem = stem[3:]
    return stem
