# ASSET-220: real configured CPack install rules, filesystem diff and uninstall.
# This is CMake package evidence, not native MSI/NSIS or N-1 qualification.
cmake_minimum_required(VERSION 3.25)
foreach(_required IN ITEMS SPARK_SOURCE_ROOT SPARK_ENGINE_BUILD_DIR SPARK_TEST_ROOT SPARK_CONFIG)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "${_required} is required")
    endif()
endforeach()
if(NOT EXISTS "${SPARK_ENGINE_BUILD_DIR}/cmake_install.cmake" OR
   NOT EXISTS "${SPARK_ENGINE_BUILD_DIR}/CPackConfig.cmake")
    message(FATAL_ERROR "Repeatability requires a configured CPack/installer tree")
endif()
if(NOT IS_ABSOLUTE "${SPARK_TEST_ROOT}")
    message(FATAL_ERROR "SPARK_TEST_ROOT must be absolute")
endif()
foreach(_bad IN ITEMS ";" "*" "?" "[" "]" "\n" "\r")
    string(FIND "${SPARK_TEST_ROOT}" "${_bad}" _bad_position)
    if(NOT _bad_position EQUAL -1)
        message(FATAL_ERROR "SPARK_TEST_ROOT must not contain delimiters or glob metacharacters")
    endif()
endforeach()
include("${SPARK_SOURCE_ROOT}/cmake/SparkRealPath.cmake")
file(MAKE_DIRECTORY "${SPARK_TEST_ROOT}")
spark_real_path(_test_real "${SPARK_TEST_ROOT}")
cmake_path(SET _test_expected NORMALIZE "${SPARK_TEST_ROOT}")
if(CMAKE_HOST_WIN32)
    string(TOLOWER "${_test_real}" _test_real)
    string(TOLOWER "${_test_expected}" _test_expected)
endif()
if(NOT _test_real STREQUAL _test_expected)
    message(FATAL_ERROR "SPARK_TEST_ROOT must not cross links or junctions")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _nonce)
set(_run "${SPARK_TEST_ROOT}/repeat-${_nonce}")
if(EXISTS "${_run}" OR IS_SYMLINK "${_run}")
    message(FATAL_ERROR "Repeatability run root already exists")
endif()
set(_prefix "${_run}/install")
file(MAKE_DIRECTORY "${_prefix}/UserData")
# Sole declared retained path; compare exact bytes and ancestor directories.
file(WRITE "${_prefix}/UserData/profile.json" "{\"progress\":\"preserve-me\"}\n")

function(_snapshot root output)
    file(GLOB_RECURSE _paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
    list(SORT _paths)
    set(_rows "")
    foreach(_path IN LISTS _paths)
        if(IS_SYMLINK "${root}/${_path}")
            message(FATAL_ERROR "Unexpected link in installed snapshot: ${_path}")
        elseif(IS_DIRECTORY "${root}/${_path}")
            list(APPEND _rows "directory:${_path}")
        else()
            file(SHA256 "${root}/${_path}" _hash)
            list(APPEND _rows "${_hash}:${_path}")
        endif()
    endforeach()
    set(${output} "${_rows}" PARENT_SCOPE)
endfunction()

function(_run_checked description)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE _status OUTPUT_VARIABLE _out ERROR_VARIABLE _err TIMEOUT 180)
    if(NOT "${_status}" STREQUAL "0")
        message(FATAL_ERROR "${description} failed (${_status}):\n${_out}\n${_err}")
    endif()
endfunction()

_snapshot("${_prefix}" _retained)
foreach(_cycle RANGE 1 2)
    _run_checked("Install cycle ${_cycle}" "${CMAKE_COMMAND}" --install "${SPARK_ENGINE_BUILD_DIR}"
        --config "${SPARK_CONFIG}" --prefix "${_prefix}")
    set(_manifest "${SPARK_ENGINE_BUILD_DIR}/install_manifest.txt")
    if(NOT EXISTS "${_manifest}")
        message(FATAL_ERROR "Install produced no manifest")
    endif()
    file(STRINGS "${_manifest}" _installed_files)
    list(LENGTH _installed_files _count)
    if(_count LESS 1)
        message(FATAL_ERROR "Install produced an empty manifest")
    endif()
    file(COPY_FILE "${_manifest}" "${_run}/manifest-${_cycle}.txt")
    _snapshot("${_prefix}" _installed)
    if(_cycle EQUAL 1)
        set(_first_install "${_installed}")
    elseif(NOT _installed STREQUAL _first_install)
        message(FATAL_ERROR "Second install differs from first install")
    endif()
    _run_checked("Idempotent reinstall cycle ${_cycle}" "${CMAKE_COMMAND}" --install "${SPARK_ENGINE_BUILD_DIR}"
        --config "${SPARK_CONFIG}" --prefix "${_prefix}")
    _snapshot("${_prefix}" _reinstalled)
    if(NOT _reinstalled STREQUAL _installed)
        message(FATAL_ERROR "Reinstall changed the installed filesystem")
    endif()
    foreach(_attempt RANGE 1 2)
        _run_checked("Uninstall cycle ${_cycle} attempt ${_attempt}" "${CMAKE_COMMAND}"
            "-DPREFIX=${_prefix}" "-DMANIFEST=${_run}/manifest-${_cycle}.txt"
            -P "${SPARK_SOURCE_ROOT}/cmake/SparkUninstall.cmake")
        _snapshot("${_prefix}" _remaining)
        if(NOT _remaining STREQUAL _retained)
            message(FATAL_ERROR "Uninstall left undeclared paths or changed declared UserData/profile.json")
        endif()
    endforeach()
endforeach()
# Remove only the fresh run root above. Failed runs remain for diagnosis.
file(REMOVE_RECURSE "${_run}")
message(STATUS "Configured package install/uninstall repeated with only declared user data retained")
