#!/bin/bash

# SparkEngine File Tree Generator
# Walks every scanned source directory and writes a hierarchical Markdown
# tree of source files with LOC counts and @brief summaries, plus a
# Mermaid module-level #include dependency graph.
#
# Output:
#   docs/api/FileTree.md
#
# Usage:
#   ./generate-file-tree.sh              # Full regeneration (default)
#   ./generate-file-tree.sh generate
#   ./generate-file-tree.sh check        # Exit 1 if FileTree.md is older than any source file

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
WIKI_DIR="$PROJECT_ROOT/wiki"
OUTPUT_FILE="$WIKI_DIR/reference/File-Tree.md"

# Discover the same source set as generate-api-docs.sh
SOURCE_DIRS=(
    "$PROJECT_ROOT/SparkEngine/Source"
    "$PROJECT_ROOT/SparkEditor/Source"
    "$PROJECT_ROOT/SparkConsole/src"
    "$PROJECT_ROOT/SparkShaderCompiler/src"
    "$PROJECT_ROOT/SparkSDK"
    "$PROJECT_ROOT/Tests"
)
for _gm_src in "$PROJECT_ROOT"/GameModules/*/Source; do
    [ -d "$_gm_src" ] && SOURCE_DIRS+=("$_gm_src")
done
unset _gm_src

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[FILE-TREE]${NC} $1"; }
log_success() { echo -e "${GREEN}[FILE-TREE]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[FILE-TREE]${NC} $1"; }
log_error()   { echo -e "${RED}[FILE-TREE]${NC} $1"; }

generate_tree() {
    mkdir -p "$WIKI_DIR"
    local tmp_files tmp_edges
    tmp_files=$(mktemp)
    tmp_edges=$(mktemp)

    # Collect all source files + per-file metadata.
    for dir in "${SOURCE_DIRS[@]}"; do
        [ -d "$dir" ] || continue
        find "$dir" -type f \( -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \) >> "$tmp_files"
    done
    LC_ALL=C sort -o "$tmp_files" "$tmp_files"

    local total_files total_loc
    total_files=$(wc -l < "$tmp_files")
    total_loc=0

    {
        echo "# File Tree"
        echo ""
        echo "> Every source file scanned by the API documentation pipeline."
        echo ">"
        echo "> Each entry shows line count and — when the file has a top-of-file"
        echo "> \`@brief\` — a one-line summary. Click a path to open the source file."
        echo ""
        echo "Auto-generated by \`docs/generate-file-tree.sh\`."
        echo ""

        # ---- Module #include dependency graph (Mermaid) ----
        echo "## Module Dependency Graph"
        echo ""
        echo "Edges are aggregated from \`#include \"...\"\` directives grouped by top-level module."
        echo ""

        # Build edge set and per-file metadata in a single awk pass (batches all
        # files into one process rather than forking per-file grep/wc/sed).
        local tmp_meta
        tmp_meta=$(mktemp)
        : > "$tmp_edges"
        : > "$tmp_meta"

        # xargs handles arg-length limits; each awk invocation processes a
        # batch of files independently (per-file state keyed by FILENAME).
        xargs -a "$tmp_files" -r awk -v project_root="$PROJECT_ROOT" -v edges_out="$tmp_edges" -v meta_out="$tmp_meta" '
            FNR == 1 {
                loc[FILENAME] = 0; brief[FILENAME] = ""; brief_done[FILENAME] = 0
                rel = FILENAME; sub("^" project_root "/", "", rel)
                relname[FILENAME] = rel
                split(rel, parts, "/")
                if (parts[1] == "GameModules" && parts[3] == "Source") src_module[FILENAME] = parts[2]
                else src_module[FILENAME] = parts[1]
            }
            {
                loc[FILENAME] = FNR
                if (!brief_done[FILENAME] && $0 ~ /@brief/) {
                    b = $0; sub(/.*@brief[[:space:]]+/, "", b); sub(/[[:space:]]*\*\/[[:space:]]*$/, "", b)
                    sub(/^[[:space:]]+/, "", b); sub(/[[:space:]]+$/, "", b)
                    brief[FILENAME] = b; brief_done[FILENAME] = 1
                }
                if ($0 ~ /^[[:space:]]*#[[:space:]]*include[[:space:]]+"/) {
                    inc = $0; sub(/^[[:space:]]*#[[:space:]]*include[[:space:]]+"/, "", inc); sub(/".*$/, "", inc)
                    # Only count cross-module edges: the include must have a slash
                    # (e.g. "Graphics/RHI/RHIDevice.h") — single-file includes are
                    # intra-module and create graph noise.
                    if (index(inc, "/") == 0) next
                    split(inc, ip, "/"); dst = ip[1]
                    if (dst != "" && dst != src_module[FILENAME]) print src_module[FILENAME] "\t" dst >> edges_out
                }
            }
            END { for (f in relname) print relname[f] "\t" loc[f] "\t" brief[f] >> meta_out }
        '

        # Deduplicate edges and emit Mermaid
        LC_ALL=C sort -u "$tmp_edges" -o "$tmp_edges"
        echo '```mermaid'
        echo 'graph LR'
        awk -F'\t' '
            { s=$1; d=$2;
              gsub(/[^A-Za-z0-9]/,"_",s); gsub(/[^A-Za-z0-9]/,"_",d);
              printf("    %s --> %s\n", s, d);
            }
        ' "$tmp_edges" | LC_ALL=C sort -u
        echo '```'
        echo ""

        # ---- Hierarchical file tree ----
        echo "## Hierarchy"
        echo ""

        # Sort metadata by path so files group under their directory
        LC_ALL=C sort "$tmp_meta" -o "$tmp_meta"

        local prev_dir=""
        while IFS=$'\t' read -r rel loc brief; do
            local dirpart="${rel%/*}"
            local filepart="${rel##*/}"
            total_loc=$((total_loc + loc))

            if [ "$dirpart" != "$prev_dir" ]; then
                echo ""
                echo "### \`$dirpart/\`"
                echo ""
                prev_dir="$dirpart"
            fi

            if [ -n "$brief" ]; then
                echo "- [\`$filepart\`](../../$rel) — $loc LOC — $brief"
            else
                echo "- [\`$filepart\`](../../$rel) — $loc LOC"
            fi
        done < "$tmp_meta"

        rm -f "$tmp_meta"

        echo ""
        echo "---"
        echo ""
        echo "## Totals"
        echo ""
        echo "| Metric | Count |"
        echo "|--------|-------|"
        echo "| Source files scanned | $total_files |"
        echo "| Total lines of code  | $total_loc |"
        echo "| Source directories   | ${#SOURCE_DIRS[@]} |"
        echo "| Last generated       | $(date '+%Y-%m-%d %H:%M:%S') |"

    } > "$OUTPUT_FILE"

    rm -f "$tmp_files" "$tmp_edges"
    log_success "Wrote $(basename "$OUTPUT_FILE") ($total_files files, $total_loc LOC)"
}

check_stale() {
    if [ ! -f "$OUTPUT_FILE" ]; then
        log_warning "$OUTPUT_FILE missing"
        exit 1
    fi
    for dir in "${SOURCE_DIRS[@]}"; do
        [ -d "$dir" ] || continue
        if find "$dir" -type f \( -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \) -newer "$OUTPUT_FILE" -print -quit | grep -q .; then
            log_warning "$OUTPUT_FILE is stale (source newer)"
            exit 1
        fi
    done
    log_info "File tree up to date"
    exit 0
}

main() {
    case "${1:-generate}" in
        generate|full|update)
            log_info "Generating file tree..."
            generate_tree
            ;;
        check)
            check_stale
            ;;
        help|-h|--help)
            echo "SparkEngine File Tree Generator"
            echo ""
            echo "Usage: $0 [generate|check|help]"
            echo ""
            echo "  generate  Regenerate docs/api/FileTree.md (default)"
            echo "  check     Exit 1 if FileTree.md is older than any source file"
            echo "  help      Show this message"
            ;;
        *)
            log_error "Unknown command: $1"
            exit 1
            ;;
    esac
}

main "$@"
