#!/bin/bash

# SparkEngine Class Hierarchy Generator
# Parses `class Foo : public Bar` and `struct Foo : public Bar` patterns
# across all scanned headers and emits a Mermaid classDiagram grouped by
# top-level module.
#
# Output:
#   docs/api/ClassHierarchy.md
#
# Usage:
#   ./generate-class-hierarchy.sh              # Full regeneration (default)
#   ./generate-class-hierarchy.sh generate
#   ./generate-class-hierarchy.sh check        # Exit 1 if output is older than any header

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
WIKI_DIR="$PROJECT_ROOT/wiki"
OUTPUT_FILE="$WIKI_DIR/Class-Hierarchy.md"

SOURCE_DIRS=(
    "$PROJECT_ROOT/SparkEngine/Source"
    "$PROJECT_ROOT/SparkEditor/Source"
    "$PROJECT_ROOT/SparkConsole/src"
    "$PROJECT_ROOT/SparkShaderCompiler/src"
    "$PROJECT_ROOT/SparkSDK"
)
for _gm_src in "$PROJECT_ROOT"/GameModules/*/Source; do
    [ -d "$_gm_src" ] && SOURCE_DIRS+=("$_gm_src")
done
unset _gm_src

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[CLASS-HIER]${NC} $1"; }
log_success() { echo -e "${GREEN}[CLASS-HIER]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[CLASS-HIER]${NC} $1"; }
log_error()   { echo -e "${RED}[CLASS-HIER]${NC} $1"; }

generate_hierarchy() {
    mkdir -p "$WIKI_DIR"
    local tmp_edges
    tmp_edges=$(mktemp)

    # Collect inheritance edges: module<TAB>Derived<TAB>Base
    for dir in "${SOURCE_DIRS[@]}"; do
        [ -d "$dir" ] || continue
        grep -rnE '^\s*(class|struct)\s+[A-Z][A-Za-z0-9_]*\s*:\s*public\s+[A-Za-z_][A-Za-z0-9_:]*' \
            --include='*.h' --include='*.hpp' "$dir" 2>/dev/null | \
        while IFS= read -r line; do
            # Parse: <path>:<lineno>:<content>
            local path="${line%%:*}"
            local rest="${line#*:}"
            rest="${rest#*:}"
            local rel="${path#$PROJECT_ROOT/}"
            local module
            module=$(echo "$rel" | cut -d/ -f1)
            local derived base
            derived=$(echo "$rest" | sed -E 's/^\s*(class|struct)\s+([A-Z][A-Za-z0-9_]*).*/\2/')
            base=$(echo "$rest" | grep -oP ':\s*public\s+\K[A-Za-z_][A-Za-z0-9_:]*' | head -1)
            [ -z "$derived" ] && continue
            [ -z "$base" ] && continue
            # Strip namespace qualifiers from base for Mermaid rendering
            base="${base##*::}"
            printf '%s\t%s\t%s\n' "$module" "$derived" "$base"
        done
    done | LC_ALL=C sort -u > "$tmp_edges"

    local total
    total=$(wc -l < "$tmp_edges")

    {
        echo "# Class Hierarchy"
        echo ""
        echo "> Inheritance relationships parsed from \`class Foo : public Bar\` /"
        echo "> \`struct Foo : public Bar\` patterns in all scanned headers."
        echo ">"
        echo "> **Total inheritance edges:** $total. Grouped by top-level module."
        echo ""
        echo "Auto-generated by \`docs/generate-class-hierarchy.sh\`."
        echo ""
        echo "---"
        echo ""

        # Emit one Mermaid block per module. GitHub wiki renders classDiagram natively.
        local current_module=""
        while IFS=$'\t' read -r module derived base; do
            if [ "$module" != "$current_module" ]; then
                if [ -n "$current_module" ]; then
                    echo '```'
                    echo ""
                fi
                current_module="$module"
                echo "## \`$module\`"
                echo ""
                echo '```mermaid'
                echo 'classDiagram'
            fi
            echo "    ${base} <|-- ${derived}"
        done < "$tmp_edges"

        # Close final block if any was opened
        if [ -n "$current_module" ]; then
            echo '```'
            echo ""
        fi

        if [ "$total" -eq 0 ]; then
            echo "_No inheritance relationships detected._"
        fi

    } > "$OUTPUT_FILE"

    rm -f "$tmp_edges"
    log_success "Wrote $(basename "$OUTPUT_FILE") ($total inheritance edges)"
}

check_stale() {
    if [ ! -f "$OUTPUT_FILE" ]; then
        log_warning "$OUTPUT_FILE missing"
        exit 1
    fi
    for dir in "${SOURCE_DIRS[@]}"; do
        [ -d "$dir" ] || continue
        if find "$dir" -type f \( -name '*.h' -o -name '*.hpp' \) -newer "$OUTPUT_FILE" -print -quit | grep -q .; then
            log_warning "$OUTPUT_FILE is stale (headers newer)"
            exit 1
        fi
    done
    log_info "Class hierarchy up to date"
    exit 0
}

main() {
    case "${1:-generate}" in
        generate|full|update)
            log_info "Generating class hierarchy..."
            generate_hierarchy
            ;;
        check)
            check_stale
            ;;
        help|-h|--help)
            echo "SparkEngine Class Hierarchy Generator"
            echo ""
            echo "Usage: $0 [generate|check|help]"
            echo ""
            echo "  generate  Regenerate docs/api/ClassHierarchy.md (default)"
            echo "  check     Exit 1 if output is older than any header"
            echo "  help      Show this message"
            ;;
        *)
            log_error "Unknown command: $1"
            exit 1
            ;;
    esac
}

main "$@"
