#!/bin/bash

# SparkEngine Symbol Index Generator
# Consumes docs/api/.symbols.tsv (produced by generate-api-docs.sh) and emits
# alphabetical Markdown indexes for every kind of symbol in the repo.
#
# Output (all under docs/api/):
#   SymbolIndex.md     — master table of every symbol
#   FunctionIndex.md   — functions + methods
#   ClassIndex.md      — classes + structs
#   EnumIndex.md       — enums
#   MacroIndex.md      — macros + type aliases
#
# Usage:
#   ./generate-symbol-index.sh              # Full regeneration (default)
#   ./generate-symbol-index.sh generate     # Same as above
#   ./generate-symbol-index.sh check        # Exit 1 if any index is missing or older than the TSV

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
API_DIR="$SCRIPT_DIR/api"
WIKI_DIR="${SPARK_SYMBOL_INDEX_OUTPUT_DIR:-$PROJECT_ROOT/wiki}"
SYMBOLS_TSV="$API_DIR/.symbols.tsv"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[SYM-IDX]${NC} $1"; }
log_success() { echo -e "${GREEN}[SYM-IDX]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[SYM-IDX]${NC} $1"; }
log_error()   { echo -e "${RED}[SYM-IDX]${NC} $1"; }

require_tsv() {
    if [ ! -s "$SYMBOLS_TSV" ]; then
        log_error "Symbol TSV not found at $SYMBOLS_TSV"
        log_error "Run docs/generate-api-docs.sh generate first."
        exit 1
    fi
}

# Group prefix (top-level dir from rel_path) — e.g. "SparkEngine/Source/..." → "SparkEngine"
group_of() {
    echo "$1" | cut -d/ -f1
}

# Write one index file filtered on kind regex.
# Args: outfile, title, description, kind_regex
# Source links use "../../<path>#L<line>" so they resolve correctly from
# wiki/reference/*.md (one level deeper than the historical wiki root).
write_filtered_index() {
    local outfile="$1" title="$2" description="$3" kind_regex="$4"
    local tmp
    tmp=$(mktemp)

    # Filter + sort alphabetically by symbol name (case-insensitive, stable).
    awk -F'\t' -v re="$kind_regex" '$1 ~ re { print }' "$SYMBOLS_TSV" | \
        LC_ALL=C sort -f -t$'\t' -k2,2 -k3,3 -k4,4n > "$tmp"

    local total
    total=$(wc -l < "$tmp")

    {
        echo "# $title"
        echo ""
        echo "> $description"
        echo ">"
        echo "> **Total:** $total symbols. Auto-generated by \`docs/generate-symbol-index.sh\`."
        echo ""
        echo "Click any **Source** link to jump to the exact line in the source tree."
        echo ""
        echo "## Alphabetical"
        echo ""
        echo "| Symbol | Kind | Module | Source | Brief |"
        echo "|--------|------|--------|--------|-------|"
        awk -F'\t' '{
            name=$2; kind=$1; path=$3; line=$4; brief=$5;
            n=split(path,p,"/"); module=p[1];
            gsub(/\|/,"\\|",brief);
            printf("| `%s` | %s | %s | [%s:L%s](../../%s#L%s) | %s |\n", name, kind, module, p[n], line, path, line, brief);
        }' "$tmp"
        echo ""
    } > "$outfile"

    rm -f "$tmp"
    log_success "Wrote $(basename "$outfile") ($total symbols)"
}

generate_all() {
    mkdir -p "$WIKI_DIR/reference"
    require_tsv

    write_filtered_index \
        "$WIKI_DIR/reference/Symbol-Index.md" \
        "Symbol Index" \
        "Every class, struct, enum, function, method, macro, and type alias across the entire SparkEngine codebase (including headers, .cpp, and Tests/)." \
        '.'

    write_filtered_index \
        "$WIKI_DIR/reference/Function-Index.md" \
        "Function Index" \
        "Every free function and out-of-line method definition across the codebase." \
        '^(function|method)$'

    write_filtered_index \
        "$WIKI_DIR/reference/Class-Index.md" \
        "Class & Struct Index" \
        "Every declared class and struct across the codebase." \
        '^(class|struct)$'

    write_filtered_index \
        "$WIKI_DIR/reference/Enum-Index.md" \
        "Enum Index" \
        "Every enum declared across the codebase." \
        '^enum$'

    write_filtered_index \
        "$WIKI_DIR/reference/Macro-Index.md" \
        "Macro & Alias Index" \
        "Every #define macro (excluding header guards) plus typedef/using aliases." \
        '^(macro|alias)$'
}

check_stale() {
    require_tsv

    # Timestamps are not reliable evidence here: generate-api-docs.sh check may
    # refresh the ignored .symbols.tsv on a clean checkout even when its content
    # is unchanged. Render into an isolated directory and compare bytes instead
    # so check mode is read-only and deterministic.
    local check_root
    check_root=$(mktemp -d)
    trap 'rm -rf "$check_root"' RETURN
    if ! SPARK_SYMBOL_INDEX_OUTPUT_DIR="$check_root" bash "$0" generate >/dev/null; then
        log_error "Failed to render symbol indexes for comparison"
        return 1
    fi

    for f in Symbol-Index.md Function-Index.md Class-Index.md Enum-Index.md Macro-Index.md; do
        local full="$WIKI_DIR/reference/$f"
        local expected="$check_root/reference/$f"
        if [ ! -f "$full" ]; then
            log_warning "$f missing"
            return 1
        fi
        if ! cmp -s "$expected" "$full"; then
            log_warning "$f content does not match $SYMBOLS_TSV"
            return 1
        fi
    done
    log_info "Symbol indexes up to date"
    return 0
}

main() {
    case "${1:-generate}" in
        generate|full|update)
            log_info "Generating symbol indexes from $SYMBOLS_TSV..."
            generate_all
            ;;
        check)
            check_stale
            ;;
        help|-h|--help)
            echo "SparkEngine Symbol Index Generator"
            echo ""
            echo "Usage: $0 [generate|check|help]"
            echo ""
            echo "  generate  Regenerate all symbol indexes from .symbols.tsv (default)"
            echo "  check     Exit 1 if any index is missing or older than the TSV"
            echo "  help      Show this message"
            ;;
        *)
            log_error "Unknown command: $1"
            exit 1
            ;;
    esac
}

main "$@"
