# Validate retained runtime text without launching an engine.
function(spark_validate_editor_fps_lineage_runtime source_root evidence_root)
# Reuse the exact production lifecycle grammar; importing must never launch a host.
set(SPARK_LIFECYCLE_PARSER_INCLUDE_ONLY TRUE)
include("${source_root}/cmake/RunSparkModuleProfileLifecycle.cmake")
unset(SPARK_LIFECYCLE_PARSER_INCLUDE_ONLY)
foreach(_case IN ITEMS positive malformed missing-asset missing-module)
    foreach(_proof IN ITEMS runtime.log exit-code.txt)
        set(_path "${evidence_root}/${_case}/${_proof}")
        if(NOT EXISTS "${_path}" OR IS_DIRECTORY "${_path}" OR IS_SYMLINK "${_path}")
            message(FATAL_ERROR "Missing complete lineage proof: ${_path}")
        endif()
        file(SIZE "${_path}" _size)
        if(_size GREATER 1048576)
            message(FATAL_ERROR "Lineage proof exceeds 1MiB: ${_path}")
        endif()
    endforeach()
    file(READ "${evidence_root}/${_case}/runtime.log" _log)
    file(READ "${evidence_root}/${_case}/exit-code.txt" _exit)
    string(STRIP "${_exit}" _exit)
    if(_case STREQUAL "positive")
        _spark_validate_lifecycle_result("${_exit}" "${_log}" "" _ok _reason)
        if(NOT _ok)
            message(FATAL_ERROR "Installed actual FPS lifecycle failed: ${_reason}")
        endif()
    elseif(NOT _exit MATCHES "^[1-9][0-9]*$" OR _log MATCHES "SPARK_MODULE_READY")
        message(FATAL_ERROR "Negative ${_case} did not fail before module readiness")
    endif()
endforeach()
endfunction()
