cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED SPARK_TEMPLATE_ROOT OR SPARK_TEMPLATE_ROOT STREQUAL "")
    message(FATAL_ERROR "SPARK_TEMPLATE_ROOT is required")
endif()
if(NOT IS_DIRECTORY "${SPARK_TEMPLATE_ROOT}")
    message(FATAL_ERROR "Template root does not exist: ${SPARK_TEMPLATE_ROOT}")
endif()

function(spark_read_ini path prefix)
    file(STRINGS "${path}" lines ENCODING UTF-8)
    set(current_section "")
    set(current_section_id "")
    set(sections "")
    set(seen_entries "")
    foreach(raw_line IN LISTS lines)
        string(STRIP "${raw_line}" line)
        if(line STREQUAL "" OR line MATCHES "^[#;]")
            continue()
        endif()
        if(line MATCHES "^\\[([^][]+)\\]$")
            set(current_section "${CMAKE_MATCH_1}")
            string(STRIP "${current_section}" current_section)
            string(MAKE_C_IDENTIFIER "${current_section}" current_section_id)
            list(FIND sections "${current_section}" duplicate_section)
            if(current_section STREQUAL "" OR NOT duplicate_section EQUAL -1)
                message(FATAL_ERROR "${path}: invalid or duplicate INI section [${current_section}]")
            endif()
            list(APPEND sections "${current_section}")
            continue()
        endif()
        if(current_section STREQUAL "" OR NOT line MATCHES "^([^=]+)=(.*)$")
            message(FATAL_ERROR "${path}: malformed INI line: ${line}")
        endif()
        set(key "${CMAKE_MATCH_1}")
        set(value "${CMAKE_MATCH_2}")
        string(STRIP "${key}" key)
        string(STRIP "${value}" value)
        string(MAKE_C_IDENTIFIER "${key}" key_id)
        set(entry_id "${current_section_id}_${key_id}")
        list(FIND seen_entries "${entry_id}" duplicate_entry)
        if(key STREQUAL "" OR NOT duplicate_entry EQUAL -1)
            message(FATAL_ERROR "${path}: invalid or duplicate key ${key} in [${current_section}]")
        endif()
        list(APPEND seen_entries "${entry_id}")
        set("${prefix}_${entry_id}" "${value}" PARENT_SCOPE)
    endforeach()
    set("${prefix}_SECTIONS" "${sections}" PARENT_SCOPE)
endfunction()

function(spark_require_equal template_name contract actual expected)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR
            "Template ${template_name} ${contract} must be '${expected}', got '${actual}'")
    endif()
endfunction()

function(spark_require_uint template_name contract value minimum maximum)
    if(NOT value MATCHES "^[0-9]+$" OR value LESS minimum OR value GREATER maximum)
        message(FATAL_ERROR
            "Template ${template_name} ${contract} must be an integer in [${minimum}, ${maximum}], got '${value}'")
    endif()
endfunction()

function(spark_require_relative_path template_name contract value must_exist)
    if(value STREQUAL "")
        message(FATAL_ERROR "Template ${template_name} ${contract} may not be empty")
    endif()
    set(path_value "${value}")
    cmake_path(IS_ABSOLUTE path_value is_absolute)
    cmake_path(NORMAL_PATH path_value OUTPUT_VARIABLE normalized)
    if(is_absolute OR normalized STREQUAL ".." OR normalized MATCHES "^\\.\\./")
        message(FATAL_ERROR
            "Template ${template_name} ${contract} must remain inside the project: '${value}'")
    endif()
    if(must_exist AND NOT EXISTS "${template_dir}/${normalized}")
        message(FATAL_ERROR "Template ${template_name} ${contract} does not exist: ${normalized}")
    endif()
endfunction()

file(GLOB template_candidates LIST_DIRECTORIES true "${SPARK_TEMPLATE_ROOT}/*")
list(SORT template_candidates)
set(validated_template_count 0)

foreach(template_dir IN LISTS template_candidates)
    if(NOT IS_DIRECTORY "${template_dir}" OR NOT EXISTS "${template_dir}/CMakeLists.txt")
        continue()
    endif()

    get_filename_component(template_name "${template_dir}" NAME)
    set(metadata_file "${template_dir}/template.json")
    set(server_file "${template_dir}/Config/server.ini")
    set(gateway_file "${template_dir}/Config/gateway.ini")
    foreach(required_file IN ITEMS "${metadata_file}" "${template_dir}/spark.modules.json" "${server_file}" "${gateway_file}")
        if(NOT EXISTS "${required_file}")
            message(FATAL_ERROR "Template ${template_name} is missing required service file: ${required_file}")
        endif()
    endforeach()

    file(READ "${metadata_file}" metadata)
    string(JSON default_scene ERROR_VARIABLE json_error GET "${metadata}" defaultScene)
    if(NOT json_error STREQUAL "NOTFOUND" OR default_scene STREQUAL "")
        message(FATAL_ERROR "Template ${template_name} has no valid defaultScene in template.json: ${json_error}")
    endif()
    spark_require_relative_path("${template_name}" "defaultScene" "${default_scene}" TRUE)
    set(default_scene_path "${default_scene}")
    cmake_path(NORMAL_PATH default_scene_path OUTPUT_VARIABLE default_scene)

    spark_read_ini("${server_file}" server)
    foreach(required_section IN ITEMS Server Network Game Modules Status GatewayControl)
        list(FIND server_SECTIONS "${required_section}" section_index)
        if(section_index EQUAL -1)
            message(FATAL_ERROR "Template ${template_name} server.ini is missing [${required_section}]")
        endif()
    endforeach()
    spark_require_uint("${template_name}" "server network port" "${server_Network_port}" 1 65535)
    spark_require_uint("${template_name}" "server max_clients" "${server_Network_max_clients}" 1 65535)
    spark_require_uint("${template_name}" "server tick_rate" "${server_Network_tick_rate}" 1 1000)
    spark_require_equal("${template_name}" "server module manifest" "${server_Modules_manifest}" "spark.modules.json")
    spark_require_equal("${template_name}" "server map" "${server_Game_maps}" "${default_scene}")
    spark_require_equal("${template_name}" "server gateway key" "${server_GatewayControl_key_file}" "Config/gateway.key")
    spark_require_relative_path("${template_name}" "server health_file" "${server_Status_health_file}" FALSE)
    spark_require_relative_path("${template_name}" "server epoch_state_file"
                                "${server_GatewayControl_epoch_state_file}" FALSE)
    spark_require_uint("${template_name}" "server status interval_ms" "${server_Status_interval_ms}" 10 600000)
    if(NOT server_GatewayControl_endpoint MATCHES "^spark-area-control-([0-9]+)$")
        message(FATAL_ERROR "Template ${template_name} has an invalid gateway-control endpoint")
    endif()
    set(area_control_port "${CMAKE_MATCH_1}")
    spark_require_uint("${template_name}" "area-control port" "${area_control_port}" 1 65535)

    spark_read_ini("${gateway_file}" gateway)
    foreach(required_section IN ITEMS Gateway Status Security)
        list(FIND gateway_SECTIONS "${required_section}" section_index)
        if(section_index EQUAL -1)
            message(FATAL_ERROR "Template ${template_name} gateway.ini is missing [${required_section}]")
        endif()
    endforeach()
    set(area_sections "")
    foreach(section IN LISTS gateway_SECTIONS)
        if(section MATCHES "^Area\\.[A-Za-z0-9_.-]+$")
            list(APPEND area_sections "${section}")
        endif()
    endforeach()
    list(LENGTH area_sections area_count)
    if(NOT area_count EQUAL 1)
        message(FATAL_ERROR "Template ${template_name} gateway.ini must define exactly one [Area.*] section")
    endif()
    list(GET area_sections 0 area_section)
    string(MAKE_C_IDENTIFIER "${area_section}" area_section_id)
    set(area_prefix "gateway_${area_section_id}")
    foreach(key IN ITEMS host port inter_server_port max_clients tick_rate scene)
        set(variable_name "${area_prefix}_${key}")
        set("area_${key}" "${${variable_name}}")
    endforeach()

    if(area_host STREQUAL "")
        message(FATAL_ERROR "Template ${template_name} gateway area host may not be empty")
    endif()
    spark_require_uint("${template_name}" "gateway port" "${gateway_Gateway_port}" 1 65535)
    spark_require_uint("${template_name}" "gateway inter_server_port" "${gateway_Gateway_inter_server_port}" 1 65535)
    spark_require_uint("${template_name}" "gateway max_total_clients" "${gateway_Gateway_max_total_clients}" 1 65535)
    spark_require_uint("${template_name}" "gateway tick_rate" "${gateway_Gateway_tick_rate}" 1 1000)
    spark_require_uint("${template_name}" "area server port" "${area_port}" 1 65535)
    spark_require_uint("${template_name}" "area inter_server_port" "${area_inter_server_port}" 1 65535)
    spark_require_uint("${template_name}" "area max_clients" "${area_max_clients}" 1 65535)
    spark_require_uint("${template_name}" "area tick_rate" "${area_tick_rate}" 1 1000)
    if(NOT area_port EQUAL server_Network_port)
        message(FATAL_ERROR "Template ${template_name} gateway area port must match server network port")
    endif()
    if(NOT area_inter_server_port EQUAL area_control_port)
        message(FATAL_ERROR "Template ${template_name} gateway area-control port does not match server endpoint")
    endif()
    spark_require_equal("${template_name}" "gateway area scene" "${area_scene}" "${default_scene}")
    spark_require_equal("${template_name}" "gateway key" "${gateway_Security_key_file}" "Config/gateway.key")
    spark_require_relative_path("${template_name}" "gateway health_file" "${gateway_Status_health_file}" FALSE)
    spark_require_relative_path("${template_name}" "gateway stop_file" "${gateway_Status_stop_file}" FALSE)
    spark_require_uint("${template_name}" "gateway status interval_ms" "${gateway_Status_interval_ms}" 10 600000)

    math(EXPR validated_template_count "${validated_template_count} + 1")
endforeach()

if(validated_template_count EQUAL 0)
    message(FATAL_ERROR "No buildable templates found under ${SPARK_TEMPLATE_ROOT}")
endif()

message(STATUS "Template service configuration verification passed for ${validated_template_count} template(s)")
