/**
 * @file GPUParticleSystem.h
 * @brief Compute-shader driven GPU particle system for high-volume effects
 * @author Spark Engine Team
 * @date 2026
 *
 * Provides a fully GPU-driven particle pipeline using D3D11 compute shaders.
 * Particles are emitted, simulated, sorted, and rendered entirely on the GPU
 * via structured buffers, append/consume buffers, indirect dispatch/draw,
 * and bitonic merge sort. Supports depth-buffer collision, multiple force
 * fields, and integrates with the existing ParticleSystem API.
 */

#pragma once
#include "../Core/Platform.h"

#ifdef SPARK_PLATFORM_WINDOWS
#include <d3d11.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <DirectXMath.h>
#endif // SPARK_PLATFORM_WINDOWS

#include <vector>
#include <string>
#include <memory>
#include <unordered_map>
#include <array>
#include <cstdint>
#include <algorithm>
#include <format>

using Microsoft::WRL::ComPtr;

// ============================================================================
// Forward declarations
// ============================================================================

class ParticleSystem;

// ============================================================================
// Constants
// ============================================================================

namespace GPUParticleConstants
{
    constexpr uint32_t DEFAULT_MAX_PARTICLES     = 1048576; // 1M particles
    constexpr uint32_t EMIT_THREAD_GROUP_SIZE    = 256;
    constexpr uint32_t SIMULATE_THREAD_GROUP_SIZE = 256;
    constexpr uint32_t SORT_THREAD_GROUP_SIZE    = 256;
    constexpr uint32_t BILLBOARD_THREAD_GROUP_SIZE = 256;
    constexpr uint32_t BITONIC_BLOCK_SIZE        = 512;
    constexpr uint32_t TRANSPOSE_BLOCK_SIZE      = 16;
    constexpr float    DEFAULT_FIXED_TIMESTEP    = 1.0f / 60.0f;
} // namespace GPUParticleConstants

// ============================================================================
// Enumerations
// ============================================================================

/**
 * @brief Shape used for GPU particle emission
 */
enum class GPUEmitShape : uint32_t
{
    Point  = 0,
    Sphere = 1,
    Cone   = 2,
    Box    = 3
};

/**
 * @brief Sort mode for GPU particles
 */
enum class GPUParticleSortMode : uint32_t
{
    None         = 0, ///< No sorting (cheapest)
    FrontToBack  = 1, ///< Sort nearest-first for opaque-ish effects
    BackToFront  = 2, ///< Sort farthest-first for transparent blending
    ByAge        = 3  ///< Sort by particle age (oldest first)
};

/**
 * @brief Blend mode for GPU particle rendering
 */
enum class GPUParticleBlendMode : uint32_t
{
    Additive      = 0,
    AlphaBlend    = 1,
    Multiply      = 2,
    Premultiplied = 3
};

// ============================================================================
// GPU-side Structures (must match HLSL struct layout)
// ============================================================================

/**
 * @brief GPU particle data stored in the structured buffer
 *
 * This struct is tightly packed to match the HLSL StructuredBuffer layout.
 * Each field aligns to 4 bytes; the total size is 64 bytes per particle.
 */
struct GPUParticle
{
    XMFLOAT3 position;   ///< World-space position
    float    size;        ///< Current billboard size

    XMFLOAT3 velocity;   ///< World-space velocity
    float    life;        ///< Remaining life in seconds

    XMFLOAT4 color;      ///< Current RGBA color

    float    maxLife;     ///< Initial life span
    float    rotation;    ///< Billboard rotation in radians
    float    age;         ///< Normalized age [0..1] = 1 - (life / maxLife)
    uint32_t flags;       ///< Bit flags (alive, collided, etc.)
};
static_assert(sizeof(GPUParticle) == 64, "GPUParticle must be 64 bytes for GPU alignment");

/**
 * @brief Billboard vertex generated by the billboard compute shader
 *
 * Four vertices per particle, expanded from the alive particle list.
 */
struct GPUBillboardVertex
{
    XMFLOAT3 position;   ///< World-space corner position
    XMFLOAT2 texCoord;   ///< UV coordinates
    XMFLOAT4 color;      ///< Per-vertex color with alpha
    float    pad;         ///< Padding to 48 bytes
};

/**
 * @brief Sort key/value pair for GPU bitonic sort
 */
struct GPUSortEntry
{
    float    sortKey;     ///< Distance or age for sorting
    uint32_t index;       ///< Index into alive list
};

/**
 * @brief Color gradient keyframe for GPU emission (matches HLSL cbuffer)
 */
struct GPUColorGradientKey
{
    XMFLOAT4 color;      ///< RGBA color at this keyframe
    float    time;        ///< Normalized time [0..1]
    float    pad[3];      ///< Padding to 32 bytes for cbuffer alignment
};

// ============================================================================
// GPUEmitterSettings
// ============================================================================

/**
 * @brief Complete configuration for a GPU particle emitter
 *
 * Uploaded to a constant buffer each frame for the emit and simulate
 * compute shaders.
 */
struct GPUEmitterSettings
{
    // --- Emission shape ---
    GPUEmitShape emitShape     = GPUEmitShape::Point;
    float shapeRadius          = 1.0f;       ///< Radius for Sphere/Cone
    XMFLOAT3 shapeExtents     = {1, 1, 1};  ///< Half-extents for Box
    float coneAngle            = 45.0f;      ///< Cone angle in degrees

    // --- Emission rate ---
    float emissionRate         = 100.0f;     ///< Particles per second
    uint32_t burstCount        = 0;          ///< One-shot burst particle count
    float burstInterval        = 0.0f;       ///< Time between repeated bursts (0 = one-shot)

    // --- Initial velocity ---
    float velocityMin          = 1.0f;       ///< Minimum initial speed
    float velocityMax          = 5.0f;       ///< Maximum initial speed
    XMFLOAT3 velocityDirection = {0, 1, 0};  ///< Preferred emission direction
    float velocitySpread       = 1.0f;       ///< 0 = focused, 1 = omnidirectional

    // --- Lifetime ---
    float lifeMin              = 1.0f;       ///< Minimum particle lifetime (seconds)
    float lifeMax              = 3.0f;       ///< Maximum particle lifetime (seconds)

    // --- Size ---
    float sizeMin              = 0.05f;      ///< Minimum initial size
    float sizeMax              = 0.2f;       ///< Maximum initial size
    float sizeOverLifeEnd      = 0.0f;       ///< Size multiplier at end of life (0 = shrink to nothing)

    // --- Color gradient (up to 8 keys) ---
    static constexpr uint32_t MAX_COLOR_KEYS = 8;
    std::array<GPUColorGradientKey, MAX_COLOR_KEYS> colorGradient = {{
        {XMFLOAT4{1, 1, 1, 1}, 0.0f, {}},
        {XMFLOAT4{1, 1, 1, 0}, 1.0f, {}},
    }};
    uint32_t colorKeyCount     = 2;

    // --- Physics ---
    float gravityMultiplier    = 1.0f;       ///< Scales world gravity
    XMFLOAT3 gravity           = {0, -9.81f, 0}; ///< Gravity vector
    float drag                 = 0.0f;       ///< Velocity damping coefficient [0..1]

    // --- Noise force ---
    float noiseFrequency       = 1.0f;       ///< Spatial frequency of noise field
    float noiseAmplitude       = 0.0f;       ///< Strength of noise force (0 = disabled)
    float noiseScrollSpeed     = 1.0f;       ///< Rate noise field evolves over time

    // --- Rotation ---
    float rotationMin          = 0.0f;       ///< Min initial rotation (radians)
    float rotationMax          = 6.2831f;    ///< Max initial rotation (radians)
    float rotationSpeedMin     = 0.0f;       ///< Min angular velocity
    float rotationSpeedMax     = 0.0f;       ///< Max angular velocity

    // --- Sorting ---
    GPUParticleSortMode sortMode = GPUParticleSortMode::None;

    // --- Rendering ---
    GPUParticleBlendMode blendMode = GPUParticleBlendMode::Additive;
    std::string texturePath;                 ///< Optional billboard texture

    // --- Depth collision ---
    bool depthCollisionEnabled = false;      ///< Enable depth buffer collision
    float collisionRestitution = 0.3f;       ///< Bounciness on collision [0..1]
    float collisionLifetimeLoss = 0.1f;      ///< Fraction of life lost on each bounce

    // --- Playback ---
    bool loop                  = true;
    bool playOnAwake           = true;
    float duration             = 0.0f;       ///< Total effect duration (0 = infinite when looping)
};

// ============================================================================
// GPU Constant Buffer Structures (match HLSL cbuffer layout)
// ============================================================================

/**
 * @brief Per-frame constant buffer for emit compute shader
 */
struct alignas(16) GPUEmitCB
{
    XMFLOAT4 emitterPosition;               ///< xyz = position, w = pad
    XMFLOAT4 emitterDirection;              ///< xyz = direction, w = spread

    uint32_t emitCount;                      ///< Particles to emit this frame
    uint32_t maxParticles;                   ///< Total pool capacity
    float    deltaTime;                      ///< Frame delta time
    float    totalTime;                      ///< Accumulated time

    // Shape
    uint32_t emitShape;                      ///< GPUEmitShape as uint
    float    shapeRadius;
    float    coneAngle;
    float    pad0;

    XMFLOAT4 shapeExtents;                  ///< xyz = half-extents, w = pad

    // Velocity
    float    velocityMin;
    float    velocityMax;
    float    pad1[2];

    // Life
    float    lifeMin;
    float    lifeMax;

    // Size
    float    sizeMin;
    float    sizeMax;

    // Rotation
    float    rotationMin;
    float    rotationMax;
    float    rotationSpeedMin;
    float    rotationSpeedMax;

    // Color gradient
    GPUColorGradientKey colorKeys[GPUEmitterSettings::MAX_COLOR_KEYS];
    uint32_t colorKeyCount;
    uint32_t randomSeed;                     ///< Per-frame random seed
    float    pad2[2];
};

/**
 * @brief Per-frame constant buffer for simulate compute shader
 */
struct alignas(16) GPUSimulateCB
{
    float    deltaTime;
    float    totalTime;
    uint32_t maxParticles;
    float    drag;

    XMFLOAT4 gravity;                       ///< xyz = gravity, w = multiplier

    // Noise
    float    noiseFrequency;
    float    noiseAmplitude;
    float    noiseScrollSpeed;
    float    sizeOverLifeEnd;

    // Depth collision
    uint32_t depthCollisionEnabled;
    float    collisionRestitution;
    float    collisionLifetimeLoss;
    float    pad0;

    XMFLOAT4X4 inverseView;                 ///< For reconstructing world pos from depth
    XMFLOAT4X4 inverseProjection;
    XMFLOAT4 screenParams;                  ///< x = width, y = height, z = 1/w, w = 1/h
};

/**
 * @brief Per-frame constant buffer for sort compute shader
 */
struct alignas(16) GPUSortCB
{
    uint32_t level;
    uint32_t levelMask;
    uint32_t width;
    uint32_t height;
};

/**
 * @brief Per-frame constant buffer for billboard/render shader
 */
struct alignas(16) GPURenderCB
{
    XMFLOAT4X4 view;
    XMFLOAT4X4 projection;
    XMFLOAT4X4 viewProjection;
    XMFLOAT4   cameraPosition;              ///< xyz = camera pos, w = pad
    XMFLOAT4   cameraUp;                    ///< xyz = camera up, w = pad
    XMFLOAT4   cameraRight;                 ///< xyz = camera right, w = pad
    uint32_t   aliveCount;                   ///< Number of alive particles
    float      pad[3];
};

// ============================================================================
// Indirect Argument Structures
// ============================================================================

/**
 * @brief D3D11 indirect dispatch arguments (matches D3D11_DISPATCH_INDIRECT)
 */
struct GPUDispatchArgs
{
    uint32_t threadGroupCountX;
    uint32_t threadGroupCountY;
    uint32_t threadGroupCountZ;
};

/**
 * @brief D3D11 indirect draw arguments (matches D3D11_DRAW_INSTANCED_INDIRECT)
 */
struct GPUDrawArgs
{
    uint32_t vertexCountPerInstance;
    uint32_t instanceCount;
    uint32_t startVertexLocation;
    uint32_t startInstanceLocation;
};

// ============================================================================
// GPUParticleEmitter
// ============================================================================

/**
 * @brief A single GPU-driven particle emitter
 *
 * Owns all GPU buffers (particle pool, alive/dead lists, indirect args)
 * and dispatches compute shaders for emission, simulation, sorting, and
 * billboard generation. Does NOT own the compute shader objects -- those
 * are shared across all emitters and owned by GPUParticleSystem.
 */
class GPUParticleEmitter
{
public:
    GPUParticleEmitter(const std::string& name, const GPUEmitterSettings& settings);
    ~GPUParticleEmitter();

    // Non-copyable, moveable
    GPUParticleEmitter(const GPUParticleEmitter&) = delete;
    GPUParticleEmitter& operator=(const GPUParticleEmitter&) = delete;
    GPUParticleEmitter(GPUParticleEmitter&&) noexcept = default;
    GPUParticleEmitter& operator=(GPUParticleEmitter&&) noexcept = default;

    /**
     * @brief Initialize all GPU buffers for this emitter
     * @param device D3D11 device
     * @param maxParticles Maximum particle pool capacity
     * @return S_OK on success
     */
    HRESULT Initialize(ID3D11Device* device, uint32_t maxParticles);

    /**
     * @brief Release all GPU resources
     */
    void Shutdown();

    // ---- Compute dispatch (called by GPUParticleSystem) ----

    /**
     * @brief Emit new particles via the emit compute shader
     * @param context Device context
     * @param emitShader Compiled emit compute shader
     * @param deltaTime Frame delta time
     * @param totalTime Accumulated time
     */
    void DispatchEmit(
        ID3D11DeviceContext* context,
        ID3D11ComputeShader* emitShader,
        float deltaTime,
        float totalTime);

    /**
     * @brief Simulate alive particles (physics, forces, death)
     * @param context Device context
     * @param simulateShader Compiled simulate compute shader
     * @param deltaTime Frame delta time
     * @param totalTime Accumulated time
     * @param view Current view matrix (for depth collision)
     * @param projection Current projection matrix
     * @param depthSRV Depth buffer SRV (can be nullptr if no collision)
     * @param screenWidth Viewport width
     * @param screenHeight Viewport height
     */
    void DispatchSimulate(
        ID3D11DeviceContext* context,
        ID3D11ComputeShader* simulateShader,
        float deltaTime,
        float totalTime,
        const XMMATRIX& view,
        const XMMATRIX& projection,
        ID3D11ShaderResourceView* depthSRV,
        uint32_t screenWidth,
        uint32_t screenHeight);

    /**
     * @brief Sort alive particles via GPU bitonic sort
     * @param context Device context
     * @param bitonicSortShader Bitonic sort compute shader
     * @param transposeShader Matrix transpose compute shader
     */
    void DispatchSort(
        ID3D11DeviceContext* context,
        ID3D11ComputeShader* bitonicSortShader,
        ID3D11ComputeShader* transposeShader);

    /**
     * @brief Generate billboard vertices from alive particles
     * @param context Device context
     * @param billboardShader Billboard generation compute shader
     * @param view Current view matrix
     * @param projection Current projection matrix
     * @param cameraPos Camera world position
     */
    void DispatchBillboardGeneration(
        ID3D11DeviceContext* context,
        ID3D11ComputeShader* billboardShader,
        const XMMATRIX& view,
        const XMMATRIX& projection,
        const XMFLOAT3& cameraPos);

    /**
     * @brief Issue an indirect draw call for the generated billboards
     * @param context Device context
     */
    void RenderIndirect(ID3D11DeviceContext* context) const;

    // ---- Playback control ----

    void Play();
    void Stop();
    void Pause();
    void Reset(ID3D11DeviceContext* context);
    void Burst(uint32_t count = 0); ///< 0 = use settings.burstCount

    // ---- Accessors ----

    void SetPosition(const XMFLOAT3& pos) { m_position = pos; }
    void SetRotation(const XMFLOAT3& rot) { m_rotation = rot; }
    const XMFLOAT3& GetPosition() const { return m_position; }
    const XMFLOAT3& GetRotation() const { return m_rotation; }
    const std::string& GetName() const { return m_name; }
    const GPUEmitterSettings& GetSettings() const { return m_settings; }
    GPUEmitterSettings& GetSettings() { return m_settings; }
    bool IsPlaying() const { return m_playing; }
    uint32_t GetMaxParticles() const { return m_maxParticles; }

    /**
     * @brief Read back the alive count from the GPU (stalls pipeline)
     * @param context Device context
     * @return Number of alive particles
     */
    uint32_t ReadAliveCount(ID3D11DeviceContext* context) const;

    // ---- Buffer accessors (for external binding) ----

    ID3D11ShaderResourceView* GetParticleSRV() const { return m_particleSRV.Get(); }
    ID3D11UnorderedAccessView* GetParticleUAV() const { return m_particleUAV.Get(); }
    ID3D11ShaderResourceView* GetBillboardSRV() const { return m_billboardSRV.Get(); }
    ID3D11Buffer* GetBillboardVertexBuffer() const { return m_billboardVertexBuffer.Get(); }
    ID3D11Buffer* GetIndirectDrawBuffer() const { return m_indirectDrawBuffer.Get(); }

private:
    // ---- Helper methods ----

    HRESULT CreateParticleBuffer(ID3D11Device* device);
    HRESULT CreateAliveDeadLists(ID3D11Device* device);
    HRESULT CreateIndirectBuffers(ID3D11Device* device);
    HRESULT CreateBillboardBuffer(ID3D11Device* device);
    HRESULT CreateSortBuffers(ID3D11Device* device);
    HRESULT CreateConstantBuffers(ID3D11Device* device);
    HRESULT CreateCounterStagingBuffer(ID3D11Device* device);

    void UpdateEmitConstantBuffer(ID3D11DeviceContext* context, uint32_t emitCount, float deltaTime, float totalTime);
    void UpdateSimulateConstantBuffer(
        ID3D11DeviceContext* context,
        float deltaTime,
        float totalTime,
        const XMMATRIX& view,
        const XMMATRIX& projection,
        uint32_t screenWidth,
        uint32_t screenHeight);
    void UpdateRenderConstantBuffer(
        ID3D11DeviceContext* context,
        const XMMATRIX& view,
        const XMMATRIX& projection,
        const XMFLOAT3& cameraPos);

    void SwapAliveListBuffers();

    // ---- Emitter identity ----

    std::string m_name;
    GPUEmitterSettings m_settings;

    // ---- Transform ----

    XMFLOAT3 m_position = {0, 0, 0};
    XMFLOAT3 m_rotation = {0, 0, 0};

    // ---- Playback state ----

    bool m_playing                = false;
    bool m_initialized            = false;
    float m_emissionAccumulator   = 0.0f;
    float m_elapsedTime           = 0.0f;
    float m_burstTimer            = 0.0f;
    uint32_t m_pendingBurst       = 0;
    uint32_t m_maxParticles       = 0;

    // ---- Particle pool (StructuredBuffer with UAV) ----

    ComPtr<ID3D11Buffer>              m_particleBuffer;
    ComPtr<ID3D11ShaderResourceView>  m_particleSRV;
    ComPtr<ID3D11UnorderedAccessView> m_particleUAV;

    // ---- Alive / Dead lists (Append/Consume structured buffers) ----

    ComPtr<ID3D11Buffer>              m_deadListBuffer;
    ComPtr<ID3D11UnorderedAccessView> m_deadListUAV;   ///< AppendStructuredBuffer

    ComPtr<ID3D11Buffer>              m_aliveListBuffer;
    ComPtr<ID3D11UnorderedAccessView> m_aliveListUAV;  ///< AppendStructuredBuffer
    ComPtr<ID3D11ShaderResourceView>  m_aliveListSRV;

    ComPtr<ID3D11Buffer>              m_aliveListBuffer2;   ///< Double-buffered alive list
    ComPtr<ID3D11UnorderedAccessView> m_aliveListUAV2;
    ComPtr<ID3D11ShaderResourceView>  m_aliveListSRV2;

    uint32_t m_currentAliveList   = 0; ///< 0 or 1, indexes the double-buffered alive list

    // ---- Indirect dispatch / draw argument buffers ----

    ComPtr<ID3D11Buffer> m_indirectDispatchBuffer;  ///< For DispatchIndirect
    ComPtr<ID3D11Buffer> m_indirectDrawBuffer;      ///< For DrawInstancedIndirect
    ComPtr<ID3D11UnorderedAccessView> m_indirectDispatchUAV;
    ComPtr<ID3D11UnorderedAccessView> m_indirectDrawUAV;

    // ---- Billboard vertex buffer ----

    ComPtr<ID3D11Buffer>              m_billboardVertexBuffer;
    ComPtr<ID3D11ShaderResourceView>  m_billboardSRV;
    ComPtr<ID3D11UnorderedAccessView> m_billboardUAV;

    // ---- Sort buffers ----

    ComPtr<ID3D11Buffer>              m_sortBuffer;
    ComPtr<ID3D11ShaderResourceView>  m_sortSRV;
    ComPtr<ID3D11UnorderedAccessView> m_sortUAV;

    ComPtr<ID3D11Buffer>              m_sortTempBuffer;
    ComPtr<ID3D11ShaderResourceView>  m_sortTempSRV;
    ComPtr<ID3D11UnorderedAccessView> m_sortTempUAV;

    // ---- Constant buffers ----

    ComPtr<ID3D11Buffer> m_emitCB;
    ComPtr<ID3D11Buffer> m_simulateCB;
    ComPtr<ID3D11Buffer> m_sortCB;
    ComPtr<ID3D11Buffer> m_renderCB;

    // ---- Staging buffer for GPU readback ----

    ComPtr<ID3D11Buffer> m_counterStagingBuffer;
};

// ============================================================================
// GPUParticleSystem
// ============================================================================

/**
 * @brief System-level manager for all GPU particle emitters
 *
 * Owns the shared compute shaders, manages emitter lifetimes, and
 * orchestrates the per-frame emit -> simulate -> sort -> render pipeline.
 * Integrates with the existing ParticleSystem via shared blend states and
 * optional fallback.
 */
class GPUParticleSystem
{
public:
    GPUParticleSystem();
    ~GPUParticleSystem();

    // Non-copyable
    GPUParticleSystem(const GPUParticleSystem&) = delete;
    GPUParticleSystem& operator=(const GPUParticleSystem&) = delete;

    // ---- Lifecycle ----

    /**
     * @brief Initialize the GPU particle system
     * @param device D3D11 device (must support compute shaders - feature level 11.0+)
     * @param context D3D11 immediate context
     * @param maxParticlesPerEmitter Default max particles per emitter
     * @return S_OK on success, error code on failure
     */
    HRESULT Initialize(
        ID3D11Device* device,
        ID3D11DeviceContext* context,
        uint32_t maxParticlesPerEmitter = GPUParticleConstants::DEFAULT_MAX_PARTICLES);

    /**
     * @brief Release all GPU resources and emitters
     */
    void Shutdown();

    /**
     * @brief Emit new particles across all active emitters
     * @param deltaTime Frame delta time
     */
    void Emit(float deltaTime);

    /**
     * @brief Update/simulate all active emitters
     * @param deltaTime Frame delta time
     * @param view Current camera view matrix
     * @param projection Current projection matrix
     * @param depthSRV Depth buffer SRV for collision (can be nullptr)
     * @param screenWidth Viewport width
     * @param screenHeight Viewport height
     */
    void Update(
        float deltaTime,
        const XMMATRIX& view,
        const XMMATRIX& projection,
        ID3D11ShaderResourceView* depthSRV = nullptr,
        uint32_t screenWidth = 0,
        uint32_t screenHeight = 0);

    /**
     * @brief Render all active emitters
     * @param view Camera view matrix
     * @param projection Projection matrix
     * @param cameraPos Camera world position
     */
    void Render(
        const XMMATRIX& view,
        const XMMATRIX& projection,
        const XMFLOAT3& cameraPos);

    // ---- Emitter management ----

    /**
     * @brief Create a new GPU particle emitter
     * @param name Unique name for the emitter
     * @param settings Emitter configuration
     * @param maxParticles Override max particles (0 = use system default)
     * @return Pointer to the created emitter, or nullptr on failure
     */
    GPUParticleEmitter* CreateEmitter(
        const std::string& name,
        const GPUEmitterSettings& settings,
        uint32_t maxParticles = 0);

    /**
     * @brief Get an emitter by name
     * @param name Emitter name
     * @return Pointer to emitter, or nullptr if not found
     */
    GPUParticleEmitter* GetEmitter(const std::string& name) const;

    /**
     * @brief Destroy a single emitter
     * @param name Emitter name
     */
    void DestroyEmitter(const std::string& name);

    /**
     * @brief Destroy all emitters
     */
    void DestroyAllEmitters();

    // ---- Preset effects (convenience, mirrors ParticleSystem API) ----

    GPUParticleEmitter* SpawnExplosion(const XMFLOAT3& position, float radius = 3.0f);
    GPUParticleEmitter* SpawnMuzzleFlash(const XMFLOAT3& position, const XMFLOAT3& direction);
    GPUParticleEmitter* SpawnSparks(const XMFLOAT3& position, const XMFLOAT3& normal, uint32_t count = 200);
    GPUParticleEmitter* SpawnSmoke(const XMFLOAT3& position, float duration = 3.0f);

    // ---- Metrics ----

    /**
     * @brief Get approximate total alive particles across all emitters
     *
     * This may stall the pipeline due to GPU readback. Use sparingly
     * (e.g., for debug UI, not every frame).
     */
    uint32_t GetTotalAliveParticles() const;

    uint32_t GetEmitterCount() const { return static_cast<uint32_t>(m_emitters.size()); }
    uint32_t GetMaxParticlesPerEmitter() const { return m_maxParticlesPerEmitter; }
    bool IsInitialized() const { return m_initialized; }

    // ---- Blend state access (shared with CPU particle system) ----

    ID3D11BlendState* GetBlendState(GPUParticleBlendMode mode) const;

    // ---- Console integration ----

    /**
     * @brief List all emitters and their status
     * @return Formatted string for console output
     */
    std::string Console_ListEmitters() const;

    /**
     * @brief Get detailed info about a specific emitter
     * @param name Emitter name
     * @return Formatted string for console output
     */
    std::string Console_GetEmitterInfo(const std::string& name) const;

    /**
     * @brief Spawn a preset effect from the console
     * @param effectType "explosion", "muzzleflash", "sparks", "smoke"
     * @param x World X position
     * @param y World Y position
     * @param z World Z position
     */
    void Console_SpawnEffect(const std::string& effectType, float x, float y, float z);

    /**
     * @brief Toggle depth collision globally
     * @param enabled Enable or disable
     */
    void Console_SetDepthCollision(bool enabled);

    /**
     * @brief Set global particle count scale
     * @param scale Multiplier for all emission rates (0.0 - 1.0 for reduction)
     */
    void Console_SetParticleScale(float scale);

private:
    // ---- Shader compilation ----

    HRESULT CompileComputeShaders();
    HRESULT CompileComputeShader(
        const char* hlslSource,
        const char* entryPoint,
        ID3D11ComputeShader** outShader);

    // ---- Blend / rasterizer state creation ----

    HRESULT CreateBlendStates();
    HRESULT CreateRenderStates();

    // ---- Shader source generation ----

    static const char* GetEmitShaderSource();
    static const char* GetSimulateShaderSource();
    static const char* GetBitonicSortShaderSource();
    static const char* GetTransposeShaderSource();
    static const char* GetBillboardShaderSource();

    // ---- Device references (non-owning) ----

    ID3D11Device*        m_device  = nullptr;
    ID3D11DeviceContext* m_context = nullptr;

    // ---- System state ----

    bool     m_initialized             = false;
    uint32_t m_maxParticlesPerEmitter  = GPUParticleConstants::DEFAULT_MAX_PARTICLES;
    float    m_totalTime               = 0.0f;
    float    m_globalEmissionScale     = 1.0f;
    bool     m_globalDepthCollision    = false;
    uint32_t m_nextEmitterID           = 0;

    // ---- Emitters ----

    std::unordered_map<std::string, std::unique_ptr<GPUParticleEmitter>> m_emitters;

    // ---- Shared compute shaders ----

    ComPtr<ID3D11ComputeShader> m_emitShader;
    ComPtr<ID3D11ComputeShader> m_simulateShader;
    ComPtr<ID3D11ComputeShader> m_bitonicSortShader;
    ComPtr<ID3D11ComputeShader> m_transposeShader;
    ComPtr<ID3D11ComputeShader> m_billboardShader;

    // ---- Shared render pipeline state ----

    ComPtr<ID3D11VertexShader>      m_billboardVS;
    ComPtr<ID3D11PixelShader>       m_billboardPS;
    ComPtr<ID3D11InputLayout>       m_billboardInputLayout;

    ComPtr<ID3D11BlendState>        m_additiveBlend;
    ComPtr<ID3D11BlendState>        m_alphaBlend;
    ComPtr<ID3D11BlendState>        m_multiplyBlend;
    ComPtr<ID3D11BlendState>        m_premultipliedBlend;

    ComPtr<ID3D11DepthStencilState> m_depthReadOnly;  ///< Depth test on, write off
    ComPtr<ID3D11RasterizerState>   m_noCullRasterizer;
    ComPtr<ID3D11SamplerState>      m_linearSampler;

    // ---- Shared texture (default white) ----

    ComPtr<ID3D11Texture2D>          m_defaultTexture;
    ComPtr<ID3D11ShaderResourceView> m_defaultTextureSRV;
};
